/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.banhang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DonHangChiTiet service. Represents a row in the &quot;minimart_donhangchitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.banhang.model.impl.DonHangChiTietModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.banhang.model.impl.DonHangChiTietImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DonHangChiTiet
 * @see com.minimart.portlet.banhang.model.impl.DonHangChiTietImpl
 * @see com.minimart.portlet.banhang.model.impl.DonHangChiTietModelImpl
 * @generated
 */
public interface DonHangChiTietModel extends AuditedModel,
	BaseModel<DonHangChiTiet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a don hang chi tiet model instance should use the {@link DonHangChiTiet} interface instead.
	 */

	/**
	 * Returns the primary key of this don hang chi tiet.
	 *
	 * @return the primary key of this don hang chi tiet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this don hang chi tiet.
	 *
	 * @param primaryKey the primary key of this don hang chi tiet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the don hang chi tiet ID of this don hang chi tiet.
	 *
	 * @return the don hang chi tiet ID of this don hang chi tiet
	 */
	public long getDonHangChiTietId();

	/**
	 * Sets the don hang chi tiet ID of this don hang chi tiet.
	 *
	 * @param donHangChiTietId the don hang chi tiet ID of this don hang chi tiet
	 */
	public void setDonHangChiTietId(long donHangChiTietId);

	/**
	 * Returns the company ID of this don hang chi tiet.
	 *
	 * @return the company ID of this don hang chi tiet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this don hang chi tiet.
	 *
	 * @param companyId the company ID of this don hang chi tiet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this don hang chi tiet.
	 *
	 * @return the user ID of this don hang chi tiet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this don hang chi tiet.
	 *
	 * @param userId the user ID of this don hang chi tiet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this don hang chi tiet.
	 *
	 * @return the user uuid of this don hang chi tiet
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this don hang chi tiet.
	 *
	 * @param userUuid the user uuid of this don hang chi tiet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this don hang chi tiet.
	 *
	 * @return the user name of this don hang chi tiet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this don hang chi tiet.
	 *
	 * @param userName the user name of this don hang chi tiet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this don hang chi tiet.
	 *
	 * @return the create date of this don hang chi tiet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this don hang chi tiet.
	 *
	 * @param createDate the create date of this don hang chi tiet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this don hang chi tiet.
	 *
	 * @return the modified date of this don hang chi tiet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this don hang chi tiet.
	 *
	 * @param modifiedDate the modified date of this don hang chi tiet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the don hang ID of this don hang chi tiet.
	 *
	 * @return the don hang ID of this don hang chi tiet
	 */
	public long getDonHangId();

	/**
	 * Sets the don hang ID of this don hang chi tiet.
	 *
	 * @param donHangId the don hang ID of this don hang chi tiet
	 */
	public void setDonHangId(long donHangId);

	/**
	 * Returns the mat hang ID of this don hang chi tiet.
	 *
	 * @return the mat hang ID of this don hang chi tiet
	 */
	public long getMatHangId();

	/**
	 * Sets the mat hang ID of this don hang chi tiet.
	 *
	 * @param matHangId the mat hang ID of this don hang chi tiet
	 */
	public void setMatHangId(long matHangId);

	/**
	 * Returns the so luong of this don hang chi tiet.
	 *
	 * @return the so luong of this don hang chi tiet
	 */
	public int getSoLuong();

	/**
	 * Sets the so luong of this don hang chi tiet.
	 *
	 * @param soLuong the so luong of this don hang chi tiet
	 */
	public void setSoLuong(int soLuong);

	/**
	 * Returns the don vi tinh ID of this don hang chi tiet.
	 *
	 * @return the don vi tinh ID of this don hang chi tiet
	 */
	public long getDonViTinhId();

	/**
	 * Sets the don vi tinh ID of this don hang chi tiet.
	 *
	 * @param donViTinhId the don vi tinh ID of this don hang chi tiet
	 */
	public void setDonViTinhId(long donViTinhId);

	/**
	 * Returns the thanh tien of this don hang chi tiet.
	 *
	 * @return the thanh tien of this don hang chi tiet
	 */
	public int getThanhTien();

	/**
	 * Sets the thanh tien of this don hang chi tiet.
	 *
	 * @param thanhTien the thanh tien of this don hang chi tiet
	 */
	public void setThanhTien(int thanhTien);

	/**
	 * Returns the ti le giam gia of this don hang chi tiet.
	 *
	 * @return the ti le giam gia of this don hang chi tiet
	 */
	public int getTiLeGiamGia();

	/**
	 * Sets the ti le giam gia of this don hang chi tiet.
	 *
	 * @param tiLeGiamGia the ti le giam gia of this don hang chi tiet
	 */
	public void setTiLeGiamGia(int tiLeGiamGia);

	/**
	 * Returns the kich thuoc of this don hang chi tiet.
	 *
	 * @return the kich thuoc of this don hang chi tiet
	 */
	@AutoEscape
	public String getKichThuoc();

	/**
	 * Sets the kich thuoc of this don hang chi tiet.
	 *
	 * @param kichThuoc the kich thuoc of this don hang chi tiet
	 */
	public void setKichThuoc(String kichThuoc);

	/**
	 * Returns the han su dung of this don hang chi tiet.
	 *
	 * @return the han su dung of this don hang chi tiet
	 */
	public Date getHanSuDung();

	/**
	 * Sets the han su dung of this don hang chi tiet.
	 *
	 * @param hanSuDung the han su dung of this don hang chi tiet
	 */
	public void setHanSuDung(Date hanSuDung);

	/**
	 * Returns the hoat dong of this don hang chi tiet.
	 *
	 * @return the hoat dong of this don hang chi tiet
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this don hang chi tiet is hoat dong.
	 *
	 * @return <code>true</code> if this don hang chi tiet is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this don hang chi tiet is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this don hang chi tiet
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the huy of this don hang chi tiet.
	 *
	 * @return the huy of this don hang chi tiet
	 */
	public boolean getHuy();

	/**
	 * Returns <code>true</code> if this don hang chi tiet is huy.
	 *
	 * @return <code>true</code> if this don hang chi tiet is huy; <code>false</code> otherwise
	 */
	public boolean isHuy();

	/**
	 * Sets whether this don hang chi tiet is huy.
	 *
	 * @param huy the huy of this don hang chi tiet
	 */
	public void setHuy(boolean huy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.banhang.model.DonHangChiTiet donHangChiTiet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.banhang.model.DonHangChiTiet> toCacheModel();

	@Override
	public com.minimart.portlet.banhang.model.DonHangChiTiet toEscapedModel();

	@Override
	public com.minimart.portlet.banhang.model.DonHangChiTiet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}