/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.banhang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DonHang service. Represents a row in the &quot;minimart_donhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.banhang.model.impl.DonHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.banhang.model.impl.DonHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DonHang
 * @see com.minimart.portlet.banhang.model.impl.DonHangImpl
 * @see com.minimart.portlet.banhang.model.impl.DonHangModelImpl
 * @generated
 */
public interface DonHangModel extends AuditedModel, BaseModel<DonHang> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a don hang model instance should use the {@link DonHang} interface instead.
	 */

	/**
	 * Returns the primary key of this don hang.
	 *
	 * @return the primary key of this don hang
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this don hang.
	 *
	 * @param primaryKey the primary key of this don hang
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the don hang ID of this don hang.
	 *
	 * @return the don hang ID of this don hang
	 */
	public long getDonHangId();

	/**
	 * Sets the don hang ID of this don hang.
	 *
	 * @param donHangId the don hang ID of this don hang
	 */
	public void setDonHangId(long donHangId);

	/**
	 * Returns the company ID of this don hang.
	 *
	 * @return the company ID of this don hang
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this don hang.
	 *
	 * @param companyId the company ID of this don hang
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this don hang.
	 *
	 * @return the user ID of this don hang
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this don hang.
	 *
	 * @param userId the user ID of this don hang
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this don hang.
	 *
	 * @return the user uuid of this don hang
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this don hang.
	 *
	 * @param userUuid the user uuid of this don hang
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this don hang.
	 *
	 * @return the user name of this don hang
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this don hang.
	 *
	 * @param userName the user name of this don hang
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this don hang.
	 *
	 * @return the create date of this don hang
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this don hang.
	 *
	 * @param createDate the create date of this don hang
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this don hang.
	 *
	 * @return the modified date of this don hang
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this don hang.
	 *
	 * @param modifiedDate the modified date of this don hang
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cua hang ID of this don hang.
	 *
	 * @return the cua hang ID of this don hang
	 */
	public long getCuaHangId();

	/**
	 * Sets the cua hang ID of this don hang.
	 *
	 * @param cuaHangId the cua hang ID of this don hang
	 */
	public void setCuaHangId(long cuaHangId);

	/**
	 * Returns the khach hang ID of this don hang.
	 *
	 * @return the khach hang ID of this don hang
	 */
	public long getKhachHangId();

	/**
	 * Sets the khach hang ID of this don hang.
	 *
	 * @param khachHangId the khach hang ID of this don hang
	 */
	public void setKhachHangId(long khachHangId);

	/**
	 * Returns the hoat dong of this don hang.
	 *
	 * @return the hoat dong of this don hang
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this don hang is hoat dong.
	 *
	 * @return <code>true</code> if this don hang is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this don hang is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this don hang
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the tong cong of this don hang.
	 *
	 * @return the tong cong of this don hang
	 */
	public int getTongCong();

	/**
	 * Sets the tong cong of this don hang.
	 *
	 * @param tongCong the tong cong of this don hang
	 */
	public void setTongCong(int tongCong);

	/**
	 * Returns the da thanh toan of this don hang.
	 *
	 * @return the da thanh toan of this don hang
	 */
	public boolean getDaThanhToan();

	/**
	 * Returns <code>true</code> if this don hang is da thanh toan.
	 *
	 * @return <code>true</code> if this don hang is da thanh toan; <code>false</code> otherwise
	 */
	public boolean isDaThanhToan();

	/**
	 * Sets whether this don hang is da thanh toan.
	 *
	 * @param daThanhToan the da thanh toan of this don hang
	 */
	public void setDaThanhToan(boolean daThanhToan);

	/**
	 * Returns the phi van chuyen of this don hang.
	 *
	 * @return the phi van chuyen of this don hang
	 */
	public int getPhiVanChuyen();

	/**
	 * Sets the phi van chuyen of this don hang.
	 *
	 * @param phiVanChuyen the phi van chuyen of this don hang
	 */
	public void setPhiVanChuyen(int phiVanChuyen);

	/**
	 * Returns the trang thai don hang ID of this don hang.
	 *
	 * @return the trang thai don hang ID of this don hang
	 */
	public long getTrangThaiDonHangId();

	/**
	 * Sets the trang thai don hang ID of this don hang.
	 *
	 * @param trangThaiDonHangId the trang thai don hang ID of this don hang
	 */
	public void setTrangThaiDonHangId(long trangThaiDonHangId);

	/**
	 * Returns the ngay thanh toan of this don hang.
	 *
	 * @return the ngay thanh toan of this don hang
	 */
	public Date getNgayThanhToan();

	/**
	 * Sets the ngay thanh toan of this don hang.
	 *
	 * @param ngayThanhToan the ngay thanh toan of this don hang
	 */
	public void setNgayThanhToan(Date ngayThanhToan);

	/**
	 * Returns the khach dua of this don hang.
	 *
	 * @return the khach dua of this don hang
	 */
	public int getKhachDua();

	/**
	 * Sets the khach dua of this don hang.
	 *
	 * @param khachDua the khach dua of this don hang
	 */
	public void setKhachDua(int khachDua);

	/**
	 * Returns the tra lai of this don hang.
	 *
	 * @return the tra lai of this don hang
	 */
	public int getTraLai();

	/**
	 * Sets the tra lai of this don hang.
	 *
	 * @param traLai the tra lai of this don hang
	 */
	public void setTraLai(int traLai);

	/**
	 * Returns the thue v a t of this don hang.
	 *
	 * @return the thue v a t of this don hang
	 */
	public int getThueVAT();

	/**
	 * Sets the thue v a t of this don hang.
	 *
	 * @param thueVAT the thue v a t of this don hang
	 */
	public void setThueVAT(int thueVAT);

	/**
	 * Returns the diem tich luy of this don hang.
	 *
	 * @return the diem tich luy of this don hang
	 */
	public int getDiemTichLuy();

	/**
	 * Sets the diem tich luy of this don hang.
	 *
	 * @param diemTichLuy the diem tich luy of this don hang
	 */
	public void setDiemTichLuy(int diemTichLuy);

	/**
	 * Returns the thanh toan tien mat of this don hang.
	 *
	 * @return the thanh toan tien mat of this don hang
	 */
	public int getThanhToanTienMat();

	/**
	 * Sets the thanh toan tien mat of this don hang.
	 *
	 * @param thanhToanTienMat the thanh toan tien mat of this don hang
	 */
	public void setThanhToanTienMat(int thanhToanTienMat);

	/**
	 * Returns the thanh toan the of this don hang.
	 *
	 * @return the thanh toan the of this don hang
	 */
	public int getThanhToanThe();

	/**
	 * Sets the thanh toan the of this don hang.
	 *
	 * @param thanhToanThe the thanh toan the of this don hang
	 */
	public void setThanhToanThe(int thanhToanThe);

	/**
	 * Returns the thanh toan chuyen khoan of this don hang.
	 *
	 * @return the thanh toan chuyen khoan of this don hang
	 */
	public int getThanhToanChuyenKhoan();

	/**
	 * Sets the thanh toan chuyen khoan of this don hang.
	 *
	 * @param thanhToanChuyenKhoan the thanh toan chuyen khoan of this don hang
	 */
	public void setThanhToanChuyenKhoan(int thanhToanChuyenKhoan);

	/**
	 * Returns the phieu giam gia ID of this don hang.
	 *
	 * @return the phieu giam gia ID of this don hang
	 */
	public long getPhieuGiamGiaId();

	/**
	 * Sets the phieu giam gia ID of this don hang.
	 *
	 * @param phieuGiamGiaId the phieu giam gia ID of this don hang
	 */
	public void setPhieuGiamGiaId(long phieuGiamGiaId);

	/**
	 * Returns the tru tich luy of this don hang.
	 *
	 * @return the tru tich luy of this don hang
	 */
	public int getTruTichLuy();

	/**
	 * Sets the tru tich luy of this don hang.
	 *
	 * @param truTichLuy the tru tich luy of this don hang
	 */
	public void setTruTichLuy(int truTichLuy);

	/**
	 * Returns the in hoa don lan of this don hang.
	 *
	 * @return the in hoa don lan of this don hang
	 */
	public int getInHoaDonLan();

	/**
	 * Sets the in hoa don lan of this don hang.
	 *
	 * @param inHoaDonLan the in hoa don lan of this don hang
	 */
	public void setInHoaDonLan(int inHoaDonLan);

	/**
	 * Returns the ma don hang of this don hang.
	 *
	 * @return the ma don hang of this don hang
	 */
	@AutoEscape
	public String getMaDonHang();

	/**
	 * Sets the ma don hang of this don hang.
	 *
	 * @param maDonHang the ma don hang of this don hang
	 */
	public void setMaDonHang(String maDonHang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.banhang.model.DonHang donHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.banhang.model.DonHang> toCacheModel();

	@Override
	public com.minimart.portlet.banhang.model.DonHang toEscapedModel();

	@Override
	public com.minimart.portlet.banhang.model.DonHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}