/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.banhang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TrangThaiDonHang service. Represents a row in the &quot;minimart_trangthaidonhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.banhang.model.impl.TrangThaiDonHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.banhang.model.impl.TrangThaiDonHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see TrangThaiDonHang
 * @see com.minimart.portlet.banhang.model.impl.TrangThaiDonHangImpl
 * @see com.minimart.portlet.banhang.model.impl.TrangThaiDonHangModelImpl
 * @generated
 */
public interface TrangThaiDonHangModel extends AuditedModel,
	BaseModel<TrangThaiDonHang> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trang thai don hang model instance should use the {@link TrangThaiDonHang} interface instead.
	 */

	/**
	 * Returns the primary key of this trang thai don hang.
	 *
	 * @return the primary key of this trang thai don hang
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trang thai don hang.
	 *
	 * @param primaryKey the primary key of this trang thai don hang
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the trang thai don hang ID of this trang thai don hang.
	 *
	 * @return the trang thai don hang ID of this trang thai don hang
	 */
	public long getTrangThaiDonHangId();

	/**
	 * Sets the trang thai don hang ID of this trang thai don hang.
	 *
	 * @param trangThaiDonHangId the trang thai don hang ID of this trang thai don hang
	 */
	public void setTrangThaiDonHangId(long trangThaiDonHangId);

	/**
	 * Returns the company ID of this trang thai don hang.
	 *
	 * @return the company ID of this trang thai don hang
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this trang thai don hang.
	 *
	 * @param companyId the company ID of this trang thai don hang
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this trang thai don hang.
	 *
	 * @return the user ID of this trang thai don hang
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this trang thai don hang.
	 *
	 * @param userId the user ID of this trang thai don hang
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this trang thai don hang.
	 *
	 * @return the user uuid of this trang thai don hang
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this trang thai don hang.
	 *
	 * @param userUuid the user uuid of this trang thai don hang
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this trang thai don hang.
	 *
	 * @return the user name of this trang thai don hang
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this trang thai don hang.
	 *
	 * @param userName the user name of this trang thai don hang
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this trang thai don hang.
	 *
	 * @return the create date of this trang thai don hang
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this trang thai don hang.
	 *
	 * @param createDate the create date of this trang thai don hang
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this trang thai don hang.
	 *
	 * @return the modified date of this trang thai don hang
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this trang thai don hang.
	 *
	 * @param modifiedDate the modified date of this trang thai don hang
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this trang thai don hang.
	 *
	 * @return the ten of this trang thai don hang
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this trang thai don hang.
	 *
	 * @param ten the ten of this trang thai don hang
	 */
	public void setTen(String ten);

	/**
	 * Returns the hoat dong of this trang thai don hang.
	 *
	 * @return the hoat dong of this trang thai don hang
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this trang thai don hang is hoat dong.
	 *
	 * @return <code>true</code> if this trang thai don hang is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this trang thai don hang is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this trang thai don hang
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the ghi chu of this trang thai don hang.
	 *
	 * @return the ghi chu of this trang thai don hang
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this trang thai don hang.
	 *
	 * @param ghiChu the ghi chu of this trang thai don hang
	 */
	public void setGhiChu(String ghiChu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.banhang.model.TrangThaiDonHang trangThaiDonHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.banhang.model.TrangThaiDonHang> toCacheModel();

	@Override
	public com.minimart.portlet.banhang.model.TrangThaiDonHang toEscapedModel();

	@Override
	public com.minimart.portlet.banhang.model.TrangThaiDonHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}