/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khohang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KhoHang service. Represents a row in the &quot;minimart_khohang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.khohang.model.impl.KhoHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.khohang.model.impl.KhoHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see KhoHang
 * @see com.minimart.portlet.khohang.model.impl.KhoHangImpl
 * @see com.minimart.portlet.khohang.model.impl.KhoHangModelImpl
 * @generated
 */
public interface KhoHangModel extends AuditedModel, BaseModel<KhoHang> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kho hang model instance should use the {@link KhoHang} interface instead.
	 */

	/**
	 * Returns the primary key of this kho hang.
	 *
	 * @return the primary key of this kho hang
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kho hang.
	 *
	 * @param primaryKey the primary key of this kho hang
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the kho hang ID of this kho hang.
	 *
	 * @return the kho hang ID of this kho hang
	 */
	public long getKhoHangId();

	/**
	 * Sets the kho hang ID of this kho hang.
	 *
	 * @param khoHangId the kho hang ID of this kho hang
	 */
	public void setKhoHangId(long khoHangId);

	/**
	 * Returns the company ID of this kho hang.
	 *
	 * @return the company ID of this kho hang
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this kho hang.
	 *
	 * @param companyId the company ID of this kho hang
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this kho hang.
	 *
	 * @return the user ID of this kho hang
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this kho hang.
	 *
	 * @param userId the user ID of this kho hang
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this kho hang.
	 *
	 * @return the user uuid of this kho hang
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this kho hang.
	 *
	 * @param userUuid the user uuid of this kho hang
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this kho hang.
	 *
	 * @return the user name of this kho hang
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this kho hang.
	 *
	 * @param userName the user name of this kho hang
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this kho hang.
	 *
	 * @return the create date of this kho hang
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this kho hang.
	 *
	 * @param createDate the create date of this kho hang
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this kho hang.
	 *
	 * @return the modified date of this kho hang
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this kho hang.
	 *
	 * @param modifiedDate the modified date of this kho hang
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this kho hang.
	 *
	 * @return the ten of this kho hang
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this kho hang.
	 *
	 * @param ten the ten of this kho hang
	 */
	public void setTen(String ten);

	/**
	 * Returns the trang thai of this kho hang.
	 *
	 * @return the trang thai of this kho hang
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this kho hang is trang thai.
	 *
	 * @return <code>true</code> if this kho hang is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this kho hang is trang thai.
	 *
	 * @param trangThai the trang thai of this kho hang
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the item type of this kho hang.
	 *
	 * @return the item type of this kho hang
	 */
	public int getItemType();

	/**
	 * Sets the item type of this kho hang.
	 *
	 * @param itemType the item type of this kho hang
	 */
	public void setItemType(int itemType);

	/**
	 * Returns the cho phep nhap kho of this kho hang.
	 *
	 * @return the cho phep nhap kho of this kho hang
	 */
	public boolean getChoPhepNhapKho();

	/**
	 * Returns <code>true</code> if this kho hang is cho phep nhap kho.
	 *
	 * @return <code>true</code> if this kho hang is cho phep nhap kho; <code>false</code> otherwise
	 */
	public boolean isChoPhepNhapKho();

	/**
	 * Sets whether this kho hang is cho phep nhap kho.
	 *
	 * @param choPhepNhapKho the cho phep nhap kho of this kho hang
	 */
	public void setChoPhepNhapKho(boolean choPhepNhapKho);

	/**
	 * Returns the cua hang ID of this kho hang.
	 *
	 * @return the cua hang ID of this kho hang
	 */
	public long getCuaHangId();

	/**
	 * Sets the cua hang ID of this kho hang.
	 *
	 * @param cuaHangId the cua hang ID of this kho hang
	 */
	public void setCuaHangId(long cuaHangId);

	/**
	 * Returns the auto ID of this kho hang.
	 *
	 * @return the auto ID of this kho hang
	 */
	public long getAutoId();

	/**
	 * Sets the auto ID of this kho hang.
	 *
	 * @param autoId the auto ID of this kho hang
	 */
	public void setAutoId(long autoId);

	/**
	 * Returns the sigma ID of this kho hang.
	 *
	 * @return the sigma ID of this kho hang
	 */
	public long getSigmaId();

	/**
	 * Sets the sigma ID of this kho hang.
	 *
	 * @param sigmaId the sigma ID of this kho hang
	 */
	public void setSigmaId(long sigmaId);

	/**
	 * Returns the ghi chu of this kho hang.
	 *
	 * @return the ghi chu of this kho hang
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this kho hang.
	 *
	 * @param ghiChu the ghi chu of this kho hang
	 */
	public void setGhiChu(String ghiChu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.khohang.model.KhoHang khoHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.khohang.model.KhoHang> toCacheModel();

	@Override
	public com.minimart.portlet.khohang.model.KhoHang toEscapedModel();

	@Override
	public com.minimart.portlet.khohang.model.KhoHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}