/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khachhang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KhachHang service. Represents a row in the &quot;minimart_khachhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.khachhang.model.impl.KhachHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.khachhang.model.impl.KhachHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see KhachHang
 * @see com.minimart.portlet.khachhang.model.impl.KhachHangImpl
 * @see com.minimart.portlet.khachhang.model.impl.KhachHangModelImpl
 * @generated
 */
public interface KhachHangModel extends AuditedModel, BaseModel<KhachHang> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a khach hang model instance should use the {@link KhachHang} interface instead.
	 */

	/**
	 * Returns the primary key of this khach hang.
	 *
	 * @return the primary key of this khach hang
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this khach hang.
	 *
	 * @param primaryKey the primary key of this khach hang
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the khach hang ID of this khach hang.
	 *
	 * @return the khach hang ID of this khach hang
	 */
	public long getKhachHangId();

	/**
	 * Sets the khach hang ID of this khach hang.
	 *
	 * @param khachHangId the khach hang ID of this khach hang
	 */
	public void setKhachHangId(long khachHangId);

	/**
	 * Returns the company ID of this khach hang.
	 *
	 * @return the company ID of this khach hang
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this khach hang.
	 *
	 * @param companyId the company ID of this khach hang
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this khach hang.
	 *
	 * @return the user ID of this khach hang
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this khach hang.
	 *
	 * @param userId the user ID of this khach hang
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this khach hang.
	 *
	 * @return the user uuid of this khach hang
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this khach hang.
	 *
	 * @param userUuid the user uuid of this khach hang
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this khach hang.
	 *
	 * @return the user name of this khach hang
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this khach hang.
	 *
	 * @param userName the user name of this khach hang
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this khach hang.
	 *
	 * @return the create date of this khach hang
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this khach hang.
	 *
	 * @param createDate the create date of this khach hang
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this khach hang.
	 *
	 * @return the modified date of this khach hang
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this khach hang.
	 *
	 * @param modifiedDate the modified date of this khach hang
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this khach hang.
	 *
	 * @return the ten of this khach hang
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this khach hang.
	 *
	 * @param ten the ten of this khach hang
	 */
	public void setTen(String ten);

	/**
	 * Returns the nhom khach hang ID of this khach hang.
	 *
	 * @return the nhom khach hang ID of this khach hang
	 */
	public long getNhomKhachHangId();

	/**
	 * Sets the nhom khach hang ID of this khach hang.
	 *
	 * @param nhomKhachHangId the nhom khach hang ID of this khach hang
	 */
	public void setNhomKhachHangId(long nhomKhachHangId);

	/**
	 * Returns the ma of this khach hang.
	 *
	 * @return the ma of this khach hang
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this khach hang.
	 *
	 * @param ma the ma of this khach hang
	 */
	public void setMa(String ma);

	/**
	 * Returns the dia chi of this khach hang.
	 *
	 * @return the dia chi of this khach hang
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this khach hang.
	 *
	 * @param diaChi the dia chi of this khach hang
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the dien thoai of this khach hang.
	 *
	 * @return the dien thoai of this khach hang
	 */
	@AutoEscape
	public String getDienThoai();

	/**
	 * Sets the dien thoai of this khach hang.
	 *
	 * @param dienThoai the dien thoai of this khach hang
	 */
	public void setDienThoai(String dienThoai);

	/**
	 * Returns the email of this khach hang.
	 *
	 * @return the email of this khach hang
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this khach hang.
	 *
	 * @param email the email of this khach hang
	 */
	public void setEmail(String email);

	/**
	 * Returns the facebook of this khach hang.
	 *
	 * @return the facebook of this khach hang
	 */
	@AutoEscape
	public String getFacebook();

	/**
	 * Sets the facebook of this khach hang.
	 *
	 * @param facebook the facebook of this khach hang
	 */
	public void setFacebook(String facebook);

	/**
	 * Returns the twitter of this khach hang.
	 *
	 * @return the twitter of this khach hang
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this khach hang.
	 *
	 * @param twitter the twitter of this khach hang
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the social media1 of this khach hang.
	 *
	 * @return the social media1 of this khach hang
	 */
	@AutoEscape
	public String getSocialMedia1();

	/**
	 * Sets the social media1 of this khach hang.
	 *
	 * @param socialMedia1 the social media1 of this khach hang
	 */
	public void setSocialMedia1(String socialMedia1);

	/**
	 * Returns the social media2 of this khach hang.
	 *
	 * @return the social media2 of this khach hang
	 */
	@AutoEscape
	public String getSocialMedia2();

	/**
	 * Sets the social media2 of this khach hang.
	 *
	 * @param socialMedia2 the social media2 of this khach hang
	 */
	public void setSocialMedia2(String socialMedia2);

	/**
	 * Returns the social media3 of this khach hang.
	 *
	 * @return the social media3 of this khach hang
	 */
	@AutoEscape
	public String getSocialMedia3();

	/**
	 * Sets the social media3 of this khach hang.
	 *
	 * @param socialMedia3 the social media3 of this khach hang
	 */
	public void setSocialMedia3(String socialMedia3);

	/**
	 * Returns the trang thai of this khach hang.
	 *
	 * @return the trang thai of this khach hang
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this khach hang.
	 *
	 * @param trangThai the trang thai of this khach hang
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the diem tich luy of this khach hang.
	 *
	 * @return the diem tich luy of this khach hang
	 */
	public int getDiemTichLuy();

	/**
	 * Sets the diem tich luy of this khach hang.
	 *
	 * @param diemTichLuy the diem tich luy of this khach hang
	 */
	public void setDiemTichLuy(int diemTichLuy);

	/**
	 * Returns the ma so thue of this khach hang.
	 *
	 * @return the ma so thue of this khach hang
	 */
	@AutoEscape
	public String getMaSoThue();

	/**
	 * Sets the ma so thue of this khach hang.
	 *
	 * @param maSoThue the ma so thue of this khach hang
	 */
	public void setMaSoThue(String maSoThue);

	/**
	 * Returns the hoat dong of this khach hang.
	 *
	 * @return the hoat dong of this khach hang
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this khach hang is hoat dong.
	 *
	 * @return <code>true</code> if this khach hang is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this khach hang is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this khach hang
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the ngay sinh of this khach hang.
	 *
	 * @return the ngay sinh of this khach hang
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this khach hang.
	 *
	 * @param ngaySinh the ngay sinh of this khach hang
	 */
	public void setNgaySinh(Date ngaySinh);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.khachhang.model.KhachHang khachHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.khachhang.model.KhachHang> toCacheModel();

	@Override
	public com.minimart.portlet.khachhang.model.KhachHang toEscapedModel();

	@Override
	public com.minimart.portlet.khachhang.model.KhachHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}