/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.thethanhtoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TheTraTruoc service. Represents a row in the &quot;minimart_thetratruoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.thethanhtoan.model.impl.TheTraTruocModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.thethanhtoan.model.impl.TheTraTruocImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see TheTraTruoc
 * @see com.minimart.portlet.thethanhtoan.model.impl.TheTraTruocImpl
 * @see com.minimart.portlet.thethanhtoan.model.impl.TheTraTruocModelImpl
 * @generated
 */
public interface TheTraTruocModel extends AuditedModel, BaseModel<TheTraTruoc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a the tra truoc model instance should use the {@link TheTraTruoc} interface instead.
	 */

	/**
	 * Returns the primary key of this the tra truoc.
	 *
	 * @return the primary key of this the tra truoc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this the tra truoc.
	 *
	 * @param primaryKey the primary key of this the tra truoc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the the tra truoc ID of this the tra truoc.
	 *
	 * @return the the tra truoc ID of this the tra truoc
	 */
	public long getTheTraTruocId();

	/**
	 * Sets the the tra truoc ID of this the tra truoc.
	 *
	 * @param theTraTruocId the the tra truoc ID of this the tra truoc
	 */
	public void setTheTraTruocId(long theTraTruocId);

	/**
	 * Returns the company ID of this the tra truoc.
	 *
	 * @return the company ID of this the tra truoc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this the tra truoc.
	 *
	 * @param companyId the company ID of this the tra truoc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this the tra truoc.
	 *
	 * @return the user ID of this the tra truoc
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this the tra truoc.
	 *
	 * @param userId the user ID of this the tra truoc
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this the tra truoc.
	 *
	 * @return the user uuid of this the tra truoc
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this the tra truoc.
	 *
	 * @param userUuid the user uuid of this the tra truoc
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this the tra truoc.
	 *
	 * @return the user name of this the tra truoc
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this the tra truoc.
	 *
	 * @param userName the user name of this the tra truoc
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this the tra truoc.
	 *
	 * @return the create date of this the tra truoc
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this the tra truoc.
	 *
	 * @param createDate the create date of this the tra truoc
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this the tra truoc.
	 *
	 * @return the modified date of this the tra truoc
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this the tra truoc.
	 *
	 * @param modifiedDate the modified date of this the tra truoc
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten the of this the tra truoc.
	 *
	 * @return the ten the of this the tra truoc
	 */
	@AutoEscape
	public String getTenThe();

	/**
	 * Sets the ten the of this the tra truoc.
	 *
	 * @param tenThe the ten the of this the tra truoc
	 */
	public void setTenThe(String tenThe);

	/**
	 * Returns the nhom the tra truoc ID of this the tra truoc.
	 *
	 * @return the nhom the tra truoc ID of this the tra truoc
	 */
	public long getNhomTheTraTruocId();

	/**
	 * Sets the nhom the tra truoc ID of this the tra truoc.
	 *
	 * @param nhomTheTraTruocId the nhom the tra truoc ID of this the tra truoc
	 */
	public void setNhomTheTraTruocId(long nhomTheTraTruocId);

	/**
	 * Returns the khoa of this the tra truoc.
	 *
	 * @return the khoa of this the tra truoc
	 */
	public boolean getKhoa();

	/**
	 * Returns <code>true</code> if this the tra truoc is khoa.
	 *
	 * @return <code>true</code> if this the tra truoc is khoa; <code>false</code> otherwise
	 */
	public boolean isKhoa();

	/**
	 * Sets whether this the tra truoc is khoa.
	 *
	 * @param khoa the khoa of this the tra truoc
	 */
	public void setKhoa(boolean khoa);

	/**
	 * Returns the ngay het han of this the tra truoc.
	 *
	 * @return the ngay het han of this the tra truoc
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this the tra truoc.
	 *
	 * @param ngayHetHan the ngay het han of this the tra truoc
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the trang thai of this the tra truoc.
	 *
	 * @return the trang thai of this the tra truoc
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this the tra truoc.
	 *
	 * @param trangThai the trang thai of this the tra truoc
	 */
	public void setTrangThai(String trangThai);

	/**
	 * Returns the user modifiled ID of this the tra truoc.
	 *
	 * @return the user modifiled ID of this the tra truoc
	 */
	public long getUserModifiledId();

	/**
	 * Sets the user modifiled ID of this the tra truoc.
	 *
	 * @param userModifiledId the user modifiled ID of this the tra truoc
	 */
	public void setUserModifiledId(long userModifiledId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.thethanhtoan.model.TheTraTruoc theTraTruoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.thethanhtoan.model.TheTraTruoc> toCacheModel();

	@Override
	public com.minimart.portlet.thethanhtoan.model.TheTraTruoc toEscapedModel();

	@Override
	public com.minimart.portlet.thethanhtoan.model.TheTraTruoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}