/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.nhacungcap.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.nhacungcap.model.NhomNhaCungCap;
import com.minimart.portlet.nhacungcap.model.NhomNhaCungCapModel;
import com.minimart.portlet.nhacungcap.model.NhomNhaCungCapSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the NhomNhaCungCap service. Represents a row in the &quot;minimart_nhomnhacungcap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.nhacungcap.model.NhomNhaCungCapModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NhomNhaCungCapImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see NhomNhaCungCapImpl
 * @see com.minimart.portlet.nhacungcap.model.NhomNhaCungCap
 * @see com.minimart.portlet.nhacungcap.model.NhomNhaCungCapModel
 * @generated
 */
@JSON(strict = true)
public class NhomNhaCungCapModelImpl extends BaseModelImpl<NhomNhaCungCap>
	implements NhomNhaCungCapModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nhom nha cung cap model instance should use the {@link com.minimart.portlet.nhacungcap.model.NhomNhaCungCap} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_nhomnhacungcap";
	public static final Object[][] TABLE_COLUMNS = {
			{ "nhomNhaCungCapId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "ghiChu", Types.VARCHAR },
			{ "hoatDong", Types.BOOLEAN },
			{ "uuTien", Types.INTEGER },
			{ "image", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_nhomnhacungcap (nhomNhaCungCapId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,ghiChu VARCHAR(75) null,hoatDong BOOLEAN,uuTien INTEGER,image VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_nhomnhacungcap";
	public static final String ORDER_BY_JPQL = " ORDER BY nhomNhaCungCap.ten ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_nhomnhacungcap.ten ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.nhacungcap.model.NhomNhaCungCap"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.nhacungcap.model.NhomNhaCungCap"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.nhacungcap.model.NhomNhaCungCap"),
			true);
	public static long HOATDONG_COLUMN_BITMASK = 1L;
	public static long TEN_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NhomNhaCungCap toModel(NhomNhaCungCapSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NhomNhaCungCap model = new NhomNhaCungCapImpl();

		model.setNhomNhaCungCapId(soapModel.getNhomNhaCungCapId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setGhiChu(soapModel.getGhiChu());
		model.setHoatDong(soapModel.getHoatDong());
		model.setUuTien(soapModel.getUuTien());
		model.setImage(soapModel.getImage());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NhomNhaCungCap> toModels(NhomNhaCungCapSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NhomNhaCungCap> models = new ArrayList<NhomNhaCungCap>(soapModels.length);

		for (NhomNhaCungCapSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.nhacungcap.model.NhomNhaCungCap"));

	public NhomNhaCungCapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _nhomNhaCungCapId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNhomNhaCungCapId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _nhomNhaCungCapId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NhomNhaCungCap.class;
	}

	@Override
	public String getModelClassName() {
		return NhomNhaCungCap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("nhomNhaCungCapId", getNhomNhaCungCapId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("hoatDong", getHoatDong());
		attributes.put("uuTien", getUuTien());
		attributes.put("image", getImage());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long nhomNhaCungCapId = (Long)attributes.get("nhomNhaCungCapId");

		if (nhomNhaCungCapId != null) {
			setNhomNhaCungCapId(nhomNhaCungCapId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Boolean hoatDong = (Boolean)attributes.get("hoatDong");

		if (hoatDong != null) {
			setHoatDong(hoatDong);
		}

		Integer uuTien = (Integer)attributes.get("uuTien");

		if (uuTien != null) {
			setUuTien(uuTien);
		}

		String image = (String)attributes.get("image");

		if (image != null) {
			setImage(image);
		}
	}

	@JSON
	@Override
	public long getNhomNhaCungCapId() {
		return _nhomNhaCungCapId;
	}

	@Override
	public void setNhomNhaCungCapId(long nhomNhaCungCapId) {
		_nhomNhaCungCapId = nhomNhaCungCapId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@JSON
	@Override
	public boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public boolean isHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	@JSON
	@Override
	public int getUuTien() {
		return _uuTien;
	}

	@Override
	public void setUuTien(int uuTien) {
		_uuTien = uuTien;
	}

	@JSON
	@Override
	public String getImage() {
		if (_image == null) {
			return StringPool.BLANK;
		}
		else {
			return _image;
		}
	}

	@Override
	public void setImage(String image) {
		_image = image;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			NhomNhaCungCap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NhomNhaCungCap toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (NhomNhaCungCap)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NhomNhaCungCapImpl nhomNhaCungCapImpl = new NhomNhaCungCapImpl();

		nhomNhaCungCapImpl.setNhomNhaCungCapId(getNhomNhaCungCapId());
		nhomNhaCungCapImpl.setCompanyId(getCompanyId());
		nhomNhaCungCapImpl.setUserId(getUserId());
		nhomNhaCungCapImpl.setUserName(getUserName());
		nhomNhaCungCapImpl.setCreateDate(getCreateDate());
		nhomNhaCungCapImpl.setModifiedDate(getModifiedDate());
		nhomNhaCungCapImpl.setTen(getTen());
		nhomNhaCungCapImpl.setGhiChu(getGhiChu());
		nhomNhaCungCapImpl.setHoatDong(getHoatDong());
		nhomNhaCungCapImpl.setUuTien(getUuTien());
		nhomNhaCungCapImpl.setImage(getImage());

		nhomNhaCungCapImpl.resetOriginalValues();

		return nhomNhaCungCapImpl;
	}

	@Override
	public int compareTo(NhomNhaCungCap nhomNhaCungCap) {
		int value = 0;

		value = getTen().compareTo(nhomNhaCungCap.getTen());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NhomNhaCungCap)) {
			return false;
		}

		NhomNhaCungCap nhomNhaCungCap = (NhomNhaCungCap)obj;

		long primaryKey = nhomNhaCungCap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		NhomNhaCungCapModelImpl nhomNhaCungCapModelImpl = this;

		nhomNhaCungCapModelImpl._originalTen = nhomNhaCungCapModelImpl._ten;

		nhomNhaCungCapModelImpl._originalHoatDong = nhomNhaCungCapModelImpl._hoatDong;

		nhomNhaCungCapModelImpl._setOriginalHoatDong = false;

		nhomNhaCungCapModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<NhomNhaCungCap> toCacheModel() {
		NhomNhaCungCapCacheModel nhomNhaCungCapCacheModel = new NhomNhaCungCapCacheModel();

		nhomNhaCungCapCacheModel.nhomNhaCungCapId = getNhomNhaCungCapId();

		nhomNhaCungCapCacheModel.companyId = getCompanyId();

		nhomNhaCungCapCacheModel.userId = getUserId();

		nhomNhaCungCapCacheModel.userName = getUserName();

		String userName = nhomNhaCungCapCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			nhomNhaCungCapCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			nhomNhaCungCapCacheModel.createDate = createDate.getTime();
		}
		else {
			nhomNhaCungCapCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			nhomNhaCungCapCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			nhomNhaCungCapCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		nhomNhaCungCapCacheModel.ten = getTen();

		String ten = nhomNhaCungCapCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			nhomNhaCungCapCacheModel.ten = null;
		}

		nhomNhaCungCapCacheModel.ghiChu = getGhiChu();

		String ghiChu = nhomNhaCungCapCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			nhomNhaCungCapCacheModel.ghiChu = null;
		}

		nhomNhaCungCapCacheModel.hoatDong = getHoatDong();

		nhomNhaCungCapCacheModel.uuTien = getUuTien();

		nhomNhaCungCapCacheModel.image = getImage();

		String image = nhomNhaCungCapCacheModel.image;

		if ((image != null) && (image.length() == 0)) {
			nhomNhaCungCapCacheModel.image = null;
		}

		return nhomNhaCungCapCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{nhomNhaCungCapId=");
		sb.append(getNhomNhaCungCapId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", hoatDong=");
		sb.append(getHoatDong());
		sb.append(", uuTien=");
		sb.append(getUuTien());
		sb.append(", image=");
		sb.append(getImage());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.nhacungcap.model.NhomNhaCungCap");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>nhomNhaCungCapId</column-name><column-value><![CDATA[");
		sb.append(getNhomNhaCungCapId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoatDong</column-name><column-value><![CDATA[");
		sb.append(getHoatDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uuTien</column-name><column-value><![CDATA[");
		sb.append(getUuTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>image</column-name><column-value><![CDATA[");
		sb.append(getImage());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = NhomNhaCungCap.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			NhomNhaCungCap.class
		};
	private long _nhomNhaCungCapId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private String _ghiChu;
	private boolean _hoatDong;
	private boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private int _uuTien;
	private String _image;
	private long _columnBitmask;
	private NhomNhaCungCap _escapedModel;
}