/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.banhang.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.banhang.model.DonHang;
import com.minimart.portlet.banhang.model.DonHangModel;
import com.minimart.portlet.banhang.model.DonHangSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DonHang service. Represents a row in the &quot;minimart_donhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.banhang.model.DonHangModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DonHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DonHangImpl
 * @see com.minimart.portlet.banhang.model.DonHang
 * @see com.minimart.portlet.banhang.model.DonHangModel
 * @generated
 */
@JSON(strict = true)
public class DonHangModelImpl extends BaseModelImpl<DonHang>
	implements DonHangModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a don hang model instance should use the {@link com.minimart.portlet.banhang.model.DonHang} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_donhang";
	public static final Object[][] TABLE_COLUMNS = {
			{ "donHangId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "cuaHangId", Types.BIGINT },
			{ "khachHangId", Types.BIGINT },
			{ "hoatDong", Types.BOOLEAN },
			{ "tongCong", Types.INTEGER },
			{ "daThanhToan", Types.BOOLEAN },
			{ "phiVanChuyen", Types.INTEGER },
			{ "trangThaiDonHangId", Types.BIGINT },
			{ "ngayThanhToan", Types.TIMESTAMP },
			{ "khachDua", Types.INTEGER },
			{ "traLai", Types.INTEGER },
			{ "thueVAT", Types.INTEGER },
			{ "diemTichLuy", Types.INTEGER },
			{ "thanhToanTienMat", Types.INTEGER },
			{ "thanhToanThe", Types.INTEGER },
			{ "thanhToanChuyenKhoan", Types.INTEGER },
			{ "phieuGiamGiaId", Types.BIGINT },
			{ "truTichLuy", Types.INTEGER },
			{ "inHoaDonLan", Types.INTEGER },
			{ "maDonHang", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_donhang (donHangId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,cuaHangId LONG,khachHangId LONG,hoatDong BOOLEAN,tongCong INTEGER,daThanhToan BOOLEAN,phiVanChuyen INTEGER,trangThaiDonHangId LONG,ngayThanhToan DATE null,khachDua INTEGER,traLai INTEGER,thueVAT INTEGER,diemTichLuy INTEGER,thanhToanTienMat INTEGER,thanhToanThe INTEGER,thanhToanChuyenKhoan INTEGER,phieuGiamGiaId LONG,truTichLuy INTEGER,inHoaDonLan INTEGER,maDonHang VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_donhang";
	public static final String ORDER_BY_JPQL = " ORDER BY donHang.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_donhang.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.banhang.model.DonHang"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.banhang.model.DonHang"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.banhang.model.DonHang"),
			true);
	public static long CUAHANGID_COLUMN_BITMASK = 1L;
	public static long HOATDONG_COLUMN_BITMASK = 2L;
	public static long KHACHHANGID_COLUMN_BITMASK = 4L;
	public static long TRANGTHAIDONHANGID_COLUMN_BITMASK = 8L;
	public static long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DonHang toModel(DonHangSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DonHang model = new DonHangImpl();

		model.setDonHangId(soapModel.getDonHangId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCuaHangId(soapModel.getCuaHangId());
		model.setKhachHangId(soapModel.getKhachHangId());
		model.setHoatDong(soapModel.getHoatDong());
		model.setTongCong(soapModel.getTongCong());
		model.setDaThanhToan(soapModel.getDaThanhToan());
		model.setPhiVanChuyen(soapModel.getPhiVanChuyen());
		model.setTrangThaiDonHangId(soapModel.getTrangThaiDonHangId());
		model.setNgayThanhToan(soapModel.getNgayThanhToan());
		model.setKhachDua(soapModel.getKhachDua());
		model.setTraLai(soapModel.getTraLai());
		model.setThueVAT(soapModel.getThueVAT());
		model.setDiemTichLuy(soapModel.getDiemTichLuy());
		model.setThanhToanTienMat(soapModel.getThanhToanTienMat());
		model.setThanhToanThe(soapModel.getThanhToanThe());
		model.setThanhToanChuyenKhoan(soapModel.getThanhToanChuyenKhoan());
		model.setPhieuGiamGiaId(soapModel.getPhieuGiamGiaId());
		model.setTruTichLuy(soapModel.getTruTichLuy());
		model.setInHoaDonLan(soapModel.getInHoaDonLan());
		model.setMaDonHang(soapModel.getMaDonHang());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DonHang> toModels(DonHangSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DonHang> models = new ArrayList<DonHang>(soapModels.length);

		for (DonHangSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.banhang.model.DonHang"));

	public DonHangModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _donHangId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDonHangId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _donHangId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DonHang.class;
	}

	@Override
	public String getModelClassName() {
		return DonHang.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("donHangId", getDonHangId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("cuaHangId", getCuaHangId());
		attributes.put("khachHangId", getKhachHangId());
		attributes.put("hoatDong", getHoatDong());
		attributes.put("tongCong", getTongCong());
		attributes.put("daThanhToan", getDaThanhToan());
		attributes.put("phiVanChuyen", getPhiVanChuyen());
		attributes.put("trangThaiDonHangId", getTrangThaiDonHangId());
		attributes.put("ngayThanhToan", getNgayThanhToan());
		attributes.put("khachDua", getKhachDua());
		attributes.put("traLai", getTraLai());
		attributes.put("thueVAT", getThueVAT());
		attributes.put("diemTichLuy", getDiemTichLuy());
		attributes.put("thanhToanTienMat", getThanhToanTienMat());
		attributes.put("thanhToanThe", getThanhToanThe());
		attributes.put("thanhToanChuyenKhoan", getThanhToanChuyenKhoan());
		attributes.put("phieuGiamGiaId", getPhieuGiamGiaId());
		attributes.put("truTichLuy", getTruTichLuy());
		attributes.put("inHoaDonLan", getInHoaDonLan());
		attributes.put("maDonHang", getMaDonHang());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long donHangId = (Long)attributes.get("donHangId");

		if (donHangId != null) {
			setDonHangId(donHangId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long cuaHangId = (Long)attributes.get("cuaHangId");

		if (cuaHangId != null) {
			setCuaHangId(cuaHangId);
		}

		Long khachHangId = (Long)attributes.get("khachHangId");

		if (khachHangId != null) {
			setKhachHangId(khachHangId);
		}

		Boolean hoatDong = (Boolean)attributes.get("hoatDong");

		if (hoatDong != null) {
			setHoatDong(hoatDong);
		}

		Integer tongCong = (Integer)attributes.get("tongCong");

		if (tongCong != null) {
			setTongCong(tongCong);
		}

		Boolean daThanhToan = (Boolean)attributes.get("daThanhToan");

		if (daThanhToan != null) {
			setDaThanhToan(daThanhToan);
		}

		Integer phiVanChuyen = (Integer)attributes.get("phiVanChuyen");

		if (phiVanChuyen != null) {
			setPhiVanChuyen(phiVanChuyen);
		}

		Long trangThaiDonHangId = (Long)attributes.get("trangThaiDonHangId");

		if (trangThaiDonHangId != null) {
			setTrangThaiDonHangId(trangThaiDonHangId);
		}

		Date ngayThanhToan = (Date)attributes.get("ngayThanhToan");

		if (ngayThanhToan != null) {
			setNgayThanhToan(ngayThanhToan);
		}

		Integer khachDua = (Integer)attributes.get("khachDua");

		if (khachDua != null) {
			setKhachDua(khachDua);
		}

		Integer traLai = (Integer)attributes.get("traLai");

		if (traLai != null) {
			setTraLai(traLai);
		}

		Integer thueVAT = (Integer)attributes.get("thueVAT");

		if (thueVAT != null) {
			setThueVAT(thueVAT);
		}

		Integer diemTichLuy = (Integer)attributes.get("diemTichLuy");

		if (diemTichLuy != null) {
			setDiemTichLuy(diemTichLuy);
		}

		Integer thanhToanTienMat = (Integer)attributes.get("thanhToanTienMat");

		if (thanhToanTienMat != null) {
			setThanhToanTienMat(thanhToanTienMat);
		}

		Integer thanhToanThe = (Integer)attributes.get("thanhToanThe");

		if (thanhToanThe != null) {
			setThanhToanThe(thanhToanThe);
		}

		Integer thanhToanChuyenKhoan = (Integer)attributes.get(
				"thanhToanChuyenKhoan");

		if (thanhToanChuyenKhoan != null) {
			setThanhToanChuyenKhoan(thanhToanChuyenKhoan);
		}

		Long phieuGiamGiaId = (Long)attributes.get("phieuGiamGiaId");

		if (phieuGiamGiaId != null) {
			setPhieuGiamGiaId(phieuGiamGiaId);
		}

		Integer truTichLuy = (Integer)attributes.get("truTichLuy");

		if (truTichLuy != null) {
			setTruTichLuy(truTichLuy);
		}

		Integer inHoaDonLan = (Integer)attributes.get("inHoaDonLan");

		if (inHoaDonLan != null) {
			setInHoaDonLan(inHoaDonLan);
		}

		String maDonHang = (String)attributes.get("maDonHang");

		if (maDonHang != null) {
			setMaDonHang(maDonHang);
		}
	}

	@JSON
	@Override
	public long getDonHangId() {
		return _donHangId;
	}

	@Override
	public void setDonHangId(long donHangId) {
		_donHangId = donHangId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCuaHangId() {
		return _cuaHangId;
	}

	@Override
	public void setCuaHangId(long cuaHangId) {
		_columnBitmask |= CUAHANGID_COLUMN_BITMASK;

		if (!_setOriginalCuaHangId) {
			_setOriginalCuaHangId = true;

			_originalCuaHangId = _cuaHangId;
		}

		_cuaHangId = cuaHangId;
	}

	public long getOriginalCuaHangId() {
		return _originalCuaHangId;
	}

	@JSON
	@Override
	public long getKhachHangId() {
		return _khachHangId;
	}

	@Override
	public void setKhachHangId(long khachHangId) {
		_columnBitmask |= KHACHHANGID_COLUMN_BITMASK;

		if (!_setOriginalKhachHangId) {
			_setOriginalKhachHangId = true;

			_originalKhachHangId = _khachHangId;
		}

		_khachHangId = khachHangId;
	}

	public long getOriginalKhachHangId() {
		return _originalKhachHangId;
	}

	@JSON
	@Override
	public boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public boolean isHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	@JSON
	@Override
	public int getTongCong() {
		return _tongCong;
	}

	@Override
	public void setTongCong(int tongCong) {
		_tongCong = tongCong;
	}

	@JSON
	@Override
	public boolean getDaThanhToan() {
		return _daThanhToan;
	}

	@Override
	public boolean isDaThanhToan() {
		return _daThanhToan;
	}

	@Override
	public void setDaThanhToan(boolean daThanhToan) {
		_daThanhToan = daThanhToan;
	}

	@JSON
	@Override
	public int getPhiVanChuyen() {
		return _phiVanChuyen;
	}

	@Override
	public void setPhiVanChuyen(int phiVanChuyen) {
		_phiVanChuyen = phiVanChuyen;
	}

	@JSON
	@Override
	public long getTrangThaiDonHangId() {
		return _trangThaiDonHangId;
	}

	@Override
	public void setTrangThaiDonHangId(long trangThaiDonHangId) {
		_columnBitmask |= TRANGTHAIDONHANGID_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiDonHangId) {
			_setOriginalTrangThaiDonHangId = true;

			_originalTrangThaiDonHangId = _trangThaiDonHangId;
		}

		_trangThaiDonHangId = trangThaiDonHangId;
	}

	public long getOriginalTrangThaiDonHangId() {
		return _originalTrangThaiDonHangId;
	}

	@JSON
	@Override
	public Date getNgayThanhToan() {
		return _ngayThanhToan;
	}

	@Override
	public void setNgayThanhToan(Date ngayThanhToan) {
		_ngayThanhToan = ngayThanhToan;
	}

	@JSON
	@Override
	public int getKhachDua() {
		return _khachDua;
	}

	@Override
	public void setKhachDua(int khachDua) {
		_khachDua = khachDua;
	}

	@JSON
	@Override
	public int getTraLai() {
		return _traLai;
	}

	@Override
	public void setTraLai(int traLai) {
		_traLai = traLai;
	}

	@JSON
	@Override
	public int getThueVAT() {
		return _thueVAT;
	}

	@Override
	public void setThueVAT(int thueVAT) {
		_thueVAT = thueVAT;
	}

	@JSON
	@Override
	public int getDiemTichLuy() {
		return _diemTichLuy;
	}

	@Override
	public void setDiemTichLuy(int diemTichLuy) {
		_diemTichLuy = diemTichLuy;
	}

	@JSON
	@Override
	public int getThanhToanTienMat() {
		return _thanhToanTienMat;
	}

	@Override
	public void setThanhToanTienMat(int thanhToanTienMat) {
		_thanhToanTienMat = thanhToanTienMat;
	}

	@JSON
	@Override
	public int getThanhToanThe() {
		return _thanhToanThe;
	}

	@Override
	public void setThanhToanThe(int thanhToanThe) {
		_thanhToanThe = thanhToanThe;
	}

	@JSON
	@Override
	public int getThanhToanChuyenKhoan() {
		return _thanhToanChuyenKhoan;
	}

	@Override
	public void setThanhToanChuyenKhoan(int thanhToanChuyenKhoan) {
		_thanhToanChuyenKhoan = thanhToanChuyenKhoan;
	}

	@JSON
	@Override
	public long getPhieuGiamGiaId() {
		return _phieuGiamGiaId;
	}

	@Override
	public void setPhieuGiamGiaId(long phieuGiamGiaId) {
		_phieuGiamGiaId = phieuGiamGiaId;
	}

	@JSON
	@Override
	public int getTruTichLuy() {
		return _truTichLuy;
	}

	@Override
	public void setTruTichLuy(int truTichLuy) {
		_truTichLuy = truTichLuy;
	}

	@JSON
	@Override
	public int getInHoaDonLan() {
		return _inHoaDonLan;
	}

	@Override
	public void setInHoaDonLan(int inHoaDonLan) {
		_inHoaDonLan = inHoaDonLan;
	}

	@JSON
	@Override
	public String getMaDonHang() {
		if (_maDonHang == null) {
			return StringPool.BLANK;
		}
		else {
			return _maDonHang;
		}
	}

	@Override
	public void setMaDonHang(String maDonHang) {
		_maDonHang = maDonHang;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DonHang.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DonHang toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DonHang)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DonHangImpl donHangImpl = new DonHangImpl();

		donHangImpl.setDonHangId(getDonHangId());
		donHangImpl.setCompanyId(getCompanyId());
		donHangImpl.setUserId(getUserId());
		donHangImpl.setUserName(getUserName());
		donHangImpl.setCreateDate(getCreateDate());
		donHangImpl.setModifiedDate(getModifiedDate());
		donHangImpl.setCuaHangId(getCuaHangId());
		donHangImpl.setKhachHangId(getKhachHangId());
		donHangImpl.setHoatDong(getHoatDong());
		donHangImpl.setTongCong(getTongCong());
		donHangImpl.setDaThanhToan(getDaThanhToan());
		donHangImpl.setPhiVanChuyen(getPhiVanChuyen());
		donHangImpl.setTrangThaiDonHangId(getTrangThaiDonHangId());
		donHangImpl.setNgayThanhToan(getNgayThanhToan());
		donHangImpl.setKhachDua(getKhachDua());
		donHangImpl.setTraLai(getTraLai());
		donHangImpl.setThueVAT(getThueVAT());
		donHangImpl.setDiemTichLuy(getDiemTichLuy());
		donHangImpl.setThanhToanTienMat(getThanhToanTienMat());
		donHangImpl.setThanhToanThe(getThanhToanThe());
		donHangImpl.setThanhToanChuyenKhoan(getThanhToanChuyenKhoan());
		donHangImpl.setPhieuGiamGiaId(getPhieuGiamGiaId());
		donHangImpl.setTruTichLuy(getTruTichLuy());
		donHangImpl.setInHoaDonLan(getInHoaDonLan());
		donHangImpl.setMaDonHang(getMaDonHang());

		donHangImpl.resetOriginalValues();

		return donHangImpl;
	}

	@Override
	public int compareTo(DonHang donHang) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), donHang.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DonHang)) {
			return false;
		}

		DonHang donHang = (DonHang)obj;

		long primaryKey = donHang.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DonHangModelImpl donHangModelImpl = this;

		donHangModelImpl._originalCuaHangId = donHangModelImpl._cuaHangId;

		donHangModelImpl._setOriginalCuaHangId = false;

		donHangModelImpl._originalKhachHangId = donHangModelImpl._khachHangId;

		donHangModelImpl._setOriginalKhachHangId = false;

		donHangModelImpl._originalHoatDong = donHangModelImpl._hoatDong;

		donHangModelImpl._setOriginalHoatDong = false;

		donHangModelImpl._originalTrangThaiDonHangId = donHangModelImpl._trangThaiDonHangId;

		donHangModelImpl._setOriginalTrangThaiDonHangId = false;

		donHangModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DonHang> toCacheModel() {
		DonHangCacheModel donHangCacheModel = new DonHangCacheModel();

		donHangCacheModel.donHangId = getDonHangId();

		donHangCacheModel.companyId = getCompanyId();

		donHangCacheModel.userId = getUserId();

		donHangCacheModel.userName = getUserName();

		String userName = donHangCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			donHangCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			donHangCacheModel.createDate = createDate.getTime();
		}
		else {
			donHangCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			donHangCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			donHangCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		donHangCacheModel.cuaHangId = getCuaHangId();

		donHangCacheModel.khachHangId = getKhachHangId();

		donHangCacheModel.hoatDong = getHoatDong();

		donHangCacheModel.tongCong = getTongCong();

		donHangCacheModel.daThanhToan = getDaThanhToan();

		donHangCacheModel.phiVanChuyen = getPhiVanChuyen();

		donHangCacheModel.trangThaiDonHangId = getTrangThaiDonHangId();

		Date ngayThanhToan = getNgayThanhToan();

		if (ngayThanhToan != null) {
			donHangCacheModel.ngayThanhToan = ngayThanhToan.getTime();
		}
		else {
			donHangCacheModel.ngayThanhToan = Long.MIN_VALUE;
		}

		donHangCacheModel.khachDua = getKhachDua();

		donHangCacheModel.traLai = getTraLai();

		donHangCacheModel.thueVAT = getThueVAT();

		donHangCacheModel.diemTichLuy = getDiemTichLuy();

		donHangCacheModel.thanhToanTienMat = getThanhToanTienMat();

		donHangCacheModel.thanhToanThe = getThanhToanThe();

		donHangCacheModel.thanhToanChuyenKhoan = getThanhToanChuyenKhoan();

		donHangCacheModel.phieuGiamGiaId = getPhieuGiamGiaId();

		donHangCacheModel.truTichLuy = getTruTichLuy();

		donHangCacheModel.inHoaDonLan = getInHoaDonLan();

		donHangCacheModel.maDonHang = getMaDonHang();

		String maDonHang = donHangCacheModel.maDonHang;

		if ((maDonHang != null) && (maDonHang.length() == 0)) {
			donHangCacheModel.maDonHang = null;
		}

		return donHangCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(51);

		sb.append("{donHangId=");
		sb.append(getDonHangId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", cuaHangId=");
		sb.append(getCuaHangId());
		sb.append(", khachHangId=");
		sb.append(getKhachHangId());
		sb.append(", hoatDong=");
		sb.append(getHoatDong());
		sb.append(", tongCong=");
		sb.append(getTongCong());
		sb.append(", daThanhToan=");
		sb.append(getDaThanhToan());
		sb.append(", phiVanChuyen=");
		sb.append(getPhiVanChuyen());
		sb.append(", trangThaiDonHangId=");
		sb.append(getTrangThaiDonHangId());
		sb.append(", ngayThanhToan=");
		sb.append(getNgayThanhToan());
		sb.append(", khachDua=");
		sb.append(getKhachDua());
		sb.append(", traLai=");
		sb.append(getTraLai());
		sb.append(", thueVAT=");
		sb.append(getThueVAT());
		sb.append(", diemTichLuy=");
		sb.append(getDiemTichLuy());
		sb.append(", thanhToanTienMat=");
		sb.append(getThanhToanTienMat());
		sb.append(", thanhToanThe=");
		sb.append(getThanhToanThe());
		sb.append(", thanhToanChuyenKhoan=");
		sb.append(getThanhToanChuyenKhoan());
		sb.append(", phieuGiamGiaId=");
		sb.append(getPhieuGiamGiaId());
		sb.append(", truTichLuy=");
		sb.append(getTruTichLuy());
		sb.append(", inHoaDonLan=");
		sb.append(getInHoaDonLan());
		sb.append(", maDonHang=");
		sb.append(getMaDonHang());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(79);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.banhang.model.DonHang");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>donHangId</column-name><column-value><![CDATA[");
		sb.append(getDonHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuaHangId</column-name><column-value><![CDATA[");
		sb.append(getCuaHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>khachHangId</column-name><column-value><![CDATA[");
		sb.append(getKhachHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoatDong</column-name><column-value><![CDATA[");
		sb.append(getHoatDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongCong</column-name><column-value><![CDATA[");
		sb.append(getTongCong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daThanhToan</column-name><column-value><![CDATA[");
		sb.append(getDaThanhToan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phiVanChuyen</column-name><column-value><![CDATA[");
		sb.append(getPhiVanChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiDonHangId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiDonHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayThanhToan</column-name><column-value><![CDATA[");
		sb.append(getNgayThanhToan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>khachDua</column-name><column-value><![CDATA[");
		sb.append(getKhachDua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>traLai</column-name><column-value><![CDATA[");
		sb.append(getTraLai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thueVAT</column-name><column-value><![CDATA[");
		sb.append(getThueVAT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diemTichLuy</column-name><column-value><![CDATA[");
		sb.append(getDiemTichLuy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhToanTienMat</column-name><column-value><![CDATA[");
		sb.append(getThanhToanTienMat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhToanThe</column-name><column-value><![CDATA[");
		sb.append(getThanhToanThe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhToanChuyenKhoan</column-name><column-value><![CDATA[");
		sb.append(getThanhToanChuyenKhoan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phieuGiamGiaId</column-name><column-value><![CDATA[");
		sb.append(getPhieuGiamGiaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truTichLuy</column-name><column-value><![CDATA[");
		sb.append(getTruTichLuy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inHoaDonLan</column-name><column-value><![CDATA[");
		sb.append(getInHoaDonLan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maDonHang</column-name><column-value><![CDATA[");
		sb.append(getMaDonHang());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DonHang.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DonHang.class
		};
	private long _donHangId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _cuaHangId;
	private long _originalCuaHangId;
	private boolean _setOriginalCuaHangId;
	private long _khachHangId;
	private long _originalKhachHangId;
	private boolean _setOriginalKhachHangId;
	private boolean _hoatDong;
	private boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private int _tongCong;
	private boolean _daThanhToan;
	private int _phiVanChuyen;
	private long _trangThaiDonHangId;
	private long _originalTrangThaiDonHangId;
	private boolean _setOriginalTrangThaiDonHangId;
	private Date _ngayThanhToan;
	private int _khachDua;
	private int _traLai;
	private int _thueVAT;
	private int _diemTichLuy;
	private int _thanhToanTienMat;
	private int _thanhToanThe;
	private int _thanhToanChuyenKhoan;
	private long _phieuGiamGiaId;
	private int _truTichLuy;
	private int _inHoaDonLan;
	private String _maDonHang;
	private long _columnBitmask;
	private DonHang _escapedModel;
}