/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.danhmucchung.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PhuongXa service. Represents a row in the &quot;minimart_phuongxa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.danhmucchung.model.impl.PhuongXaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.danhmucchung.model.impl.PhuongXaImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see PhuongXa
 * @see com.minimart.portlet.danhmucchung.model.impl.PhuongXaImpl
 * @see com.minimart.portlet.danhmucchung.model.impl.PhuongXaModelImpl
 * @generated
 */
public interface PhuongXaModel extends AuditedModel, BaseModel<PhuongXa> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phuong xa model instance should use the {@link PhuongXa} interface instead.
	 */

	/**
	 * Returns the primary key of this phuong xa.
	 *
	 * @return the primary key of this phuong xa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phuong xa.
	 *
	 * @param primaryKey the primary key of this phuong xa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the phuong xa ID of this phuong xa.
	 *
	 * @return the phuong xa ID of this phuong xa
	 */
	public long getPhuongXaId();

	/**
	 * Sets the phuong xa ID of this phuong xa.
	 *
	 * @param phuongXaId the phuong xa ID of this phuong xa
	 */
	public void setPhuongXaId(long phuongXaId);

	/**
	 * Returns the company ID of this phuong xa.
	 *
	 * @return the company ID of this phuong xa
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phuong xa.
	 *
	 * @param companyId the company ID of this phuong xa
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this phuong xa.
	 *
	 * @return the user ID of this phuong xa
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this phuong xa.
	 *
	 * @param userId the user ID of this phuong xa
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phuong xa.
	 *
	 * @return the user uuid of this phuong xa
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this phuong xa.
	 *
	 * @param userUuid the user uuid of this phuong xa
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this phuong xa.
	 *
	 * @return the user name of this phuong xa
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this phuong xa.
	 *
	 * @param userName the user name of this phuong xa
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this phuong xa.
	 *
	 * @return the create date of this phuong xa
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this phuong xa.
	 *
	 * @param createDate the create date of this phuong xa
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this phuong xa.
	 *
	 * @return the modified date of this phuong xa
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this phuong xa.
	 *
	 * @param modifiedDate the modified date of this phuong xa
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this phuong xa.
	 *
	 * @return the ten of this phuong xa
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this phuong xa.
	 *
	 * @param ten the ten of this phuong xa
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this phuong xa.
	 *
	 * @return the ma of this phuong xa
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this phuong xa.
	 *
	 * @param ma the ma of this phuong xa
	 */
	public void setMa(String ma);

	/**
	 * Returns the trang thai of this phuong xa.
	 *
	 * @return the trang thai of this phuong xa
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this phuong xa is trang thai.
	 *
	 * @return <code>true</code> if this phuong xa is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this phuong xa is trang thai.
	 *
	 * @param trangThai the trang thai of this phuong xa
	 */
	public void setTrangThai(boolean trangThai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.danhmucchung.model.PhuongXa phuongXa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.danhmucchung.model.PhuongXa> toCacheModel();

	@Override
	public com.minimart.portlet.danhmucchung.model.PhuongXa toEscapedModel();

	@Override
	public com.minimart.portlet.danhmucchung.model.PhuongXa toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}