/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.mathang.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.mathang.model.NhomMatHang;
import com.minimart.portlet.mathang.model.NhomMatHangModel;
import com.minimart.portlet.mathang.model.NhomMatHangSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the NhomMatHang service. Represents a row in the &quot;minimart_nhommathang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.mathang.model.NhomMatHangModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NhomMatHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see NhomMatHangImpl
 * @see com.minimart.portlet.mathang.model.NhomMatHang
 * @see com.minimart.portlet.mathang.model.NhomMatHangModel
 * @generated
 */
@JSON(strict = true)
public class NhomMatHangModelImpl extends BaseModelImpl<NhomMatHang>
	implements NhomMatHangModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nhom mat hang model instance should use the {@link com.minimart.portlet.mathang.model.NhomMatHang} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_nhommathang";
	public static final Object[][] TABLE_COLUMNS = {
			{ "nhomMatHangId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "code_", Types.VARCHAR },
			{ "status", Types.INTEGER },
			{ "note", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_nhommathang (nhomMatHangId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,code_ VARCHAR(75) null,status INTEGER,note VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_nhommathang";
	public static final String ORDER_BY_JPQL = " ORDER BY nhomMatHang.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_nhommathang.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.mathang.model.NhomMatHang"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.mathang.model.NhomMatHang"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.mathang.model.NhomMatHang"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NhomMatHang toModel(NhomMatHangSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NhomMatHang model = new NhomMatHangImpl();

		model.setNhomMatHangId(soapModel.getNhomMatHangId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setStatus(soapModel.getStatus());
		model.setNote(soapModel.getNote());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NhomMatHang> toModels(NhomMatHangSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NhomMatHang> models = new ArrayList<NhomMatHang>(soapModels.length);

		for (NhomMatHangSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.mathang.model.NhomMatHang"));

	public NhomMatHangModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _nhomMatHangId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNhomMatHangId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _nhomMatHangId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NhomMatHang.class;
	}

	@Override
	public String getModelClassName() {
		return NhomMatHang.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("nhomMatHangId", getNhomMatHangId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("code", getCode());
		attributes.put("status", getStatus());
		attributes.put("note", getNote());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long nhomMatHangId = (Long)attributes.get("nhomMatHangId");

		if (nhomMatHangId != null) {
			setNhomMatHangId(nhomMatHangId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String note = (String)attributes.get("note");

		if (note != null) {
			setNote(note);
		}
	}

	@JSON
	@Override
	public long getNhomMatHangId() {
		return _nhomMatHangId;
	}

	@Override
	public void setNhomMatHangId(long nhomMatHangId) {
		_nhomMatHangId = nhomMatHangId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_code = code;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		_note = note;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			NhomMatHang.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NhomMatHang toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (NhomMatHang)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NhomMatHangImpl nhomMatHangImpl = new NhomMatHangImpl();

		nhomMatHangImpl.setNhomMatHangId(getNhomMatHangId());
		nhomMatHangImpl.setGroupId(getGroupId());
		nhomMatHangImpl.setCompanyId(getCompanyId());
		nhomMatHangImpl.setUserId(getUserId());
		nhomMatHangImpl.setUserName(getUserName());
		nhomMatHangImpl.setCreateDate(getCreateDate());
		nhomMatHangImpl.setModifiedDate(getModifiedDate());
		nhomMatHangImpl.setName(getName());
		nhomMatHangImpl.setCode(getCode());
		nhomMatHangImpl.setStatus(getStatus());
		nhomMatHangImpl.setNote(getNote());

		nhomMatHangImpl.resetOriginalValues();

		return nhomMatHangImpl;
	}

	@Override
	public int compareTo(NhomMatHang nhomMatHang) {
		int value = 0;

		value = getName().compareTo(nhomMatHang.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NhomMatHang)) {
			return false;
		}

		NhomMatHang nhomMatHang = (NhomMatHang)obj;

		long primaryKey = nhomMatHang.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		NhomMatHangModelImpl nhomMatHangModelImpl = this;

		nhomMatHangModelImpl._originalName = nhomMatHangModelImpl._name;

		nhomMatHangModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<NhomMatHang> toCacheModel() {
		NhomMatHangCacheModel nhomMatHangCacheModel = new NhomMatHangCacheModel();

		nhomMatHangCacheModel.nhomMatHangId = getNhomMatHangId();

		nhomMatHangCacheModel.groupId = getGroupId();

		nhomMatHangCacheModel.companyId = getCompanyId();

		nhomMatHangCacheModel.userId = getUserId();

		nhomMatHangCacheModel.userName = getUserName();

		String userName = nhomMatHangCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			nhomMatHangCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			nhomMatHangCacheModel.createDate = createDate.getTime();
		}
		else {
			nhomMatHangCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			nhomMatHangCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			nhomMatHangCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		nhomMatHangCacheModel.name = getName();

		String name = nhomMatHangCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			nhomMatHangCacheModel.name = null;
		}

		nhomMatHangCacheModel.code = getCode();

		String code = nhomMatHangCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			nhomMatHangCacheModel.code = null;
		}

		nhomMatHangCacheModel.status = getStatus();

		nhomMatHangCacheModel.note = getNote();

		String note = nhomMatHangCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			nhomMatHangCacheModel.note = null;
		}

		return nhomMatHangCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{nhomMatHangId=");
		sb.append(getNhomMatHangId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", code=");
		sb.append(getCode());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", note=");
		sb.append(getNote());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.mathang.model.NhomMatHang");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>nhomMatHangId</column-name><column-value><![CDATA[");
		sb.append(getNhomMatHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = NhomMatHang.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			NhomMatHang.class
		};
	private long _nhomMatHangId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _originalName;
	private String _code;
	private int _status;
	private String _note;
	private long _columnBitmask;
	private NhomMatHang _escapedModel;
}