/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.nhanvien.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.minimart.portlet.nhanvien.model.NhanVien;
import com.minimart.portlet.nhanvien.service.NhanVienLocalService;
import com.minimart.portlet.nhanvien.service.persistence.NhanVienPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the nhan vien local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.minimart.portlet.nhanvien.service.impl.NhanVienLocalServiceImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see com.minimart.portlet.nhanvien.service.impl.NhanVienLocalServiceImpl
 * @see com.minimart.portlet.nhanvien.service.NhanVienLocalServiceUtil
 * @generated
 */
public abstract class NhanVienLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements NhanVienLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.minimart.portlet.nhanvien.service.NhanVienLocalServiceUtil} to access the nhan vien local service.
	 */

	/**
	 * Adds the nhan vien to the database. Also notifies the appropriate model listeners.
	 *
	 * @param nhanVien the nhan vien
	 * @return the nhan vien that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NhanVien addNhanVien(NhanVien nhanVien) throws SystemException {
		nhanVien.setNew(true);

		return nhanVienPersistence.update(nhanVien);
	}

	/**
	 * Creates a new nhan vien with the primary key. Does not add the nhan vien to the database.
	 *
	 * @param nhanVienId the primary key for the new nhan vien
	 * @return the new nhan vien
	 */
	@Override
	public NhanVien createNhanVien(long nhanVienId) {
		return nhanVienPersistence.create(nhanVienId);
	}

	/**
	 * Deletes the nhan vien with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param nhanVienId the primary key of the nhan vien
	 * @return the nhan vien that was removed
	 * @throws PortalException if a nhan vien with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NhanVien deleteNhanVien(long nhanVienId)
		throws PortalException, SystemException {
		return nhanVienPersistence.remove(nhanVienId);
	}

	/**
	 * Deletes the nhan vien from the database. Also notifies the appropriate model listeners.
	 *
	 * @param nhanVien the nhan vien
	 * @return the nhan vien that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NhanVien deleteNhanVien(NhanVien nhanVien) throws SystemException {
		return nhanVienPersistence.remove(nhanVien);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(NhanVien.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return nhanVienPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.minimart.portlet.nhanvien.model.impl.NhanVienModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return nhanVienPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.minimart.portlet.nhanvien.model.impl.NhanVienModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return nhanVienPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return nhanVienPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return nhanVienPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public NhanVien fetchNhanVien(long nhanVienId) throws SystemException {
		return nhanVienPersistence.fetchByPrimaryKey(nhanVienId);
	}

	/**
	 * Returns the nhan vien with the matching UUID and company.
	 *
	 * @param uuid the nhan vien's UUID
	 * @param  companyId the primary key of the company
	 * @return the matching nhan vien, or <code>null</code> if a matching nhan vien could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public NhanVien fetchNhanVienByUuidAndCompanyId(String uuid, long companyId)
		throws SystemException {
		return nhanVienPersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the nhan vien with the primary key.
	 *
	 * @param nhanVienId the primary key of the nhan vien
	 * @return the nhan vien
	 * @throws PortalException if a nhan vien with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public NhanVien getNhanVien(long nhanVienId)
		throws PortalException, SystemException {
		return nhanVienPersistence.findByPrimaryKey(nhanVienId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return nhanVienPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the nhan vien with the matching UUID and company.
	 *
	 * @param uuid the nhan vien's UUID
	 * @param  companyId the primary key of the company
	 * @return the matching nhan vien
	 * @throws PortalException if a matching nhan vien could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public NhanVien getNhanVienByUuidAndCompanyId(String uuid, long companyId)
		throws PortalException, SystemException {
		return nhanVienPersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns a range of all the nhan viens.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.minimart.portlet.nhanvien.model.impl.NhanVienModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of nhan viens
	 * @param end the upper bound of the range of nhan viens (not inclusive)
	 * @return the range of nhan viens
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<NhanVien> getNhanViens(int start, int end)
		throws SystemException {
		return nhanVienPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of nhan viens.
	 *
	 * @return the number of nhan viens
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getNhanViensCount() throws SystemException {
		return nhanVienPersistence.countAll();
	}

	/**
	 * Updates the nhan vien in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param nhanVien the nhan vien
	 * @return the nhan vien that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NhanVien updateNhanVien(NhanVien nhanVien) throws SystemException {
		return nhanVienPersistence.update(nhanVien);
	}

	/**
	 * Returns the nhan vien local service.
	 *
	 * @return the nhan vien local service
	 */
	public com.minimart.portlet.nhanvien.service.NhanVienLocalService getNhanVienLocalService() {
		return nhanVienLocalService;
	}

	/**
	 * Sets the nhan vien local service.
	 *
	 * @param nhanVienLocalService the nhan vien local service
	 */
	public void setNhanVienLocalService(
		com.minimart.portlet.nhanvien.service.NhanVienLocalService nhanVienLocalService) {
		this.nhanVienLocalService = nhanVienLocalService;
	}

	/**
	 * Returns the nhan vien remote service.
	 *
	 * @return the nhan vien remote service
	 */
	public com.minimart.portlet.nhanvien.service.NhanVienService getNhanVienService() {
		return nhanVienService;
	}

	/**
	 * Sets the nhan vien remote service.
	 *
	 * @param nhanVienService the nhan vien remote service
	 */
	public void setNhanVienService(
		com.minimart.portlet.nhanvien.service.NhanVienService nhanVienService) {
		this.nhanVienService = nhanVienService;
	}

	/**
	 * Returns the nhan vien persistence.
	 *
	 * @return the nhan vien persistence
	 */
	public NhanVienPersistence getNhanVienPersistence() {
		return nhanVienPersistence;
	}

	/**
	 * Sets the nhan vien persistence.
	 *
	 * @param nhanVienPersistence the nhan vien persistence
	 */
	public void setNhanVienPersistence(NhanVienPersistence nhanVienPersistence) {
		this.nhanVienPersistence = nhanVienPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.minimart.portlet.nhanvien.model.NhanVien",
			nhanVienLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.minimart.portlet.nhanvien.model.NhanVien");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return NhanVien.class;
	}

	protected String getModelClassName() {
		return NhanVien.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = nhanVienPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.minimart.portlet.nhanvien.service.NhanVienLocalService.class)
	protected com.minimart.portlet.nhanvien.service.NhanVienLocalService nhanVienLocalService;
	@BeanReference(type = com.minimart.portlet.nhanvien.service.NhanVienService.class)
	protected com.minimart.portlet.nhanvien.service.NhanVienService nhanVienService;
	@BeanReference(type = NhanVienPersistence.class)
	protected NhanVienPersistence nhanVienPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private NhanVienLocalServiceClpInvoker _clpInvoker = new NhanVienLocalServiceClpInvoker();
}