/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.nhacungcap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NhomNhaCungCap service. Represents a row in the &quot;minimart_nhomnhacungcap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.nhacungcap.model.impl.NhomNhaCungCapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.nhacungcap.model.impl.NhomNhaCungCapImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see NhomNhaCungCap
 * @see com.minimart.portlet.nhacungcap.model.impl.NhomNhaCungCapImpl
 * @see com.minimart.portlet.nhacungcap.model.impl.NhomNhaCungCapModelImpl
 * @generated
 */
public interface NhomNhaCungCapModel extends AuditedModel,
	BaseModel<NhomNhaCungCap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhom nha cung cap model instance should use the {@link NhomNhaCungCap} interface instead.
	 */

	/**
	 * Returns the primary key of this nhom nha cung cap.
	 *
	 * @return the primary key of this nhom nha cung cap
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nhom nha cung cap.
	 *
	 * @param primaryKey the primary key of this nhom nha cung cap
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the nhom nha cung cap ID of this nhom nha cung cap.
	 *
	 * @return the nhom nha cung cap ID of this nhom nha cung cap
	 */
	public long getNhomNhaCungCapId();

	/**
	 * Sets the nhom nha cung cap ID of this nhom nha cung cap.
	 *
	 * @param nhomNhaCungCapId the nhom nha cung cap ID of this nhom nha cung cap
	 */
	public void setNhomNhaCungCapId(long nhomNhaCungCapId);

	/**
	 * Returns the company ID of this nhom nha cung cap.
	 *
	 * @return the company ID of this nhom nha cung cap
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this nhom nha cung cap.
	 *
	 * @param companyId the company ID of this nhom nha cung cap
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this nhom nha cung cap.
	 *
	 * @return the user ID of this nhom nha cung cap
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this nhom nha cung cap.
	 *
	 * @param userId the user ID of this nhom nha cung cap
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this nhom nha cung cap.
	 *
	 * @return the user uuid of this nhom nha cung cap
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this nhom nha cung cap.
	 *
	 * @param userUuid the user uuid of this nhom nha cung cap
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this nhom nha cung cap.
	 *
	 * @return the user name of this nhom nha cung cap
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this nhom nha cung cap.
	 *
	 * @param userName the user name of this nhom nha cung cap
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this nhom nha cung cap.
	 *
	 * @return the create date of this nhom nha cung cap
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this nhom nha cung cap.
	 *
	 * @param createDate the create date of this nhom nha cung cap
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this nhom nha cung cap.
	 *
	 * @return the modified date of this nhom nha cung cap
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this nhom nha cung cap.
	 *
	 * @param modifiedDate the modified date of this nhom nha cung cap
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this nhom nha cung cap.
	 *
	 * @return the ten of this nhom nha cung cap
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this nhom nha cung cap.
	 *
	 * @param ten the ten of this nhom nha cung cap
	 */
	public void setTen(String ten);

	/**
	 * Returns the ghi chu of this nhom nha cung cap.
	 *
	 * @return the ghi chu of this nhom nha cung cap
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this nhom nha cung cap.
	 *
	 * @param ghiChu the ghi chu of this nhom nha cung cap
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the hoat dong of this nhom nha cung cap.
	 *
	 * @return the hoat dong of this nhom nha cung cap
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this nhom nha cung cap is hoat dong.
	 *
	 * @return <code>true</code> if this nhom nha cung cap is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this nhom nha cung cap is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this nhom nha cung cap
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the uu tien of this nhom nha cung cap.
	 *
	 * @return the uu tien of this nhom nha cung cap
	 */
	public int getUuTien();

	/**
	 * Sets the uu tien of this nhom nha cung cap.
	 *
	 * @param uuTien the uu tien of this nhom nha cung cap
	 */
	public void setUuTien(int uuTien);

	/**
	 * Returns the image of this nhom nha cung cap.
	 *
	 * @return the image of this nhom nha cung cap
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this nhom nha cung cap.
	 *
	 * @param image the image of this nhom nha cung cap
	 */
	public void setImage(String image);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.nhacungcap.model.NhomNhaCungCap nhomNhaCungCap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.nhacungcap.model.NhomNhaCungCap> toCacheModel();

	@Override
	public com.minimart.portlet.nhacungcap.model.NhomNhaCungCap toEscapedModel();

	@Override
	public com.minimart.portlet.nhacungcap.model.NhomNhaCungCap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}