/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.ketoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BangLuong service. Represents a row in the &quot;minimart_bangluong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.ketoan.model.impl.BangLuongModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.ketoan.model.impl.BangLuongImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see BangLuong
 * @see com.minimart.portlet.ketoan.model.impl.BangLuongImpl
 * @see com.minimart.portlet.ketoan.model.impl.BangLuongModelImpl
 * @generated
 */
public interface BangLuongModel extends AuditedModel, BaseModel<BangLuong> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bang luong model instance should use the {@link BangLuong} interface instead.
	 */

	/**
	 * Returns the primary key of this bang luong.
	 *
	 * @return the primary key of this bang luong
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bang luong.
	 *
	 * @param primaryKey the primary key of this bang luong
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ban luong ID of this bang luong.
	 *
	 * @return the ban luong ID of this bang luong
	 */
	public long getBanLuongId();

	/**
	 * Sets the ban luong ID of this bang luong.
	 *
	 * @param banLuongId the ban luong ID of this bang luong
	 */
	public void setBanLuongId(long banLuongId);

	/**
	 * Returns the company ID of this bang luong.
	 *
	 * @return the company ID of this bang luong
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bang luong.
	 *
	 * @param companyId the company ID of this bang luong
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bang luong.
	 *
	 * @return the user ID of this bang luong
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bang luong.
	 *
	 * @param userId the user ID of this bang luong
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bang luong.
	 *
	 * @return the user uuid of this bang luong
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this bang luong.
	 *
	 * @param userUuid the user uuid of this bang luong
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bang luong.
	 *
	 * @return the user name of this bang luong
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bang luong.
	 *
	 * @param userName the user name of this bang luong
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bang luong.
	 *
	 * @return the create date of this bang luong
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bang luong.
	 *
	 * @param createDate the create date of this bang luong
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bang luong.
	 *
	 * @return the modified date of this bang luong
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bang luong.
	 *
	 * @param modifiedDate the modified date of this bang luong
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this bang luong.
	 *
	 * @return the ten of this bang luong
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this bang luong.
	 *
	 * @param ten the ten of this bang luong
	 */
	public void setTen(String ten);

	/**
	 * Returns the trang thai of this bang luong.
	 *
	 * @return the trang thai of this bang luong
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this bang luong is trang thai.
	 *
	 * @return <code>true</code> if this bang luong is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this bang luong is trang thai.
	 *
	 * @param trangThai the trang thai of this bang luong
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the thang of this bang luong.
	 *
	 * @return the thang of this bang luong
	 */
	public int getThang();

	/**
	 * Sets the thang of this bang luong.
	 *
	 * @param thang the thang of this bang luong
	 */
	public void setThang(int thang);

	/**
	 * Returns the nam of this bang luong.
	 *
	 * @return the nam of this bang luong
	 */
	public int getNam();

	/**
	 * Sets the nam of this bang luong.
	 *
	 * @param nam the nam of this bang luong
	 */
	public void setNam(int nam);

	/**
	 * Returns the ngay of this bang luong.
	 *
	 * @return the ngay of this bang luong
	 */
	public Date getNgay();

	/**
	 * Sets the ngay of this bang luong.
	 *
	 * @param ngay the ngay of this bang luong
	 */
	public void setNgay(Date ngay);

	/**
	 * Returns the chi tiet of this bang luong.
	 *
	 * @return the chi tiet of this bang luong
	 */
	@AutoEscape
	public String getChiTiet();

	/**
	 * Sets the chi tiet of this bang luong.
	 *
	 * @param chiTiet the chi tiet of this bang luong
	 */
	public void setChiTiet(String chiTiet);

	/**
	 * Returns the ghi chu of this bang luong.
	 *
	 * @return the ghi chu of this bang luong
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this bang luong.
	 *
	 * @param ghiChu the ghi chu of this bang luong
	 */
	public void setGhiChu(String ghiChu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.ketoan.model.BangLuong bangLuong);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.ketoan.model.BangLuong> toCacheModel();

	@Override
	public com.minimart.portlet.ketoan.model.BangLuong toEscapedModel();

	@Override
	public com.minimart.portlet.ketoan.model.BangLuong toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}