/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.ketoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThuChi service. Represents a row in the &quot;minimart_thuchi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.ketoan.model.impl.ThuChiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.ketoan.model.impl.ThuChiImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see ThuChi
 * @see com.minimart.portlet.ketoan.model.impl.ThuChiImpl
 * @see com.minimart.portlet.ketoan.model.impl.ThuChiModelImpl
 * @generated
 */
public interface ThuChiModel extends AuditedModel, BaseModel<ThuChi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thu chi model instance should use the {@link ThuChi} interface instead.
	 */

	/**
	 * Returns the primary key of this thu chi.
	 *
	 * @return the primary key of this thu chi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this thu chi.
	 *
	 * @param primaryKey the primary key of this thu chi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the thu chi ID of this thu chi.
	 *
	 * @return the thu chi ID of this thu chi
	 */
	public long getThuChiId();

	/**
	 * Sets the thu chi ID of this thu chi.
	 *
	 * @param thuChiId the thu chi ID of this thu chi
	 */
	public void setThuChiId(long thuChiId);

	/**
	 * Returns the company ID of this thu chi.
	 *
	 * @return the company ID of this thu chi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this thu chi.
	 *
	 * @param companyId the company ID of this thu chi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this thu chi.
	 *
	 * @return the user ID of this thu chi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this thu chi.
	 *
	 * @param userId the user ID of this thu chi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this thu chi.
	 *
	 * @return the user uuid of this thu chi
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this thu chi.
	 *
	 * @param userUuid the user uuid of this thu chi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this thu chi.
	 *
	 * @return the user name of this thu chi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this thu chi.
	 *
	 * @param userName the user name of this thu chi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this thu chi.
	 *
	 * @return the create date of this thu chi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this thu chi.
	 *
	 * @param createDate the create date of this thu chi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this thu chi.
	 *
	 * @return the modified date of this thu chi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this thu chi.
	 *
	 * @param modifiedDate the modified date of this thu chi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this thu chi.
	 *
	 * @return the ten of this thu chi
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this thu chi.
	 *
	 * @param ten the ten of this thu chi
	 */
	public void setTen(String ten);

	/**
	 * Returns the ten doi tuong of this thu chi.
	 *
	 * @return the ten doi tuong of this thu chi
	 */
	@AutoEscape
	public String getTenDoiTuong();

	/**
	 * Sets the ten doi tuong of this thu chi.
	 *
	 * @param tenDoiTuong the ten doi tuong of this thu chi
	 */
	public void setTenDoiTuong(String tenDoiTuong);

	/**
	 * Returns the dia chi ID of this thu chi.
	 *
	 * @return the dia chi ID of this thu chi
	 */
	public long getDiaChiId();

	/**
	 * Sets the dia chi ID of this thu chi.
	 *
	 * @param diaChiId the dia chi ID of this thu chi
	 */
	public void setDiaChiId(long diaChiId);

	/**
	 * Returns the loai of this thu chi.
	 *
	 * @return the loai of this thu chi
	 */
	public int getLoai();

	/**
	 * Sets the loai of this thu chi.
	 *
	 * @param loai the loai of this thu chi
	 */
	public void setLoai(int loai);

	/**
	 * Returns the loai doi tuong of this thu chi.
	 *
	 * @return the loai doi tuong of this thu chi
	 */
	public int getLoaiDoiTuong();

	/**
	 * Sets the loai doi tuong of this thu chi.
	 *
	 * @param loaiDoiTuong the loai doi tuong of this thu chi
	 */
	public void setLoaiDoiTuong(int loaiDoiTuong);

	/**
	 * Returns the thu of this thu chi.
	 *
	 * @return the thu of this thu chi
	 */
	public int getThu();

	/**
	 * Sets the thu of this thu chi.
	 *
	 * @param thu the thu of this thu chi
	 */
	public void setThu(int thu);

	/**
	 * Returns the chi of this thu chi.
	 *
	 * @return the chi of this thu chi
	 */
	public int getChi();

	/**
	 * Sets the chi of this thu chi.
	 *
	 * @param chi the chi of this thu chi
	 */
	public void setChi(int chi);

	/**
	 * Returns the nha cung cap ID of this thu chi.
	 *
	 * @return the nha cung cap ID of this thu chi
	 */
	public long getNhaCungCapId();

	/**
	 * Sets the nha cung cap ID of this thu chi.
	 *
	 * @param nhaCungCapId the nha cung cap ID of this thu chi
	 */
	public void setNhaCungCapId(long nhaCungCapId);

	/**
	 * Returns the khach hang ID of this thu chi.
	 *
	 * @return the khach hang ID of this thu chi
	 */
	public long getKhachHangId();

	/**
	 * Sets the khach hang ID of this thu chi.
	 *
	 * @param khachHangId the khach hang ID of this thu chi
	 */
	public void setKhachHangId(long khachHangId);

	/**
	 * Returns the nhan vien ID of this thu chi.
	 *
	 * @return the nhan vien ID of this thu chi
	 */
	public long getNhanVienId();

	/**
	 * Sets the nhan vien ID of this thu chi.
	 *
	 * @param nhanVienId the nhan vien ID of this thu chi
	 */
	public void setNhanVienId(long nhanVienId);

	/**
	 * Returns the the tra truoc ID of this thu chi.
	 *
	 * @return the the tra truoc ID of this thu chi
	 */
	public long getTheTraTruocId();

	/**
	 * Sets the the tra truoc ID of this thu chi.
	 *
	 * @param theTraTruocId the the tra truoc ID of this thu chi
	 */
	public void setTheTraTruocId(long theTraTruocId);

	/**
	 * Returns the tai khoan ngan hang ID of this thu chi.
	 *
	 * @return the tai khoan ngan hang ID of this thu chi
	 */
	public long getTaiKhoanNganHangId();

	/**
	 * Sets the tai khoan ngan hang ID of this thu chi.
	 *
	 * @param taiKhoanNganHangId the tai khoan ngan hang ID of this thu chi
	 */
	public void setTaiKhoanNganHangId(long taiKhoanNganHangId);

	/**
	 * Returns the dat hang ID of this thu chi.
	 *
	 * @return the dat hang ID of this thu chi
	 */
	public long getDatHangId();

	/**
	 * Sets the dat hang ID of this thu chi.
	 *
	 * @param datHangId the dat hang ID of this thu chi
	 */
	public void setDatHangId(long datHangId);

	/**
	 * Returns the bang luong ID of this thu chi.
	 *
	 * @return the bang luong ID of this thu chi
	 */
	public long getBangLuongId();

	/**
	 * Sets the bang luong ID of this thu chi.
	 *
	 * @param bangLuongId the bang luong ID of this thu chi
	 */
	public void setBangLuongId(long bangLuongId);

	/**
	 * Returns the ly do thu chi of this thu chi.
	 *
	 * @return the ly do thu chi of this thu chi
	 */
	@AutoEscape
	public String getLyDoThuChi();

	/**
	 * Sets the ly do thu chi of this thu chi.
	 *
	 * @param lyDoThuChi the ly do thu chi of this thu chi
	 */
	public void setLyDoThuChi(String lyDoThuChi);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.ketoan.model.ThuChi thuChi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.ketoan.model.ThuChi> toCacheModel();

	@Override
	public com.minimart.portlet.ketoan.model.ThuChi toEscapedModel();

	@Override
	public com.minimart.portlet.ketoan.model.ThuChi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}