/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.nhanvien.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedAuditedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NhanVien service. Represents a row in the &quot;minimart_nhanvien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.nhanvien.model.impl.NhanVienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.nhanvien.model.impl.NhanVienImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see NhanVien
 * @see com.minimart.portlet.nhanvien.model.impl.NhanVienImpl
 * @see com.minimart.portlet.nhanvien.model.impl.NhanVienModelImpl
 * @generated
 */
public interface NhanVienModel extends BaseModel<NhanVien>, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhan vien model instance should use the {@link NhanVien} interface instead.
	 */

	/**
	 * Returns the primary key of this nhan vien.
	 *
	 * @return the primary key of this nhan vien
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nhan vien.
	 *
	 * @param primaryKey the primary key of this nhan vien
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this nhan vien.
	 *
	 * @return the uuid of this nhan vien
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this nhan vien.
	 *
	 * @param uuid the uuid of this nhan vien
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the nhan vien ID of this nhan vien.
	 *
	 * @return the nhan vien ID of this nhan vien
	 */
	public long getNhanVienId();

	/**
	 * Sets the nhan vien ID of this nhan vien.
	 *
	 * @param nhanVienId the nhan vien ID of this nhan vien
	 */
	public void setNhanVienId(long nhanVienId);

	/**
	 * Returns the company ID of this nhan vien.
	 *
	 * @return the company ID of this nhan vien
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this nhan vien.
	 *
	 * @param companyId the company ID of this nhan vien
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this nhan vien.
	 *
	 * @return the user ID of this nhan vien
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this nhan vien.
	 *
	 * @param userId the user ID of this nhan vien
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this nhan vien.
	 *
	 * @return the user uuid of this nhan vien
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this nhan vien.
	 *
	 * @param userUuid the user uuid of this nhan vien
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this nhan vien.
	 *
	 * @return the user name of this nhan vien
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this nhan vien.
	 *
	 * @param userName the user name of this nhan vien
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this nhan vien.
	 *
	 * @return the create date of this nhan vien
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this nhan vien.
	 *
	 * @param createDate the create date of this nhan vien
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this nhan vien.
	 *
	 * @return the modified date of this nhan vien
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this nhan vien.
	 *
	 * @param modifiedDate the modified date of this nhan vien
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this nhan vien.
	 *
	 * @return the ten of this nhan vien
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this nhan vien.
	 *
	 * @param ten the ten of this nhan vien
	 */
	public void setTen(String ten);

	/**
	 * Returns the ho of this nhan vien.
	 *
	 * @return the ho of this nhan vien
	 */
	@AutoEscape
	public String getHo();

	/**
	 * Sets the ho of this nhan vien.
	 *
	 * @param ho the ho of this nhan vien
	 */
	public void setHo(String ho);

	/**
	 * Returns the trang thai of this nhan vien.
	 *
	 * @return the trang thai of this nhan vien
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this nhan vien is trang thai.
	 *
	 * @return <code>true</code> if this nhan vien is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this nhan vien is trang thai.
	 *
	 * @param trangThai the trang thai of this nhan vien
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the nghi thu7 of this nhan vien.
	 *
	 * @return the nghi thu7 of this nhan vien
	 */
	public boolean getNghiThu7();

	/**
	 * Returns <code>true</code> if this nhan vien is nghi thu7.
	 *
	 * @return <code>true</code> if this nhan vien is nghi thu7; <code>false</code> otherwise
	 */
	public boolean isNghiThu7();

	/**
	 * Sets whether this nhan vien is nghi thu7.
	 *
	 * @param nghiThu7 the nghi thu7 of this nhan vien
	 */
	public void setNghiThu7(boolean nghiThu7);

	/**
	 * Returns the nghi chu nhat of this nhan vien.
	 *
	 * @return the nghi chu nhat of this nhan vien
	 */
	public boolean getNghiChuNhat();

	/**
	 * Returns <code>true</code> if this nhan vien is nghi chu nhat.
	 *
	 * @return <code>true</code> if this nhan vien is nghi chu nhat; <code>false</code> otherwise
	 */
	public boolean isNghiChuNhat();

	/**
	 * Sets whether this nhan vien is nghi chu nhat.
	 *
	 * @param nghiChuNhat the nghi chu nhat of this nhan vien
	 */
	public void setNghiChuNhat(boolean nghiChuNhat);

	/**
	 * Returns the cach tinh luong of this nhan vien.
	 *
	 * @return the cach tinh luong of this nhan vien
	 */
	public int getCachTinhLuong();

	/**
	 * Sets the cach tinh luong of this nhan vien.
	 *
	 * @param cachTinhLuong the cach tinh luong of this nhan vien
	 */
	public void setCachTinhLuong(int cachTinhLuong);

	/**
	 * Returns the luong ca of this nhan vien.
	 *
	 * @return the luong ca of this nhan vien
	 */
	public int getLuongCa();

	/**
	 * Sets the luong ca of this nhan vien.
	 *
	 * @param luongCa the luong ca of this nhan vien
	 */
	public void setLuongCa(int luongCa);

	/**
	 * Returns the luong thang of this nhan vien.
	 *
	 * @return the luong thang of this nhan vien
	 */
	public int getLuongThang();

	/**
	 * Sets the luong thang of this nhan vien.
	 *
	 * @param luongThang the luong thang of this nhan vien
	 */
	public void setLuongThang(int luongThang);

	/**
	 * Returns the image of this nhan vien.
	 *
	 * @return the image of this nhan vien
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this nhan vien.
	 *
	 * @param image the image of this nhan vien
	 */
	public void setImage(String image);

	/**
	 * Returns the dia chi ID of this nhan vien.
	 *
	 * @return the dia chi ID of this nhan vien
	 */
	public long getDiaChiId();

	/**
	 * Sets the dia chi ID of this nhan vien.
	 *
	 * @param diaChiId the dia chi ID of this nhan vien
	 */
	public void setDiaChiId(long diaChiId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.nhanvien.model.NhanVien nhanVien);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.nhanvien.model.NhanVien> toCacheModel();

	@Override
	public com.minimart.portlet.nhanvien.model.NhanVien toEscapedModel();

	@Override
	public com.minimart.portlet.nhanvien.model.NhanVien toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}