/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.dathang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DatHangChiTiet service. Represents a row in the &quot;minimart_dathangchitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.dathang.model.impl.DatHangChiTietModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.dathang.model.impl.DatHangChiTietImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DatHangChiTiet
 * @see com.minimart.portlet.dathang.model.impl.DatHangChiTietImpl
 * @see com.minimart.portlet.dathang.model.impl.DatHangChiTietModelImpl
 * @generated
 */
public interface DatHangChiTietModel extends AuditedModel,
	BaseModel<DatHangChiTiet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dat hang chi tiet model instance should use the {@link DatHangChiTiet} interface instead.
	 */

	/**
	 * Returns the primary key of this dat hang chi tiet.
	 *
	 * @return the primary key of this dat hang chi tiet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dat hang chi tiet.
	 *
	 * @param primaryKey the primary key of this dat hang chi tiet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dat hang chi tiet ID of this dat hang chi tiet.
	 *
	 * @return the dat hang chi tiet ID of this dat hang chi tiet
	 */
	public long getDatHangChiTietId();

	/**
	 * Sets the dat hang chi tiet ID of this dat hang chi tiet.
	 *
	 * @param datHangChiTietId the dat hang chi tiet ID of this dat hang chi tiet
	 */
	public void setDatHangChiTietId(long datHangChiTietId);

	/**
	 * Returns the company ID of this dat hang chi tiet.
	 *
	 * @return the company ID of this dat hang chi tiet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dat hang chi tiet.
	 *
	 * @param companyId the company ID of this dat hang chi tiet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dat hang chi tiet.
	 *
	 * @return the user ID of this dat hang chi tiet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dat hang chi tiet.
	 *
	 * @param userId the user ID of this dat hang chi tiet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dat hang chi tiet.
	 *
	 * @return the user uuid of this dat hang chi tiet
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dat hang chi tiet.
	 *
	 * @param userUuid the user uuid of this dat hang chi tiet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dat hang chi tiet.
	 *
	 * @return the user name of this dat hang chi tiet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dat hang chi tiet.
	 *
	 * @param userName the user name of this dat hang chi tiet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dat hang chi tiet.
	 *
	 * @return the create date of this dat hang chi tiet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dat hang chi tiet.
	 *
	 * @param createDate the create date of this dat hang chi tiet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dat hang chi tiet.
	 *
	 * @return the modified date of this dat hang chi tiet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dat hang chi tiet.
	 *
	 * @param modifiedDate the modified date of this dat hang chi tiet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the so luong of this dat hang chi tiet.
	 *
	 * @return the so luong of this dat hang chi tiet
	 */
	public int getSoLuong();

	/**
	 * Sets the so luong of this dat hang chi tiet.
	 *
	 * @param soLuong the so luong of this dat hang chi tiet
	 */
	public void setSoLuong(int soLuong);

	/**
	 * Returns the don gia of this dat hang chi tiet.
	 *
	 * @return the don gia of this dat hang chi tiet
	 */
	public int getDonGia();

	/**
	 * Sets the don gia of this dat hang chi tiet.
	 *
	 * @param donGia the don gia of this dat hang chi tiet
	 */
	public void setDonGia(int donGia);

	/**
	 * Returns the thanh tien of this dat hang chi tiet.
	 *
	 * @return the thanh tien of this dat hang chi tiet
	 */
	public int getThanhTien();

	/**
	 * Sets the thanh tien of this dat hang chi tiet.
	 *
	 * @param thanhTien the thanh tien of this dat hang chi tiet
	 */
	public void setThanhTien(int thanhTien);

	/**
	 * Returns the ti le giam gia of this dat hang chi tiet.
	 *
	 * @return the ti le giam gia of this dat hang chi tiet
	 */
	public double getTiLeGiamGia();

	/**
	 * Sets the ti le giam gia of this dat hang chi tiet.
	 *
	 * @param tiLeGiamGia the ti le giam gia of this dat hang chi tiet
	 */
	public void setTiLeGiamGia(double tiLeGiamGia);

	/**
	 * Returns the ghi chu of this dat hang chi tiet.
	 *
	 * @return the ghi chu of this dat hang chi tiet
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this dat hang chi tiet.
	 *
	 * @param ghiChu the ghi chu of this dat hang chi tiet
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the trang thai of this dat hang chi tiet.
	 *
	 * @return the trang thai of this dat hang chi tiet
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this dat hang chi tiet is trang thai.
	 *
	 * @return <code>true</code> if this dat hang chi tiet is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this dat hang chi tiet is trang thai.
	 *
	 * @param trangThai the trang thai of this dat hang chi tiet
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the bao hanh of this dat hang chi tiet.
	 *
	 * @return the bao hanh of this dat hang chi tiet
	 */
	@AutoEscape
	public String getBaoHanh();

	/**
	 * Sets the bao hanh of this dat hang chi tiet.
	 *
	 * @param baoHanh the bao hanh of this dat hang chi tiet
	 */
	public void setBaoHanh(String baoHanh);

	/**
	 * Returns the don vi tinh ID of this dat hang chi tiet.
	 *
	 * @return the don vi tinh ID of this dat hang chi tiet
	 */
	public long getDonViTinhId();

	/**
	 * Sets the don vi tinh ID of this dat hang chi tiet.
	 *
	 * @param donViTinhId the don vi tinh ID of this dat hang chi tiet
	 */
	public void setDonViTinhId(long donViTinhId);

	/**
	 * Returns the dat hang ID of this dat hang chi tiet.
	 *
	 * @return the dat hang ID of this dat hang chi tiet
	 */
	public long getDatHangId();

	/**
	 * Sets the dat hang ID of this dat hang chi tiet.
	 *
	 * @param datHangId the dat hang ID of this dat hang chi tiet
	 */
	public void setDatHangId(long datHangId);

	/**
	 * Returns the ma hang ID of this dat hang chi tiet.
	 *
	 * @return the ma hang ID of this dat hang chi tiet
	 */
	public long getMaHangId();

	/**
	 * Sets the ma hang ID of this dat hang chi tiet.
	 *
	 * @param maHangId the ma hang ID of this dat hang chi tiet
	 */
	public void setMaHangId(long maHangId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.dathang.model.DatHangChiTiet datHangChiTiet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.dathang.model.DatHangChiTiet> toCacheModel();

	@Override
	public com.minimart.portlet.dathang.model.DatHangChiTiet toEscapedModel();

	@Override
	public com.minimart.portlet.dathang.model.DatHangChiTiet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}