/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.dathang.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.minimart.portlet.dathang.model.DatHang;
import com.minimart.portlet.dathang.service.DatHangService;
import com.minimart.portlet.dathang.service.persistence.DatHangChiTietPersistence;
import com.minimart.portlet.dathang.service.persistence.DatHangPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dat hang remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.minimart.portlet.dathang.service.impl.DatHangServiceImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see com.minimart.portlet.dathang.service.impl.DatHangServiceImpl
 * @see com.minimart.portlet.dathang.service.DatHangServiceUtil
 * @generated
 */
public abstract class DatHangServiceBaseImpl extends BaseServiceImpl
	implements DatHangService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.minimart.portlet.dathang.service.DatHangServiceUtil} to access the dat hang remote service.
	 */

	/**
	 * Returns the dat hang local service.
	 *
	 * @return the dat hang local service
	 */
	public com.minimart.portlet.dathang.service.DatHangLocalService getDatHangLocalService() {
		return datHangLocalService;
	}

	/**
	 * Sets the dat hang local service.
	 *
	 * @param datHangLocalService the dat hang local service
	 */
	public void setDatHangLocalService(
		com.minimart.portlet.dathang.service.DatHangLocalService datHangLocalService) {
		this.datHangLocalService = datHangLocalService;
	}

	/**
	 * Returns the dat hang remote service.
	 *
	 * @return the dat hang remote service
	 */
	public com.minimart.portlet.dathang.service.DatHangService getDatHangService() {
		return datHangService;
	}

	/**
	 * Sets the dat hang remote service.
	 *
	 * @param datHangService the dat hang remote service
	 */
	public void setDatHangService(
		com.minimart.portlet.dathang.service.DatHangService datHangService) {
		this.datHangService = datHangService;
	}

	/**
	 * Returns the dat hang persistence.
	 *
	 * @return the dat hang persistence
	 */
	public DatHangPersistence getDatHangPersistence() {
		return datHangPersistence;
	}

	/**
	 * Sets the dat hang persistence.
	 *
	 * @param datHangPersistence the dat hang persistence
	 */
	public void setDatHangPersistence(DatHangPersistence datHangPersistence) {
		this.datHangPersistence = datHangPersistence;
	}

	/**
	 * Returns the dat hang chi tiet local service.
	 *
	 * @return the dat hang chi tiet local service
	 */
	public com.minimart.portlet.dathang.service.DatHangChiTietLocalService getDatHangChiTietLocalService() {
		return datHangChiTietLocalService;
	}

	/**
	 * Sets the dat hang chi tiet local service.
	 *
	 * @param datHangChiTietLocalService the dat hang chi tiet local service
	 */
	public void setDatHangChiTietLocalService(
		com.minimart.portlet.dathang.service.DatHangChiTietLocalService datHangChiTietLocalService) {
		this.datHangChiTietLocalService = datHangChiTietLocalService;
	}

	/**
	 * Returns the dat hang chi tiet remote service.
	 *
	 * @return the dat hang chi tiet remote service
	 */
	public com.minimart.portlet.dathang.service.DatHangChiTietService getDatHangChiTietService() {
		return datHangChiTietService;
	}

	/**
	 * Sets the dat hang chi tiet remote service.
	 *
	 * @param datHangChiTietService the dat hang chi tiet remote service
	 */
	public void setDatHangChiTietService(
		com.minimart.portlet.dathang.service.DatHangChiTietService datHangChiTietService) {
		this.datHangChiTietService = datHangChiTietService;
	}

	/**
	 * Returns the dat hang chi tiet persistence.
	 *
	 * @return the dat hang chi tiet persistence
	 */
	public DatHangChiTietPersistence getDatHangChiTietPersistence() {
		return datHangChiTietPersistence;
	}

	/**
	 * Sets the dat hang chi tiet persistence.
	 *
	 * @param datHangChiTietPersistence the dat hang chi tiet persistence
	 */
	public void setDatHangChiTietPersistence(
		DatHangChiTietPersistence datHangChiTietPersistence) {
		this.datHangChiTietPersistence = datHangChiTietPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return DatHang.class;
	}

	protected String getModelClassName() {
		return DatHang.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = datHangPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.minimart.portlet.dathang.service.DatHangLocalService.class)
	protected com.minimart.portlet.dathang.service.DatHangLocalService datHangLocalService;
	@BeanReference(type = com.minimart.portlet.dathang.service.DatHangService.class)
	protected com.minimart.portlet.dathang.service.DatHangService datHangService;
	@BeanReference(type = DatHangPersistence.class)
	protected DatHangPersistence datHangPersistence;
	@BeanReference(type = com.minimart.portlet.dathang.service.DatHangChiTietLocalService.class)
	protected com.minimart.portlet.dathang.service.DatHangChiTietLocalService datHangChiTietLocalService;
	@BeanReference(type = com.minimart.portlet.dathang.service.DatHangChiTietService.class)
	protected com.minimart.portlet.dathang.service.DatHangChiTietService datHangChiTietService;
	@BeanReference(type = DatHangChiTietPersistence.class)
	protected DatHangChiTietPersistence datHangChiTietPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private DatHangServiceClpInvoker _clpInvoker = new DatHangServiceClpInvoker();
}