/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.ketoan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.ketoan.model.BangLuong;
import com.minimart.portlet.ketoan.model.BangLuongModel;
import com.minimart.portlet.ketoan.model.BangLuongSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BangLuong service. Represents a row in the &quot;minimart_bangluong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.ketoan.model.BangLuongModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BangLuongImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see BangLuongImpl
 * @see com.minimart.portlet.ketoan.model.BangLuong
 * @see com.minimart.portlet.ketoan.model.BangLuongModel
 * @generated
 */
@JSON(strict = true)
public class BangLuongModelImpl extends BaseModelImpl<BangLuong>
	implements BangLuongModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bang luong model instance should use the {@link com.minimart.portlet.ketoan.model.BangLuong} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_bangluong";
	public static final Object[][] TABLE_COLUMNS = {
			{ "banLuongId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "trangThai", Types.BOOLEAN },
			{ "thang", Types.INTEGER },
			{ "nam", Types.INTEGER },
			{ "ngay", Types.TIMESTAMP },
			{ "chiTiet", Types.VARCHAR },
			{ "ghiChu", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_bangluong (banLuongId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,trangThai BOOLEAN,thang INTEGER,nam INTEGER,ngay DATE null,chiTiet VARCHAR(75) null,ghiChu VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_bangluong";
	public static final String ORDER_BY_JPQL = " ORDER BY bangLuong.ten ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_bangluong.ten ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.ketoan.model.BangLuong"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.ketoan.model.BangLuong"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.ketoan.model.BangLuong"),
			true);
	public static long TEN_COLUMN_BITMASK = 1L;
	public static long TRANGTHAI_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BangLuong toModel(BangLuongSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BangLuong model = new BangLuongImpl();

		model.setBanLuongId(soapModel.getBanLuongId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setTrangThai(soapModel.getTrangThai());
		model.setThang(soapModel.getThang());
		model.setNam(soapModel.getNam());
		model.setNgay(soapModel.getNgay());
		model.setChiTiet(soapModel.getChiTiet());
		model.setGhiChu(soapModel.getGhiChu());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BangLuong> toModels(BangLuongSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BangLuong> models = new ArrayList<BangLuong>(soapModels.length);

		for (BangLuongSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.ketoan.model.BangLuong"));

	public BangLuongModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _banLuongId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBanLuongId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _banLuongId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BangLuong.class;
	}

	@Override
	public String getModelClassName() {
		return BangLuong.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("banLuongId", getBanLuongId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("trangThai", getTrangThai());
		attributes.put("thang", getThang());
		attributes.put("nam", getNam());
		attributes.put("ngay", getNgay());
		attributes.put("chiTiet", getChiTiet());
		attributes.put("ghiChu", getGhiChu());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long banLuongId = (Long)attributes.get("banLuongId");

		if (banLuongId != null) {
			setBanLuongId(banLuongId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		Boolean trangThai = (Boolean)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Integer thang = (Integer)attributes.get("thang");

		if (thang != null) {
			setThang(thang);
		}

		Integer nam = (Integer)attributes.get("nam");

		if (nam != null) {
			setNam(nam);
		}

		Date ngay = (Date)attributes.get("ngay");

		if (ngay != null) {
			setNgay(ngay);
		}

		String chiTiet = (String)attributes.get("chiTiet");

		if (chiTiet != null) {
			setChiTiet(chiTiet);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}
	}

	@JSON
	@Override
	public long getBanLuongId() {
		return _banLuongId;
	}

	@Override
	public void setBanLuongId(long banLuongId) {
		_banLuongId = banLuongId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public boolean getTrangThai() {
		return _trangThai;
	}

	@Override
	public boolean isTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(boolean trangThai) {
		_columnBitmask |= TRANGTHAI_COLUMN_BITMASK;

		if (!_setOriginalTrangThai) {
			_setOriginalTrangThai = true;

			_originalTrangThai = _trangThai;
		}

		_trangThai = trangThai;
	}

	public boolean getOriginalTrangThai() {
		return _originalTrangThai;
	}

	@JSON
	@Override
	public int getThang() {
		return _thang;
	}

	@Override
	public void setThang(int thang) {
		_thang = thang;
	}

	@JSON
	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_nam = nam;
	}

	@JSON
	@Override
	public Date getNgay() {
		return _ngay;
	}

	@Override
	public void setNgay(Date ngay) {
		_ngay = ngay;
	}

	@JSON
	@Override
	public String getChiTiet() {
		if (_chiTiet == null) {
			return StringPool.BLANK;
		}
		else {
			return _chiTiet;
		}
	}

	@Override
	public void setChiTiet(String chiTiet) {
		_chiTiet = chiTiet;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BangLuong.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BangLuong toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BangLuong)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BangLuongImpl bangLuongImpl = new BangLuongImpl();

		bangLuongImpl.setBanLuongId(getBanLuongId());
		bangLuongImpl.setCompanyId(getCompanyId());
		bangLuongImpl.setUserId(getUserId());
		bangLuongImpl.setUserName(getUserName());
		bangLuongImpl.setCreateDate(getCreateDate());
		bangLuongImpl.setModifiedDate(getModifiedDate());
		bangLuongImpl.setTen(getTen());
		bangLuongImpl.setTrangThai(getTrangThai());
		bangLuongImpl.setThang(getThang());
		bangLuongImpl.setNam(getNam());
		bangLuongImpl.setNgay(getNgay());
		bangLuongImpl.setChiTiet(getChiTiet());
		bangLuongImpl.setGhiChu(getGhiChu());

		bangLuongImpl.resetOriginalValues();

		return bangLuongImpl;
	}

	@Override
	public int compareTo(BangLuong bangLuong) {
		int value = 0;

		value = getTen().compareTo(bangLuong.getTen());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BangLuong)) {
			return false;
		}

		BangLuong bangLuong = (BangLuong)obj;

		long primaryKey = bangLuong.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BangLuongModelImpl bangLuongModelImpl = this;

		bangLuongModelImpl._originalTen = bangLuongModelImpl._ten;

		bangLuongModelImpl._originalTrangThai = bangLuongModelImpl._trangThai;

		bangLuongModelImpl._setOriginalTrangThai = false;

		bangLuongModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BangLuong> toCacheModel() {
		BangLuongCacheModel bangLuongCacheModel = new BangLuongCacheModel();

		bangLuongCacheModel.banLuongId = getBanLuongId();

		bangLuongCacheModel.companyId = getCompanyId();

		bangLuongCacheModel.userId = getUserId();

		bangLuongCacheModel.userName = getUserName();

		String userName = bangLuongCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			bangLuongCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bangLuongCacheModel.createDate = createDate.getTime();
		}
		else {
			bangLuongCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bangLuongCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bangLuongCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bangLuongCacheModel.ten = getTen();

		String ten = bangLuongCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			bangLuongCacheModel.ten = null;
		}

		bangLuongCacheModel.trangThai = getTrangThai();

		bangLuongCacheModel.thang = getThang();

		bangLuongCacheModel.nam = getNam();

		Date ngay = getNgay();

		if (ngay != null) {
			bangLuongCacheModel.ngay = ngay.getTime();
		}
		else {
			bangLuongCacheModel.ngay = Long.MIN_VALUE;
		}

		bangLuongCacheModel.chiTiet = getChiTiet();

		String chiTiet = bangLuongCacheModel.chiTiet;

		if ((chiTiet != null) && (chiTiet.length() == 0)) {
			bangLuongCacheModel.chiTiet = null;
		}

		bangLuongCacheModel.ghiChu = getGhiChu();

		String ghiChu = bangLuongCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			bangLuongCacheModel.ghiChu = null;
		}

		return bangLuongCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{banLuongId=");
		sb.append(getBanLuongId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", thang=");
		sb.append(getThang());
		sb.append(", nam=");
		sb.append(getNam());
		sb.append(", ngay=");
		sb.append(getNgay());
		sb.append(", chiTiet=");
		sb.append(getChiTiet());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.ketoan.model.BangLuong");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>banLuongId</column-name><column-value><![CDATA[");
		sb.append(getBanLuongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thang</column-name><column-value><![CDATA[");
		sb.append(getThang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nam</column-name><column-value><![CDATA[");
		sb.append(getNam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngay</column-name><column-value><![CDATA[");
		sb.append(getNgay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiTiet</column-name><column-value><![CDATA[");
		sb.append(getChiTiet());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BangLuong.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BangLuong.class
		};
	private long _banLuongId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private boolean _trangThai;
	private boolean _originalTrangThai;
	private boolean _setOriginalTrangThai;
	private int _thang;
	private int _nam;
	private Date _ngay;
	private String _chiTiet;
	private String _ghiChu;
	private long _columnBitmask;
	private BangLuong _escapedModel;
}