/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.ketoan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.ketoan.model.ThuChi;
import com.minimart.portlet.ketoan.model.ThuChiModel;
import com.minimart.portlet.ketoan.model.ThuChiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ThuChi service. Represents a row in the &quot;minimart_thuchi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.ketoan.model.ThuChiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThuChiImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see ThuChiImpl
 * @see com.minimart.portlet.ketoan.model.ThuChi
 * @see com.minimart.portlet.ketoan.model.ThuChiModel
 * @generated
 */
@JSON(strict = true)
public class ThuChiModelImpl extends BaseModelImpl<ThuChi>
	implements ThuChiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thu chi model instance should use the {@link com.minimart.portlet.ketoan.model.ThuChi} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_thuchi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "thuChiId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "tenDoiTuong", Types.VARCHAR },
			{ "diaChiId", Types.BIGINT },
			{ "loai", Types.INTEGER },
			{ "loaiDoiTuong", Types.INTEGER },
			{ "thu", Types.INTEGER },
			{ "chi", Types.INTEGER },
			{ "nhaCungCapId", Types.BIGINT },
			{ "khachHangId", Types.BIGINT },
			{ "nhanVienId", Types.BIGINT },
			{ "theTraTruocId", Types.BIGINT },
			{ "taiKhoanNganHangId", Types.BIGINT },
			{ "datHangId", Types.BIGINT },
			{ "bangLuongId", Types.BIGINT },
			{ "lyDoThuChi", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_thuchi (thuChiId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,tenDoiTuong VARCHAR(75) null,diaChiId LONG,loai INTEGER,loaiDoiTuong INTEGER,thu INTEGER,chi INTEGER,nhaCungCapId LONG,khachHangId LONG,nhanVienId LONG,theTraTruocId LONG,taiKhoanNganHangId LONG,datHangId LONG,bangLuongId LONG,lyDoThuChi VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_thuchi";
	public static final String ORDER_BY_JPQL = " ORDER BY thuChi.ten ASC, thuChi.tenDoiTuong ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_thuchi.ten ASC, minimart_thuchi.tenDoiTuong ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.ketoan.model.ThuChi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.ketoan.model.ThuChi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.ketoan.model.ThuChi"),
			true);
	public static long LYDOTHUCHI_COLUMN_BITMASK = 1L;
	public static long NHANVIENID_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static long TENDOITUONG_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ThuChi toModel(ThuChiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ThuChi model = new ThuChiImpl();

		model.setThuChiId(soapModel.getThuChiId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setTenDoiTuong(soapModel.getTenDoiTuong());
		model.setDiaChiId(soapModel.getDiaChiId());
		model.setLoai(soapModel.getLoai());
		model.setLoaiDoiTuong(soapModel.getLoaiDoiTuong());
		model.setThu(soapModel.getThu());
		model.setChi(soapModel.getChi());
		model.setNhaCungCapId(soapModel.getNhaCungCapId());
		model.setKhachHangId(soapModel.getKhachHangId());
		model.setNhanVienId(soapModel.getNhanVienId());
		model.setTheTraTruocId(soapModel.getTheTraTruocId());
		model.setTaiKhoanNganHangId(soapModel.getTaiKhoanNganHangId());
		model.setDatHangId(soapModel.getDatHangId());
		model.setBangLuongId(soapModel.getBangLuongId());
		model.setLyDoThuChi(soapModel.getLyDoThuChi());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ThuChi> toModels(ThuChiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ThuChi> models = new ArrayList<ThuChi>(soapModels.length);

		for (ThuChiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.ketoan.model.ThuChi"));

	public ThuChiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _thuChiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setThuChiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _thuChiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ThuChi.class;
	}

	@Override
	public String getModelClassName() {
		return ThuChi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("thuChiId", getThuChiId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("tenDoiTuong", getTenDoiTuong());
		attributes.put("diaChiId", getDiaChiId());
		attributes.put("loai", getLoai());
		attributes.put("loaiDoiTuong", getLoaiDoiTuong());
		attributes.put("thu", getThu());
		attributes.put("chi", getChi());
		attributes.put("nhaCungCapId", getNhaCungCapId());
		attributes.put("khachHangId", getKhachHangId());
		attributes.put("nhanVienId", getNhanVienId());
		attributes.put("theTraTruocId", getTheTraTruocId());
		attributes.put("taiKhoanNganHangId", getTaiKhoanNganHangId());
		attributes.put("datHangId", getDatHangId());
		attributes.put("bangLuongId", getBangLuongId());
		attributes.put("lyDoThuChi", getLyDoThuChi());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long thuChiId = (Long)attributes.get("thuChiId");

		if (thuChiId != null) {
			setThuChiId(thuChiId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		String tenDoiTuong = (String)attributes.get("tenDoiTuong");

		if (tenDoiTuong != null) {
			setTenDoiTuong(tenDoiTuong);
		}

		Long diaChiId = (Long)attributes.get("diaChiId");

		if (diaChiId != null) {
			setDiaChiId(diaChiId);
		}

		Integer loai = (Integer)attributes.get("loai");

		if (loai != null) {
			setLoai(loai);
		}

		Integer loaiDoiTuong = (Integer)attributes.get("loaiDoiTuong");

		if (loaiDoiTuong != null) {
			setLoaiDoiTuong(loaiDoiTuong);
		}

		Integer thu = (Integer)attributes.get("thu");

		if (thu != null) {
			setThu(thu);
		}

		Integer chi = (Integer)attributes.get("chi");

		if (chi != null) {
			setChi(chi);
		}

		Long nhaCungCapId = (Long)attributes.get("nhaCungCapId");

		if (nhaCungCapId != null) {
			setNhaCungCapId(nhaCungCapId);
		}

		Long khachHangId = (Long)attributes.get("khachHangId");

		if (khachHangId != null) {
			setKhachHangId(khachHangId);
		}

		Long nhanVienId = (Long)attributes.get("nhanVienId");

		if (nhanVienId != null) {
			setNhanVienId(nhanVienId);
		}

		Long theTraTruocId = (Long)attributes.get("theTraTruocId");

		if (theTraTruocId != null) {
			setTheTraTruocId(theTraTruocId);
		}

		Long taiKhoanNganHangId = (Long)attributes.get("taiKhoanNganHangId");

		if (taiKhoanNganHangId != null) {
			setTaiKhoanNganHangId(taiKhoanNganHangId);
		}

		Long datHangId = (Long)attributes.get("datHangId");

		if (datHangId != null) {
			setDatHangId(datHangId);
		}

		Long bangLuongId = (Long)attributes.get("bangLuongId");

		if (bangLuongId != null) {
			setBangLuongId(bangLuongId);
		}

		String lyDoThuChi = (String)attributes.get("lyDoThuChi");

		if (lyDoThuChi != null) {
			setLyDoThuChi(lyDoThuChi);
		}
	}

	@JSON
	@Override
	public long getThuChiId() {
		return _thuChiId;
	}

	@Override
	public void setThuChiId(long thuChiId) {
		_thuChiId = thuChiId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public String getTenDoiTuong() {
		if (_tenDoiTuong == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDoiTuong;
		}
	}

	@Override
	public void setTenDoiTuong(String tenDoiTuong) {
		_columnBitmask = -1L;

		_tenDoiTuong = tenDoiTuong;
	}

	@JSON
	@Override
	public long getDiaChiId() {
		return _diaChiId;
	}

	@Override
	public void setDiaChiId(long diaChiId) {
		_diaChiId = diaChiId;
	}

	@JSON
	@Override
	public int getLoai() {
		return _loai;
	}

	@Override
	public void setLoai(int loai) {
		_loai = loai;
	}

	@JSON
	@Override
	public int getLoaiDoiTuong() {
		return _loaiDoiTuong;
	}

	@Override
	public void setLoaiDoiTuong(int loaiDoiTuong) {
		_loaiDoiTuong = loaiDoiTuong;
	}

	@JSON
	@Override
	public int getThu() {
		return _thu;
	}

	@Override
	public void setThu(int thu) {
		_thu = thu;
	}

	@JSON
	@Override
	public int getChi() {
		return _chi;
	}

	@Override
	public void setChi(int chi) {
		_chi = chi;
	}

	@JSON
	@Override
	public long getNhaCungCapId() {
		return _nhaCungCapId;
	}

	@Override
	public void setNhaCungCapId(long nhaCungCapId) {
		_nhaCungCapId = nhaCungCapId;
	}

	@JSON
	@Override
	public long getKhachHangId() {
		return _khachHangId;
	}

	@Override
	public void setKhachHangId(long khachHangId) {
		_khachHangId = khachHangId;
	}

	@JSON
	@Override
	public long getNhanVienId() {
		return _nhanVienId;
	}

	@Override
	public void setNhanVienId(long nhanVienId) {
		_columnBitmask |= NHANVIENID_COLUMN_BITMASK;

		if (!_setOriginalNhanVienId) {
			_setOriginalNhanVienId = true;

			_originalNhanVienId = _nhanVienId;
		}

		_nhanVienId = nhanVienId;
	}

	public long getOriginalNhanVienId() {
		return _originalNhanVienId;
	}

	@JSON
	@Override
	public long getTheTraTruocId() {
		return _theTraTruocId;
	}

	@Override
	public void setTheTraTruocId(long theTraTruocId) {
		_theTraTruocId = theTraTruocId;
	}

	@JSON
	@Override
	public long getTaiKhoanNganHangId() {
		return _taiKhoanNganHangId;
	}

	@Override
	public void setTaiKhoanNganHangId(long taiKhoanNganHangId) {
		_taiKhoanNganHangId = taiKhoanNganHangId;
	}

	@JSON
	@Override
	public long getDatHangId() {
		return _datHangId;
	}

	@Override
	public void setDatHangId(long datHangId) {
		_datHangId = datHangId;
	}

	@JSON
	@Override
	public long getBangLuongId() {
		return _bangLuongId;
	}

	@Override
	public void setBangLuongId(long bangLuongId) {
		_bangLuongId = bangLuongId;
	}

	@JSON
	@Override
	public String getLyDoThuChi() {
		if (_lyDoThuChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoThuChi;
		}
	}

	@Override
	public void setLyDoThuChi(String lyDoThuChi) {
		_columnBitmask |= LYDOTHUCHI_COLUMN_BITMASK;

		if (_originalLyDoThuChi == null) {
			_originalLyDoThuChi = _lyDoThuChi;
		}

		_lyDoThuChi = lyDoThuChi;
	}

	public String getOriginalLyDoThuChi() {
		return GetterUtil.getString(_originalLyDoThuChi);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ThuChi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ThuChi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ThuChi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThuChiImpl thuChiImpl = new ThuChiImpl();

		thuChiImpl.setThuChiId(getThuChiId());
		thuChiImpl.setCompanyId(getCompanyId());
		thuChiImpl.setUserId(getUserId());
		thuChiImpl.setUserName(getUserName());
		thuChiImpl.setCreateDate(getCreateDate());
		thuChiImpl.setModifiedDate(getModifiedDate());
		thuChiImpl.setTen(getTen());
		thuChiImpl.setTenDoiTuong(getTenDoiTuong());
		thuChiImpl.setDiaChiId(getDiaChiId());
		thuChiImpl.setLoai(getLoai());
		thuChiImpl.setLoaiDoiTuong(getLoaiDoiTuong());
		thuChiImpl.setThu(getThu());
		thuChiImpl.setChi(getChi());
		thuChiImpl.setNhaCungCapId(getNhaCungCapId());
		thuChiImpl.setKhachHangId(getKhachHangId());
		thuChiImpl.setNhanVienId(getNhanVienId());
		thuChiImpl.setTheTraTruocId(getTheTraTruocId());
		thuChiImpl.setTaiKhoanNganHangId(getTaiKhoanNganHangId());
		thuChiImpl.setDatHangId(getDatHangId());
		thuChiImpl.setBangLuongId(getBangLuongId());
		thuChiImpl.setLyDoThuChi(getLyDoThuChi());

		thuChiImpl.resetOriginalValues();

		return thuChiImpl;
	}

	@Override
	public int compareTo(ThuChi thuChi) {
		int value = 0;

		value = getTen().compareTo(thuChi.getTen());

		if (value != 0) {
			return value;
		}

		value = getTenDoiTuong().compareTo(thuChi.getTenDoiTuong());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ThuChi)) {
			return false;
		}

		ThuChi thuChi = (ThuChi)obj;

		long primaryKey = thuChi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ThuChiModelImpl thuChiModelImpl = this;

		thuChiModelImpl._originalTen = thuChiModelImpl._ten;

		thuChiModelImpl._originalNhanVienId = thuChiModelImpl._nhanVienId;

		thuChiModelImpl._setOriginalNhanVienId = false;

		thuChiModelImpl._originalLyDoThuChi = thuChiModelImpl._lyDoThuChi;

		thuChiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ThuChi> toCacheModel() {
		ThuChiCacheModel thuChiCacheModel = new ThuChiCacheModel();

		thuChiCacheModel.thuChiId = getThuChiId();

		thuChiCacheModel.companyId = getCompanyId();

		thuChiCacheModel.userId = getUserId();

		thuChiCacheModel.userName = getUserName();

		String userName = thuChiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			thuChiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			thuChiCacheModel.createDate = createDate.getTime();
		}
		else {
			thuChiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			thuChiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			thuChiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		thuChiCacheModel.ten = getTen();

		String ten = thuChiCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			thuChiCacheModel.ten = null;
		}

		thuChiCacheModel.tenDoiTuong = getTenDoiTuong();

		String tenDoiTuong = thuChiCacheModel.tenDoiTuong;

		if ((tenDoiTuong != null) && (tenDoiTuong.length() == 0)) {
			thuChiCacheModel.tenDoiTuong = null;
		}

		thuChiCacheModel.diaChiId = getDiaChiId();

		thuChiCacheModel.loai = getLoai();

		thuChiCacheModel.loaiDoiTuong = getLoaiDoiTuong();

		thuChiCacheModel.thu = getThu();

		thuChiCacheModel.chi = getChi();

		thuChiCacheModel.nhaCungCapId = getNhaCungCapId();

		thuChiCacheModel.khachHangId = getKhachHangId();

		thuChiCacheModel.nhanVienId = getNhanVienId();

		thuChiCacheModel.theTraTruocId = getTheTraTruocId();

		thuChiCacheModel.taiKhoanNganHangId = getTaiKhoanNganHangId();

		thuChiCacheModel.datHangId = getDatHangId();

		thuChiCacheModel.bangLuongId = getBangLuongId();

		thuChiCacheModel.lyDoThuChi = getLyDoThuChi();

		String lyDoThuChi = thuChiCacheModel.lyDoThuChi;

		if ((lyDoThuChi != null) && (lyDoThuChi.length() == 0)) {
			thuChiCacheModel.lyDoThuChi = null;
		}

		return thuChiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(43);

		sb.append("{thuChiId=");
		sb.append(getThuChiId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", tenDoiTuong=");
		sb.append(getTenDoiTuong());
		sb.append(", diaChiId=");
		sb.append(getDiaChiId());
		sb.append(", loai=");
		sb.append(getLoai());
		sb.append(", loaiDoiTuong=");
		sb.append(getLoaiDoiTuong());
		sb.append(", thu=");
		sb.append(getThu());
		sb.append(", chi=");
		sb.append(getChi());
		sb.append(", nhaCungCapId=");
		sb.append(getNhaCungCapId());
		sb.append(", khachHangId=");
		sb.append(getKhachHangId());
		sb.append(", nhanVienId=");
		sb.append(getNhanVienId());
		sb.append(", theTraTruocId=");
		sb.append(getTheTraTruocId());
		sb.append(", taiKhoanNganHangId=");
		sb.append(getTaiKhoanNganHangId());
		sb.append(", datHangId=");
		sb.append(getDatHangId());
		sb.append(", bangLuongId=");
		sb.append(getBangLuongId());
		sb.append(", lyDoThuChi=");
		sb.append(getLyDoThuChi());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(67);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.ketoan.model.ThuChi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>thuChiId</column-name><column-value><![CDATA[");
		sb.append(getThuChiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDoiTuong</column-name><column-value><![CDATA[");
		sb.append(getTenDoiTuong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loai</column-name><column-value><![CDATA[");
		sb.append(getLoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoiTuong</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoiTuong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu</column-name><column-value><![CDATA[");
		sb.append(getThu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chi</column-name><column-value><![CDATA[");
		sb.append(getChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhaCungCapId</column-name><column-value><![CDATA[");
		sb.append(getNhaCungCapId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>khachHangId</column-name><column-value><![CDATA[");
		sb.append(getKhachHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhanVienId</column-name><column-value><![CDATA[");
		sb.append(getNhanVienId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>theTraTruocId</column-name><column-value><![CDATA[");
		sb.append(getTheTraTruocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoanNganHangId</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoanNganHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>datHangId</column-name><column-value><![CDATA[");
		sb.append(getDatHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bangLuongId</column-name><column-value><![CDATA[");
		sb.append(getBangLuongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoThuChi</column-name><column-value><![CDATA[");
		sb.append(getLyDoThuChi());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ThuChi.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { ThuChi.class };
	private long _thuChiId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private String _tenDoiTuong;
	private long _diaChiId;
	private int _loai;
	private int _loaiDoiTuong;
	private int _thu;
	private int _chi;
	private long _nhaCungCapId;
	private long _khachHangId;
	private long _nhanVienId;
	private long _originalNhanVienId;
	private boolean _setOriginalNhanVienId;
	private long _theTraTruocId;
	private long _taiKhoanNganHangId;
	private long _datHangId;
	private long _bangLuongId;
	private String _lyDoThuChi;
	private String _originalLyDoThuChi;
	private long _columnBitmask;
	private ThuChi _escapedModel;
}