/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.banhang.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.minimart.portlet.banhang.model.DonHangChiTiet;
import com.minimart.portlet.banhang.service.DonHangChiTietService;
import com.minimart.portlet.banhang.service.persistence.DonHangChiTietPersistence;
import com.minimart.portlet.banhang.service.persistence.DonHangPersistence;
import com.minimart.portlet.banhang.service.persistence.TrangThaiDonHangPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the don hang chi tiet remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.minimart.portlet.banhang.service.impl.DonHangChiTietServiceImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see com.minimart.portlet.banhang.service.impl.DonHangChiTietServiceImpl
 * @see com.minimart.portlet.banhang.service.DonHangChiTietServiceUtil
 * @generated
 */
public abstract class DonHangChiTietServiceBaseImpl extends BaseServiceImpl
	implements DonHangChiTietService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.minimart.portlet.banhang.service.DonHangChiTietServiceUtil} to access the don hang chi tiet remote service.
	 */

	/**
	 * Returns the don hang local service.
	 *
	 * @return the don hang local service
	 */
	public com.minimart.portlet.banhang.service.DonHangLocalService getDonHangLocalService() {
		return donHangLocalService;
	}

	/**
	 * Sets the don hang local service.
	 *
	 * @param donHangLocalService the don hang local service
	 */
	public void setDonHangLocalService(
		com.minimart.portlet.banhang.service.DonHangLocalService donHangLocalService) {
		this.donHangLocalService = donHangLocalService;
	}

	/**
	 * Returns the don hang remote service.
	 *
	 * @return the don hang remote service
	 */
	public com.minimart.portlet.banhang.service.DonHangService getDonHangService() {
		return donHangService;
	}

	/**
	 * Sets the don hang remote service.
	 *
	 * @param donHangService the don hang remote service
	 */
	public void setDonHangService(
		com.minimart.portlet.banhang.service.DonHangService donHangService) {
		this.donHangService = donHangService;
	}

	/**
	 * Returns the don hang persistence.
	 *
	 * @return the don hang persistence
	 */
	public DonHangPersistence getDonHangPersistence() {
		return donHangPersistence;
	}

	/**
	 * Sets the don hang persistence.
	 *
	 * @param donHangPersistence the don hang persistence
	 */
	public void setDonHangPersistence(DonHangPersistence donHangPersistence) {
		this.donHangPersistence = donHangPersistence;
	}

	/**
	 * Returns the don hang chi tiet local service.
	 *
	 * @return the don hang chi tiet local service
	 */
	public com.minimart.portlet.banhang.service.DonHangChiTietLocalService getDonHangChiTietLocalService() {
		return donHangChiTietLocalService;
	}

	/**
	 * Sets the don hang chi tiet local service.
	 *
	 * @param donHangChiTietLocalService the don hang chi tiet local service
	 */
	public void setDonHangChiTietLocalService(
		com.minimart.portlet.banhang.service.DonHangChiTietLocalService donHangChiTietLocalService) {
		this.donHangChiTietLocalService = donHangChiTietLocalService;
	}

	/**
	 * Returns the don hang chi tiet remote service.
	 *
	 * @return the don hang chi tiet remote service
	 */
	public com.minimart.portlet.banhang.service.DonHangChiTietService getDonHangChiTietService() {
		return donHangChiTietService;
	}

	/**
	 * Sets the don hang chi tiet remote service.
	 *
	 * @param donHangChiTietService the don hang chi tiet remote service
	 */
	public void setDonHangChiTietService(
		com.minimart.portlet.banhang.service.DonHangChiTietService donHangChiTietService) {
		this.donHangChiTietService = donHangChiTietService;
	}

	/**
	 * Returns the don hang chi tiet persistence.
	 *
	 * @return the don hang chi tiet persistence
	 */
	public DonHangChiTietPersistence getDonHangChiTietPersistence() {
		return donHangChiTietPersistence;
	}

	/**
	 * Sets the don hang chi tiet persistence.
	 *
	 * @param donHangChiTietPersistence the don hang chi tiet persistence
	 */
	public void setDonHangChiTietPersistence(
		DonHangChiTietPersistence donHangChiTietPersistence) {
		this.donHangChiTietPersistence = donHangChiTietPersistence;
	}

	/**
	 * Returns the trang thai don hang local service.
	 *
	 * @return the trang thai don hang local service
	 */
	public com.minimart.portlet.banhang.service.TrangThaiDonHangLocalService getTrangThaiDonHangLocalService() {
		return trangThaiDonHangLocalService;
	}

	/**
	 * Sets the trang thai don hang local service.
	 *
	 * @param trangThaiDonHangLocalService the trang thai don hang local service
	 */
	public void setTrangThaiDonHangLocalService(
		com.minimart.portlet.banhang.service.TrangThaiDonHangLocalService trangThaiDonHangLocalService) {
		this.trangThaiDonHangLocalService = trangThaiDonHangLocalService;
	}

	/**
	 * Returns the trang thai don hang remote service.
	 *
	 * @return the trang thai don hang remote service
	 */
	public com.minimart.portlet.banhang.service.TrangThaiDonHangService getTrangThaiDonHangService() {
		return trangThaiDonHangService;
	}

	/**
	 * Sets the trang thai don hang remote service.
	 *
	 * @param trangThaiDonHangService the trang thai don hang remote service
	 */
	public void setTrangThaiDonHangService(
		com.minimart.portlet.banhang.service.TrangThaiDonHangService trangThaiDonHangService) {
		this.trangThaiDonHangService = trangThaiDonHangService;
	}

	/**
	 * Returns the trang thai don hang persistence.
	 *
	 * @return the trang thai don hang persistence
	 */
	public TrangThaiDonHangPersistence getTrangThaiDonHangPersistence() {
		return trangThaiDonHangPersistence;
	}

	/**
	 * Sets the trang thai don hang persistence.
	 *
	 * @param trangThaiDonHangPersistence the trang thai don hang persistence
	 */
	public void setTrangThaiDonHangPersistence(
		TrangThaiDonHangPersistence trangThaiDonHangPersistence) {
		this.trangThaiDonHangPersistence = trangThaiDonHangPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return DonHangChiTiet.class;
	}

	protected String getModelClassName() {
		return DonHangChiTiet.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = donHangChiTietPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.minimart.portlet.banhang.service.DonHangLocalService.class)
	protected com.minimart.portlet.banhang.service.DonHangLocalService donHangLocalService;
	@BeanReference(type = com.minimart.portlet.banhang.service.DonHangService.class)
	protected com.minimart.portlet.banhang.service.DonHangService donHangService;
	@BeanReference(type = DonHangPersistence.class)
	protected DonHangPersistence donHangPersistence;
	@BeanReference(type = com.minimart.portlet.banhang.service.DonHangChiTietLocalService.class)
	protected com.minimart.portlet.banhang.service.DonHangChiTietLocalService donHangChiTietLocalService;
	@BeanReference(type = com.minimart.portlet.banhang.service.DonHangChiTietService.class)
	protected com.minimart.portlet.banhang.service.DonHangChiTietService donHangChiTietService;
	@BeanReference(type = DonHangChiTietPersistence.class)
	protected DonHangChiTietPersistence donHangChiTietPersistence;
	@BeanReference(type = com.minimart.portlet.banhang.service.TrangThaiDonHangLocalService.class)
	protected com.minimart.portlet.banhang.service.TrangThaiDonHangLocalService trangThaiDonHangLocalService;
	@BeanReference(type = com.minimart.portlet.banhang.service.TrangThaiDonHangService.class)
	protected com.minimart.portlet.banhang.service.TrangThaiDonHangService trangThaiDonHangService;
	@BeanReference(type = TrangThaiDonHangPersistence.class)
	protected TrangThaiDonHangPersistence trangThaiDonHangPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private DonHangChiTietServiceClpInvoker _clpInvoker = new DonHangChiTietServiceClpInvoker();
}