/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.nhacungcap.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.minimart.portlet.nhacungcap.model.NhaCungCap;
import com.minimart.portlet.nhacungcap.service.NhaCungCapService;
import com.minimart.portlet.nhacungcap.service.persistence.NhaCungCapPersistence;
import com.minimart.portlet.nhacungcap.service.persistence.NhomNhaCungCapPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the nha cung cap remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.minimart.portlet.nhacungcap.service.impl.NhaCungCapServiceImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see com.minimart.portlet.nhacungcap.service.impl.NhaCungCapServiceImpl
 * @see com.minimart.portlet.nhacungcap.service.NhaCungCapServiceUtil
 * @generated
 */
public abstract class NhaCungCapServiceBaseImpl extends BaseServiceImpl
	implements NhaCungCapService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.minimart.portlet.nhacungcap.service.NhaCungCapServiceUtil} to access the nha cung cap remote service.
	 */

	/**
	 * Returns the nha cung cap local service.
	 *
	 * @return the nha cung cap local service
	 */
	public com.minimart.portlet.nhacungcap.service.NhaCungCapLocalService getNhaCungCapLocalService() {
		return nhaCungCapLocalService;
	}

	/**
	 * Sets the nha cung cap local service.
	 *
	 * @param nhaCungCapLocalService the nha cung cap local service
	 */
	public void setNhaCungCapLocalService(
		com.minimart.portlet.nhacungcap.service.NhaCungCapLocalService nhaCungCapLocalService) {
		this.nhaCungCapLocalService = nhaCungCapLocalService;
	}

	/**
	 * Returns the nha cung cap remote service.
	 *
	 * @return the nha cung cap remote service
	 */
	public com.minimart.portlet.nhacungcap.service.NhaCungCapService getNhaCungCapService() {
		return nhaCungCapService;
	}

	/**
	 * Sets the nha cung cap remote service.
	 *
	 * @param nhaCungCapService the nha cung cap remote service
	 */
	public void setNhaCungCapService(
		com.minimart.portlet.nhacungcap.service.NhaCungCapService nhaCungCapService) {
		this.nhaCungCapService = nhaCungCapService;
	}

	/**
	 * Returns the nha cung cap persistence.
	 *
	 * @return the nha cung cap persistence
	 */
	public NhaCungCapPersistence getNhaCungCapPersistence() {
		return nhaCungCapPersistence;
	}

	/**
	 * Sets the nha cung cap persistence.
	 *
	 * @param nhaCungCapPersistence the nha cung cap persistence
	 */
	public void setNhaCungCapPersistence(
		NhaCungCapPersistence nhaCungCapPersistence) {
		this.nhaCungCapPersistence = nhaCungCapPersistence;
	}

	/**
	 * Returns the nhom nha cung cap local service.
	 *
	 * @return the nhom nha cung cap local service
	 */
	public com.minimart.portlet.nhacungcap.service.NhomNhaCungCapLocalService getNhomNhaCungCapLocalService() {
		return nhomNhaCungCapLocalService;
	}

	/**
	 * Sets the nhom nha cung cap local service.
	 *
	 * @param nhomNhaCungCapLocalService the nhom nha cung cap local service
	 */
	public void setNhomNhaCungCapLocalService(
		com.minimart.portlet.nhacungcap.service.NhomNhaCungCapLocalService nhomNhaCungCapLocalService) {
		this.nhomNhaCungCapLocalService = nhomNhaCungCapLocalService;
	}

	/**
	 * Returns the nhom nha cung cap remote service.
	 *
	 * @return the nhom nha cung cap remote service
	 */
	public com.minimart.portlet.nhacungcap.service.NhomNhaCungCapService getNhomNhaCungCapService() {
		return nhomNhaCungCapService;
	}

	/**
	 * Sets the nhom nha cung cap remote service.
	 *
	 * @param nhomNhaCungCapService the nhom nha cung cap remote service
	 */
	public void setNhomNhaCungCapService(
		com.minimart.portlet.nhacungcap.service.NhomNhaCungCapService nhomNhaCungCapService) {
		this.nhomNhaCungCapService = nhomNhaCungCapService;
	}

	/**
	 * Returns the nhom nha cung cap persistence.
	 *
	 * @return the nhom nha cung cap persistence
	 */
	public NhomNhaCungCapPersistence getNhomNhaCungCapPersistence() {
		return nhomNhaCungCapPersistence;
	}

	/**
	 * Sets the nhom nha cung cap persistence.
	 *
	 * @param nhomNhaCungCapPersistence the nhom nha cung cap persistence
	 */
	public void setNhomNhaCungCapPersistence(
		NhomNhaCungCapPersistence nhomNhaCungCapPersistence) {
		this.nhomNhaCungCapPersistence = nhomNhaCungCapPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return NhaCungCap.class;
	}

	protected String getModelClassName() {
		return NhaCungCap.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = nhaCungCapPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.minimart.portlet.nhacungcap.service.NhaCungCapLocalService.class)
	protected com.minimart.portlet.nhacungcap.service.NhaCungCapLocalService nhaCungCapLocalService;
	@BeanReference(type = com.minimart.portlet.nhacungcap.service.NhaCungCapService.class)
	protected com.minimart.portlet.nhacungcap.service.NhaCungCapService nhaCungCapService;
	@BeanReference(type = NhaCungCapPersistence.class)
	protected NhaCungCapPersistence nhaCungCapPersistence;
	@BeanReference(type = com.minimart.portlet.nhacungcap.service.NhomNhaCungCapLocalService.class)
	protected com.minimart.portlet.nhacungcap.service.NhomNhaCungCapLocalService nhomNhaCungCapLocalService;
	@BeanReference(type = com.minimart.portlet.nhacungcap.service.NhomNhaCungCapService.class)
	protected com.minimart.portlet.nhacungcap.service.NhomNhaCungCapService nhomNhaCungCapService;
	@BeanReference(type = NhomNhaCungCapPersistence.class)
	protected NhomNhaCungCapPersistence nhomNhaCungCapPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private NhaCungCapServiceClpInvoker _clpInvoker = new NhaCungCapServiceClpInvoker();
}