/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khachhang.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.minimart.portlet.khachhang.model.KhachHang;
import com.minimart.portlet.khachhang.service.KhachHangService;
import com.minimart.portlet.khachhang.service.persistence.KhachHangPersistence;
import com.minimart.portlet.khachhang.service.persistence.NhomKhachHangPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the khach hang remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.minimart.portlet.khachhang.service.impl.KhachHangServiceImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see com.minimart.portlet.khachhang.service.impl.KhachHangServiceImpl
 * @see com.minimart.portlet.khachhang.service.KhachHangServiceUtil
 * @generated
 */
public abstract class KhachHangServiceBaseImpl extends BaseServiceImpl
	implements KhachHangService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.minimart.portlet.khachhang.service.KhachHangServiceUtil} to access the khach hang remote service.
	 */

	/**
	 * Returns the khach hang local service.
	 *
	 * @return the khach hang local service
	 */
	public com.minimart.portlet.khachhang.service.KhachHangLocalService getKhachHangLocalService() {
		return khachHangLocalService;
	}

	/**
	 * Sets the khach hang local service.
	 *
	 * @param khachHangLocalService the khach hang local service
	 */
	public void setKhachHangLocalService(
		com.minimart.portlet.khachhang.service.KhachHangLocalService khachHangLocalService) {
		this.khachHangLocalService = khachHangLocalService;
	}

	/**
	 * Returns the khach hang remote service.
	 *
	 * @return the khach hang remote service
	 */
	public com.minimart.portlet.khachhang.service.KhachHangService getKhachHangService() {
		return khachHangService;
	}

	/**
	 * Sets the khach hang remote service.
	 *
	 * @param khachHangService the khach hang remote service
	 */
	public void setKhachHangService(
		com.minimart.portlet.khachhang.service.KhachHangService khachHangService) {
		this.khachHangService = khachHangService;
	}

	/**
	 * Returns the khach hang persistence.
	 *
	 * @return the khach hang persistence
	 */
	public KhachHangPersistence getKhachHangPersistence() {
		return khachHangPersistence;
	}

	/**
	 * Sets the khach hang persistence.
	 *
	 * @param khachHangPersistence the khach hang persistence
	 */
	public void setKhachHangPersistence(
		KhachHangPersistence khachHangPersistence) {
		this.khachHangPersistence = khachHangPersistence;
	}

	/**
	 * Returns the nhom khach hang local service.
	 *
	 * @return the nhom khach hang local service
	 */
	public com.minimart.portlet.khachhang.service.NhomKhachHangLocalService getNhomKhachHangLocalService() {
		return nhomKhachHangLocalService;
	}

	/**
	 * Sets the nhom khach hang local service.
	 *
	 * @param nhomKhachHangLocalService the nhom khach hang local service
	 */
	public void setNhomKhachHangLocalService(
		com.minimart.portlet.khachhang.service.NhomKhachHangLocalService nhomKhachHangLocalService) {
		this.nhomKhachHangLocalService = nhomKhachHangLocalService;
	}

	/**
	 * Returns the nhom khach hang remote service.
	 *
	 * @return the nhom khach hang remote service
	 */
	public com.minimart.portlet.khachhang.service.NhomKhachHangService getNhomKhachHangService() {
		return nhomKhachHangService;
	}

	/**
	 * Sets the nhom khach hang remote service.
	 *
	 * @param nhomKhachHangService the nhom khach hang remote service
	 */
	public void setNhomKhachHangService(
		com.minimart.portlet.khachhang.service.NhomKhachHangService nhomKhachHangService) {
		this.nhomKhachHangService = nhomKhachHangService;
	}

	/**
	 * Returns the nhom khach hang persistence.
	 *
	 * @return the nhom khach hang persistence
	 */
	public NhomKhachHangPersistence getNhomKhachHangPersistence() {
		return nhomKhachHangPersistence;
	}

	/**
	 * Sets the nhom khach hang persistence.
	 *
	 * @param nhomKhachHangPersistence the nhom khach hang persistence
	 */
	public void setNhomKhachHangPersistence(
		NhomKhachHangPersistence nhomKhachHangPersistence) {
		this.nhomKhachHangPersistence = nhomKhachHangPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return KhachHang.class;
	}

	protected String getModelClassName() {
		return KhachHang.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = khachHangPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.minimart.portlet.khachhang.service.KhachHangLocalService.class)
	protected com.minimart.portlet.khachhang.service.KhachHangLocalService khachHangLocalService;
	@BeanReference(type = com.minimart.portlet.khachhang.service.KhachHangService.class)
	protected com.minimart.portlet.khachhang.service.KhachHangService khachHangService;
	@BeanReference(type = KhachHangPersistence.class)
	protected KhachHangPersistence khachHangPersistence;
	@BeanReference(type = com.minimart.portlet.khachhang.service.NhomKhachHangLocalService.class)
	protected com.minimart.portlet.khachhang.service.NhomKhachHangLocalService nhomKhachHangLocalService;
	@BeanReference(type = com.minimart.portlet.khachhang.service.NhomKhachHangService.class)
	protected com.minimart.portlet.khachhang.service.NhomKhachHangService nhomKhachHangService;
	@BeanReference(type = NhomKhachHangPersistence.class)
	protected NhomKhachHangPersistence nhomKhachHangPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private KhachHangServiceClpInvoker _clpInvoker = new KhachHangServiceClpInvoker();
}