/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khuyenmai.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.khuyenmai.model.DotKhuyenMai;
import com.minimart.portlet.khuyenmai.model.DotKhuyenMaiModel;
import com.minimart.portlet.khuyenmai.model.DotKhuyenMaiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DotKhuyenMai service. Represents a row in the &quot;minimart_dotkhuyenmai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.khuyenmai.model.DotKhuyenMaiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DotKhuyenMaiImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DotKhuyenMaiImpl
 * @see com.minimart.portlet.khuyenmai.model.DotKhuyenMai
 * @see com.minimart.portlet.khuyenmai.model.DotKhuyenMaiModel
 * @generated
 */
@JSON(strict = true)
public class DotKhuyenMaiModelImpl extends BaseModelImpl<DotKhuyenMai>
	implements DotKhuyenMaiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dot khuyen mai model instance should use the {@link com.minimart.portlet.khuyenmai.model.DotKhuyenMai} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_dotkhuyenmai";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dotKhuyenMaiId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "trangThai", Types.BOOLEAN },
			{ "userModifieldId", Types.BIGINT },
			{ "ngayBatDau", Types.TIMESTAMP },
			{ "ngayHetHan", Types.TIMESTAMP },
			{ "ngungApDung", Types.BOOLEAN },
			{ "tiLeGiaGia", Types.INTEGER },
			{ "ghiChu", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_dotkhuyenmai (dotKhuyenMaiId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,trangThai BOOLEAN,userModifieldId LONG,ngayBatDau DATE null,ngayHetHan DATE null,ngungApDung BOOLEAN,tiLeGiaGia INTEGER,ghiChu VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_dotkhuyenmai";
	public static final String ORDER_BY_JPQL = " ORDER BY dotKhuyenMai.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_dotkhuyenmai.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.khuyenmai.model.DotKhuyenMai"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.khuyenmai.model.DotKhuyenMai"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.khuyenmai.model.DotKhuyenMai"),
			true);
	public static long NGAYBATDAU_COLUMN_BITMASK = 1L;
	public static long NGAYHETHAN_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DotKhuyenMai toModel(DotKhuyenMaiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DotKhuyenMai model = new DotKhuyenMaiImpl();

		model.setDotKhuyenMaiId(soapModel.getDotKhuyenMaiId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setTrangThai(soapModel.getTrangThai());
		model.setUserModifieldId(soapModel.getUserModifieldId());
		model.setNgayBatDau(soapModel.getNgayBatDau());
		model.setNgayHetHan(soapModel.getNgayHetHan());
		model.setNgungApDung(soapModel.getNgungApDung());
		model.setTiLeGiaGia(soapModel.getTiLeGiaGia());
		model.setGhiChu(soapModel.getGhiChu());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DotKhuyenMai> toModels(DotKhuyenMaiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DotKhuyenMai> models = new ArrayList<DotKhuyenMai>(soapModels.length);

		for (DotKhuyenMaiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.khuyenmai.model.DotKhuyenMai"));

	public DotKhuyenMaiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dotKhuyenMaiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDotKhuyenMaiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dotKhuyenMaiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DotKhuyenMai.class;
	}

	@Override
	public String getModelClassName() {
		return DotKhuyenMai.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dotKhuyenMaiId", getDotKhuyenMaiId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("trangThai", getTrangThai());
		attributes.put("userModifieldId", getUserModifieldId());
		attributes.put("ngayBatDau", getNgayBatDau());
		attributes.put("ngayHetHan", getNgayHetHan());
		attributes.put("ngungApDung", getNgungApDung());
		attributes.put("tiLeGiaGia", getTiLeGiaGia());
		attributes.put("ghiChu", getGhiChu());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dotKhuyenMaiId = (Long)attributes.get("dotKhuyenMaiId");

		if (dotKhuyenMaiId != null) {
			setDotKhuyenMaiId(dotKhuyenMaiId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		Boolean trangThai = (Boolean)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Long userModifieldId = (Long)attributes.get("userModifieldId");

		if (userModifieldId != null) {
			setUserModifieldId(userModifieldId);
		}

		Date ngayBatDau = (Date)attributes.get("ngayBatDau");

		if (ngayBatDau != null) {
			setNgayBatDau(ngayBatDau);
		}

		Date ngayHetHan = (Date)attributes.get("ngayHetHan");

		if (ngayHetHan != null) {
			setNgayHetHan(ngayHetHan);
		}

		Boolean ngungApDung = (Boolean)attributes.get("ngungApDung");

		if (ngungApDung != null) {
			setNgungApDung(ngungApDung);
		}

		Integer tiLeGiaGia = (Integer)attributes.get("tiLeGiaGia");

		if (tiLeGiaGia != null) {
			setTiLeGiaGia(tiLeGiaGia);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}
	}

	@JSON
	@Override
	public long getDotKhuyenMaiId() {
		return _dotKhuyenMaiId;
	}

	@Override
	public void setDotKhuyenMaiId(long dotKhuyenMaiId) {
		_dotKhuyenMaiId = dotKhuyenMaiId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public boolean getTrangThai() {
		return _trangThai;
	}

	@Override
	public boolean isTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(boolean trangThai) {
		_trangThai = trangThai;
	}

	@JSON
	@Override
	public long getUserModifieldId() {
		return _userModifieldId;
	}

	@Override
	public void setUserModifieldId(long userModifieldId) {
		_userModifieldId = userModifieldId;
	}

	@JSON
	@Override
	public Date getNgayBatDau() {
		return _ngayBatDau;
	}

	@Override
	public void setNgayBatDau(Date ngayBatDau) {
		_columnBitmask |= NGAYBATDAU_COLUMN_BITMASK;

		if (_originalNgayBatDau == null) {
			_originalNgayBatDau = _ngayBatDau;
		}

		_ngayBatDau = ngayBatDau;
	}

	public Date getOriginalNgayBatDau() {
		return _originalNgayBatDau;
	}

	@JSON
	@Override
	public Date getNgayHetHan() {
		return _ngayHetHan;
	}

	@Override
	public void setNgayHetHan(Date ngayHetHan) {
		_columnBitmask |= NGAYHETHAN_COLUMN_BITMASK;

		if (_originalNgayHetHan == null) {
			_originalNgayHetHan = _ngayHetHan;
		}

		_ngayHetHan = ngayHetHan;
	}

	public Date getOriginalNgayHetHan() {
		return _originalNgayHetHan;
	}

	@JSON
	@Override
	public boolean getNgungApDung() {
		return _ngungApDung;
	}

	@Override
	public boolean isNgungApDung() {
		return _ngungApDung;
	}

	@Override
	public void setNgungApDung(boolean ngungApDung) {
		_ngungApDung = ngungApDung;
	}

	@JSON
	@Override
	public int getTiLeGiaGia() {
		return _tiLeGiaGia;
	}

	@Override
	public void setTiLeGiaGia(int tiLeGiaGia) {
		_tiLeGiaGia = tiLeGiaGia;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DotKhuyenMai.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DotKhuyenMai toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DotKhuyenMai)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DotKhuyenMaiImpl dotKhuyenMaiImpl = new DotKhuyenMaiImpl();

		dotKhuyenMaiImpl.setDotKhuyenMaiId(getDotKhuyenMaiId());
		dotKhuyenMaiImpl.setCompanyId(getCompanyId());
		dotKhuyenMaiImpl.setUserId(getUserId());
		dotKhuyenMaiImpl.setUserName(getUserName());
		dotKhuyenMaiImpl.setCreateDate(getCreateDate());
		dotKhuyenMaiImpl.setModifiedDate(getModifiedDate());
		dotKhuyenMaiImpl.setTen(getTen());
		dotKhuyenMaiImpl.setTrangThai(getTrangThai());
		dotKhuyenMaiImpl.setUserModifieldId(getUserModifieldId());
		dotKhuyenMaiImpl.setNgayBatDau(getNgayBatDau());
		dotKhuyenMaiImpl.setNgayHetHan(getNgayHetHan());
		dotKhuyenMaiImpl.setNgungApDung(getNgungApDung());
		dotKhuyenMaiImpl.setTiLeGiaGia(getTiLeGiaGia());
		dotKhuyenMaiImpl.setGhiChu(getGhiChu());

		dotKhuyenMaiImpl.resetOriginalValues();

		return dotKhuyenMaiImpl;
	}

	@Override
	public int compareTo(DotKhuyenMai dotKhuyenMai) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), dotKhuyenMai.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DotKhuyenMai)) {
			return false;
		}

		DotKhuyenMai dotKhuyenMai = (DotKhuyenMai)obj;

		long primaryKey = dotKhuyenMai.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DotKhuyenMaiModelImpl dotKhuyenMaiModelImpl = this;

		dotKhuyenMaiModelImpl._originalTen = dotKhuyenMaiModelImpl._ten;

		dotKhuyenMaiModelImpl._originalNgayBatDau = dotKhuyenMaiModelImpl._ngayBatDau;

		dotKhuyenMaiModelImpl._originalNgayHetHan = dotKhuyenMaiModelImpl._ngayHetHan;

		dotKhuyenMaiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DotKhuyenMai> toCacheModel() {
		DotKhuyenMaiCacheModel dotKhuyenMaiCacheModel = new DotKhuyenMaiCacheModel();

		dotKhuyenMaiCacheModel.dotKhuyenMaiId = getDotKhuyenMaiId();

		dotKhuyenMaiCacheModel.companyId = getCompanyId();

		dotKhuyenMaiCacheModel.userId = getUserId();

		dotKhuyenMaiCacheModel.userName = getUserName();

		String userName = dotKhuyenMaiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dotKhuyenMaiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dotKhuyenMaiCacheModel.createDate = createDate.getTime();
		}
		else {
			dotKhuyenMaiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dotKhuyenMaiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dotKhuyenMaiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dotKhuyenMaiCacheModel.ten = getTen();

		String ten = dotKhuyenMaiCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			dotKhuyenMaiCacheModel.ten = null;
		}

		dotKhuyenMaiCacheModel.trangThai = getTrangThai();

		dotKhuyenMaiCacheModel.userModifieldId = getUserModifieldId();

		Date ngayBatDau = getNgayBatDau();

		if (ngayBatDau != null) {
			dotKhuyenMaiCacheModel.ngayBatDau = ngayBatDau.getTime();
		}
		else {
			dotKhuyenMaiCacheModel.ngayBatDau = Long.MIN_VALUE;
		}

		Date ngayHetHan = getNgayHetHan();

		if (ngayHetHan != null) {
			dotKhuyenMaiCacheModel.ngayHetHan = ngayHetHan.getTime();
		}
		else {
			dotKhuyenMaiCacheModel.ngayHetHan = Long.MIN_VALUE;
		}

		dotKhuyenMaiCacheModel.ngungApDung = getNgungApDung();

		dotKhuyenMaiCacheModel.tiLeGiaGia = getTiLeGiaGia();

		dotKhuyenMaiCacheModel.ghiChu = getGhiChu();

		String ghiChu = dotKhuyenMaiCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			dotKhuyenMaiCacheModel.ghiChu = null;
		}

		return dotKhuyenMaiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{dotKhuyenMaiId=");
		sb.append(getDotKhuyenMaiId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", userModifieldId=");
		sb.append(getUserModifieldId());
		sb.append(", ngayBatDau=");
		sb.append(getNgayBatDau());
		sb.append(", ngayHetHan=");
		sb.append(getNgayHetHan());
		sb.append(", ngungApDung=");
		sb.append(getNgungApDung());
		sb.append(", tiLeGiaGia=");
		sb.append(getTiLeGiaGia());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.khuyenmai.model.DotKhuyenMai");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dotKhuyenMaiId</column-name><column-value><![CDATA[");
		sb.append(getDotKhuyenMaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userModifieldId</column-name><column-value><![CDATA[");
		sb.append(getUserModifieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayBatDau</column-name><column-value><![CDATA[");
		sb.append(getNgayBatDau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHan</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngungApDung</column-name><column-value><![CDATA[");
		sb.append(getNgungApDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeGiaGia</column-name><column-value><![CDATA[");
		sb.append(getTiLeGiaGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DotKhuyenMai.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DotKhuyenMai.class
		};
	private long _dotKhuyenMaiId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private boolean _trangThai;
	private long _userModifieldId;
	private Date _ngayBatDau;
	private Date _originalNgayBatDau;
	private Date _ngayHetHan;
	private Date _originalNgayHetHan;
	private boolean _ngungApDung;
	private int _tiLeGiaGia;
	private String _ghiChu;
	private long _columnBitmask;
	private DotKhuyenMai _escapedModel;
}