/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khuyenmai.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet;
import com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTietModel;
import com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTietSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DotKhuyenMaiChiTiet service. Represents a row in the &quot;minimart_dotkhuyenmaichitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTietModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DotKhuyenMaiChiTietImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DotKhuyenMaiChiTietImpl
 * @see com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet
 * @see com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTietModel
 * @generated
 */
@JSON(strict = true)
public class DotKhuyenMaiChiTietModelImpl extends BaseModelImpl<DotKhuyenMaiChiTiet>
	implements DotKhuyenMaiChiTietModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dot khuyen mai chi tiet model instance should use the {@link com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_dotkhuyenmaichitiet";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dotKhuyenMaiChiTietId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "dotKhuyenMaiId", Types.BIGINT },
			{ "nhomMatHangId", Types.BIGINT },
			{ "matHangId", Types.BIGINT },
			{ "matHangTangId", Types.BIGINT },
			{ "tiLeGiamGia", Types.DOUBLE },
			{ "giaTriDonHang", Types.DOUBLE },
			{ "soLuongMua", Types.INTEGER },
			{ "soLuongTang", Types.INTEGER },
			{ "giaBan", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_dotkhuyenmaichitiet (dotKhuyenMaiChiTietId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,dotKhuyenMaiId LONG,nhomMatHangId LONG,matHangId LONG,matHangTangId LONG,tiLeGiamGia DOUBLE,giaTriDonHang DOUBLE,soLuongMua INTEGER,soLuongTang INTEGER,giaBan INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table minimart_dotkhuyenmaichitiet";
	public static final String ORDER_BY_JPQL = " ORDER BY dotKhuyenMaiChiTiet.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_dotkhuyenmaichitiet.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet"),
			true);
	public static long DOTKHUYENMAIID_COLUMN_BITMASK = 1L;
	public static long MATHANGID_COLUMN_BITMASK = 2L;
	public static long NHOMMATHANGID_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DotKhuyenMaiChiTiet toModel(DotKhuyenMaiChiTietSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DotKhuyenMaiChiTiet model = new DotKhuyenMaiChiTietImpl();

		model.setDotKhuyenMaiChiTietId(soapModel.getDotKhuyenMaiChiTietId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDotKhuyenMaiId(soapModel.getDotKhuyenMaiId());
		model.setNhomMatHangId(soapModel.getNhomMatHangId());
		model.setMatHangId(soapModel.getMatHangId());
		model.setMatHangTangId(soapModel.getMatHangTangId());
		model.setTiLeGiamGia(soapModel.getTiLeGiamGia());
		model.setGiaTriDonHang(soapModel.getGiaTriDonHang());
		model.setSoLuongMua(soapModel.getSoLuongMua());
		model.setSoLuongTang(soapModel.getSoLuongTang());
		model.setGiaBan(soapModel.getGiaBan());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DotKhuyenMaiChiTiet> toModels(
		DotKhuyenMaiChiTietSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DotKhuyenMaiChiTiet> models = new ArrayList<DotKhuyenMaiChiTiet>(soapModels.length);

		for (DotKhuyenMaiChiTietSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet"));

	public DotKhuyenMaiChiTietModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dotKhuyenMaiChiTietId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDotKhuyenMaiChiTietId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dotKhuyenMaiChiTietId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DotKhuyenMaiChiTiet.class;
	}

	@Override
	public String getModelClassName() {
		return DotKhuyenMaiChiTiet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dotKhuyenMaiChiTietId", getDotKhuyenMaiChiTietId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("dotKhuyenMaiId", getDotKhuyenMaiId());
		attributes.put("nhomMatHangId", getNhomMatHangId());
		attributes.put("matHangId", getMatHangId());
		attributes.put("matHangTangId", getMatHangTangId());
		attributes.put("tiLeGiamGia", getTiLeGiamGia());
		attributes.put("giaTriDonHang", getGiaTriDonHang());
		attributes.put("soLuongMua", getSoLuongMua());
		attributes.put("soLuongTang", getSoLuongTang());
		attributes.put("giaBan", getGiaBan());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dotKhuyenMaiChiTietId = (Long)attributes.get(
				"dotKhuyenMaiChiTietId");

		if (dotKhuyenMaiChiTietId != null) {
			setDotKhuyenMaiChiTietId(dotKhuyenMaiChiTietId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long dotKhuyenMaiId = (Long)attributes.get("dotKhuyenMaiId");

		if (dotKhuyenMaiId != null) {
			setDotKhuyenMaiId(dotKhuyenMaiId);
		}

		Long nhomMatHangId = (Long)attributes.get("nhomMatHangId");

		if (nhomMatHangId != null) {
			setNhomMatHangId(nhomMatHangId);
		}

		Long matHangId = (Long)attributes.get("matHangId");

		if (matHangId != null) {
			setMatHangId(matHangId);
		}

		Long matHangTangId = (Long)attributes.get("matHangTangId");

		if (matHangTangId != null) {
			setMatHangTangId(matHangTangId);
		}

		Double tiLeGiamGia = (Double)attributes.get("tiLeGiamGia");

		if (tiLeGiamGia != null) {
			setTiLeGiamGia(tiLeGiamGia);
		}

		Double giaTriDonHang = (Double)attributes.get("giaTriDonHang");

		if (giaTriDonHang != null) {
			setGiaTriDonHang(giaTriDonHang);
		}

		Integer soLuongMua = (Integer)attributes.get("soLuongMua");

		if (soLuongMua != null) {
			setSoLuongMua(soLuongMua);
		}

		Integer soLuongTang = (Integer)attributes.get("soLuongTang");

		if (soLuongTang != null) {
			setSoLuongTang(soLuongTang);
		}

		Integer giaBan = (Integer)attributes.get("giaBan");

		if (giaBan != null) {
			setGiaBan(giaBan);
		}
	}

	@JSON
	@Override
	public long getDotKhuyenMaiChiTietId() {
		return _dotKhuyenMaiChiTietId;
	}

	@Override
	public void setDotKhuyenMaiChiTietId(long dotKhuyenMaiChiTietId) {
		_dotKhuyenMaiChiTietId = dotKhuyenMaiChiTietId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDotKhuyenMaiId() {
		return _dotKhuyenMaiId;
	}

	@Override
	public void setDotKhuyenMaiId(long dotKhuyenMaiId) {
		_columnBitmask |= DOTKHUYENMAIID_COLUMN_BITMASK;

		if (!_setOriginalDotKhuyenMaiId) {
			_setOriginalDotKhuyenMaiId = true;

			_originalDotKhuyenMaiId = _dotKhuyenMaiId;
		}

		_dotKhuyenMaiId = dotKhuyenMaiId;
	}

	public long getOriginalDotKhuyenMaiId() {
		return _originalDotKhuyenMaiId;
	}

	@JSON
	@Override
	public long getNhomMatHangId() {
		return _nhomMatHangId;
	}

	@Override
	public void setNhomMatHangId(long nhomMatHangId) {
		_columnBitmask |= NHOMMATHANGID_COLUMN_BITMASK;

		if (!_setOriginalNhomMatHangId) {
			_setOriginalNhomMatHangId = true;

			_originalNhomMatHangId = _nhomMatHangId;
		}

		_nhomMatHangId = nhomMatHangId;
	}

	public long getOriginalNhomMatHangId() {
		return _originalNhomMatHangId;
	}

	@JSON
	@Override
	public long getMatHangId() {
		return _matHangId;
	}

	@Override
	public void setMatHangId(long matHangId) {
		_columnBitmask |= MATHANGID_COLUMN_BITMASK;

		if (!_setOriginalMatHangId) {
			_setOriginalMatHangId = true;

			_originalMatHangId = _matHangId;
		}

		_matHangId = matHangId;
	}

	public long getOriginalMatHangId() {
		return _originalMatHangId;
	}

	@JSON
	@Override
	public long getMatHangTangId() {
		return _matHangTangId;
	}

	@Override
	public void setMatHangTangId(long matHangTangId) {
		_matHangTangId = matHangTangId;
	}

	@JSON
	@Override
	public double getTiLeGiamGia() {
		return _tiLeGiamGia;
	}

	@Override
	public void setTiLeGiamGia(double tiLeGiamGia) {
		_tiLeGiamGia = tiLeGiamGia;
	}

	@JSON
	@Override
	public double getGiaTriDonHang() {
		return _giaTriDonHang;
	}

	@Override
	public void setGiaTriDonHang(double giaTriDonHang) {
		_giaTriDonHang = giaTriDonHang;
	}

	@JSON
	@Override
	public int getSoLuongMua() {
		return _soLuongMua;
	}

	@Override
	public void setSoLuongMua(int soLuongMua) {
		_soLuongMua = soLuongMua;
	}

	@JSON
	@Override
	public int getSoLuongTang() {
		return _soLuongTang;
	}

	@Override
	public void setSoLuongTang(int soLuongTang) {
		_soLuongTang = soLuongTang;
	}

	@JSON
	@Override
	public int getGiaBan() {
		return _giaBan;
	}

	@Override
	public void setGiaBan(int giaBan) {
		_giaBan = giaBan;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DotKhuyenMaiChiTiet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DotKhuyenMaiChiTiet toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DotKhuyenMaiChiTiet)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DotKhuyenMaiChiTietImpl dotKhuyenMaiChiTietImpl = new DotKhuyenMaiChiTietImpl();

		dotKhuyenMaiChiTietImpl.setDotKhuyenMaiChiTietId(getDotKhuyenMaiChiTietId());
		dotKhuyenMaiChiTietImpl.setCompanyId(getCompanyId());
		dotKhuyenMaiChiTietImpl.setUserId(getUserId());
		dotKhuyenMaiChiTietImpl.setUserName(getUserName());
		dotKhuyenMaiChiTietImpl.setCreateDate(getCreateDate());
		dotKhuyenMaiChiTietImpl.setModifiedDate(getModifiedDate());
		dotKhuyenMaiChiTietImpl.setDotKhuyenMaiId(getDotKhuyenMaiId());
		dotKhuyenMaiChiTietImpl.setNhomMatHangId(getNhomMatHangId());
		dotKhuyenMaiChiTietImpl.setMatHangId(getMatHangId());
		dotKhuyenMaiChiTietImpl.setMatHangTangId(getMatHangTangId());
		dotKhuyenMaiChiTietImpl.setTiLeGiamGia(getTiLeGiamGia());
		dotKhuyenMaiChiTietImpl.setGiaTriDonHang(getGiaTriDonHang());
		dotKhuyenMaiChiTietImpl.setSoLuongMua(getSoLuongMua());
		dotKhuyenMaiChiTietImpl.setSoLuongTang(getSoLuongTang());
		dotKhuyenMaiChiTietImpl.setGiaBan(getGiaBan());

		dotKhuyenMaiChiTietImpl.resetOriginalValues();

		return dotKhuyenMaiChiTietImpl;
	}

	@Override
	public int compareTo(DotKhuyenMaiChiTiet dotKhuyenMaiChiTiet) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				dotKhuyenMaiChiTiet.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DotKhuyenMaiChiTiet)) {
			return false;
		}

		DotKhuyenMaiChiTiet dotKhuyenMaiChiTiet = (DotKhuyenMaiChiTiet)obj;

		long primaryKey = dotKhuyenMaiChiTiet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DotKhuyenMaiChiTietModelImpl dotKhuyenMaiChiTietModelImpl = this;

		dotKhuyenMaiChiTietModelImpl._originalDotKhuyenMaiId = dotKhuyenMaiChiTietModelImpl._dotKhuyenMaiId;

		dotKhuyenMaiChiTietModelImpl._setOriginalDotKhuyenMaiId = false;

		dotKhuyenMaiChiTietModelImpl._originalNhomMatHangId = dotKhuyenMaiChiTietModelImpl._nhomMatHangId;

		dotKhuyenMaiChiTietModelImpl._setOriginalNhomMatHangId = false;

		dotKhuyenMaiChiTietModelImpl._originalMatHangId = dotKhuyenMaiChiTietModelImpl._matHangId;

		dotKhuyenMaiChiTietModelImpl._setOriginalMatHangId = false;

		dotKhuyenMaiChiTietModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DotKhuyenMaiChiTiet> toCacheModel() {
		DotKhuyenMaiChiTietCacheModel dotKhuyenMaiChiTietCacheModel = new DotKhuyenMaiChiTietCacheModel();

		dotKhuyenMaiChiTietCacheModel.dotKhuyenMaiChiTietId = getDotKhuyenMaiChiTietId();

		dotKhuyenMaiChiTietCacheModel.companyId = getCompanyId();

		dotKhuyenMaiChiTietCacheModel.userId = getUserId();

		dotKhuyenMaiChiTietCacheModel.userName = getUserName();

		String userName = dotKhuyenMaiChiTietCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dotKhuyenMaiChiTietCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dotKhuyenMaiChiTietCacheModel.createDate = createDate.getTime();
		}
		else {
			dotKhuyenMaiChiTietCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dotKhuyenMaiChiTietCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dotKhuyenMaiChiTietCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dotKhuyenMaiChiTietCacheModel.dotKhuyenMaiId = getDotKhuyenMaiId();

		dotKhuyenMaiChiTietCacheModel.nhomMatHangId = getNhomMatHangId();

		dotKhuyenMaiChiTietCacheModel.matHangId = getMatHangId();

		dotKhuyenMaiChiTietCacheModel.matHangTangId = getMatHangTangId();

		dotKhuyenMaiChiTietCacheModel.tiLeGiamGia = getTiLeGiamGia();

		dotKhuyenMaiChiTietCacheModel.giaTriDonHang = getGiaTriDonHang();

		dotKhuyenMaiChiTietCacheModel.soLuongMua = getSoLuongMua();

		dotKhuyenMaiChiTietCacheModel.soLuongTang = getSoLuongTang();

		dotKhuyenMaiChiTietCacheModel.giaBan = getGiaBan();

		return dotKhuyenMaiChiTietCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{dotKhuyenMaiChiTietId=");
		sb.append(getDotKhuyenMaiChiTietId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", dotKhuyenMaiId=");
		sb.append(getDotKhuyenMaiId());
		sb.append(", nhomMatHangId=");
		sb.append(getNhomMatHangId());
		sb.append(", matHangId=");
		sb.append(getMatHangId());
		sb.append(", matHangTangId=");
		sb.append(getMatHangTangId());
		sb.append(", tiLeGiamGia=");
		sb.append(getTiLeGiamGia());
		sb.append(", giaTriDonHang=");
		sb.append(getGiaTriDonHang());
		sb.append(", soLuongMua=");
		sb.append(getSoLuongMua());
		sb.append(", soLuongTang=");
		sb.append(getSoLuongTang());
		sb.append(", giaBan=");
		sb.append(getGiaBan());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.khuyenmai.model.DotKhuyenMaiChiTiet");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dotKhuyenMaiChiTietId</column-name><column-value><![CDATA[");
		sb.append(getDotKhuyenMaiChiTietId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dotKhuyenMaiId</column-name><column-value><![CDATA[");
		sb.append(getDotKhuyenMaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhomMatHangId</column-name><column-value><![CDATA[");
		sb.append(getNhomMatHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>matHangId</column-name><column-value><![CDATA[");
		sb.append(getMatHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>matHangTangId</column-name><column-value><![CDATA[");
		sb.append(getMatHangTangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeGiamGia</column-name><column-value><![CDATA[");
		sb.append(getTiLeGiamGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>giaTriDonHang</column-name><column-value><![CDATA[");
		sb.append(getGiaTriDonHang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLuongMua</column-name><column-value><![CDATA[");
		sb.append(getSoLuongMua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLuongTang</column-name><column-value><![CDATA[");
		sb.append(getSoLuongTang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>giaBan</column-name><column-value><![CDATA[");
		sb.append(getGiaBan());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DotKhuyenMaiChiTiet.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DotKhuyenMaiChiTiet.class
		};
	private long _dotKhuyenMaiChiTietId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _dotKhuyenMaiId;
	private long _originalDotKhuyenMaiId;
	private boolean _setOriginalDotKhuyenMaiId;
	private long _nhomMatHangId;
	private long _originalNhomMatHangId;
	private boolean _setOriginalNhomMatHangId;
	private long _matHangId;
	private long _originalMatHangId;
	private boolean _setOriginalMatHangId;
	private long _matHangTangId;
	private double _tiLeGiamGia;
	private double _giaTriDonHang;
	private int _soLuongMua;
	private int _soLuongTang;
	private int _giaBan;
	private long _columnBitmask;
	private DotKhuyenMaiChiTiet _escapedModel;
}