/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khuyenmai.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai;
import com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMaiModel;
import com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMaiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LoaiHinhKhuyenMai service. Represents a row in the &quot;minimart_loaihinhkhuyenmai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMaiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoaiHinhKhuyenMaiImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see LoaiHinhKhuyenMaiImpl
 * @see com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai
 * @see com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMaiModel
 * @generated
 */
@JSON(strict = true)
public class LoaiHinhKhuyenMaiModelImpl extends BaseModelImpl<LoaiHinhKhuyenMai>
	implements LoaiHinhKhuyenMaiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loai hinh khuyen mai model instance should use the {@link com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_loaihinhkhuyenmai";
	public static final Object[][] TABLE_COLUMNS = {
			{ "loaiHinhKhuyenMaiId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "trangThai", Types.BOOLEAN },
			{ "tileGiamGia", Types.INTEGER },
			{ "ngayBatDau", Types.TIMESTAMP },
			{ "ngayHetHan", Types.TIMESTAMP },
			{ "imageid", Types.VARCHAR },
			{ "ghiChu", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_loaihinhkhuyenmai (loaiHinhKhuyenMaiId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,trangThai BOOLEAN,tileGiamGia INTEGER,ngayBatDau DATE null,ngayHetHan DATE null,imageid VARCHAR(75) null,ghiChu VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table minimart_loaihinhkhuyenmai";
	public static final String ORDER_BY_JPQL = " ORDER BY loaiHinhKhuyenMai.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_loaihinhkhuyenmai.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai"),
			true);
	public static long TEN_COLUMN_BITMASK = 1L;
	public static long TRANGTHAI_COLUMN_BITMASK = 2L;
	public static long CREATEDATE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LoaiHinhKhuyenMai toModel(LoaiHinhKhuyenMaiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LoaiHinhKhuyenMai model = new LoaiHinhKhuyenMaiImpl();

		model.setLoaiHinhKhuyenMaiId(soapModel.getLoaiHinhKhuyenMaiId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setTrangThai(soapModel.getTrangThai());
		model.setTileGiamGia(soapModel.getTileGiamGia());
		model.setNgayBatDau(soapModel.getNgayBatDau());
		model.setNgayHetHan(soapModel.getNgayHetHan());
		model.setImageid(soapModel.getImageid());
		model.setGhiChu(soapModel.getGhiChu());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LoaiHinhKhuyenMai> toModels(
		LoaiHinhKhuyenMaiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LoaiHinhKhuyenMai> models = new ArrayList<LoaiHinhKhuyenMai>(soapModels.length);

		for (LoaiHinhKhuyenMaiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai"));

	public LoaiHinhKhuyenMaiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loaiHinhKhuyenMaiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoaiHinhKhuyenMaiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loaiHinhKhuyenMaiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoaiHinhKhuyenMai.class;
	}

	@Override
	public String getModelClassName() {
		return LoaiHinhKhuyenMai.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("loaiHinhKhuyenMaiId", getLoaiHinhKhuyenMaiId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("trangThai", getTrangThai());
		attributes.put("tileGiamGia", getTileGiamGia());
		attributes.put("ngayBatDau", getNgayBatDau());
		attributes.put("ngayHetHan", getNgayHetHan());
		attributes.put("imageid", getImageid());
		attributes.put("ghiChu", getGhiChu());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long loaiHinhKhuyenMaiId = (Long)attributes.get("loaiHinhKhuyenMaiId");

		if (loaiHinhKhuyenMaiId != null) {
			setLoaiHinhKhuyenMaiId(loaiHinhKhuyenMaiId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		Boolean trangThai = (Boolean)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Integer tileGiamGia = (Integer)attributes.get("tileGiamGia");

		if (tileGiamGia != null) {
			setTileGiamGia(tileGiamGia);
		}

		Date ngayBatDau = (Date)attributes.get("ngayBatDau");

		if (ngayBatDau != null) {
			setNgayBatDau(ngayBatDau);
		}

		Date ngayHetHan = (Date)attributes.get("ngayHetHan");

		if (ngayHetHan != null) {
			setNgayHetHan(ngayHetHan);
		}

		String imageid = (String)attributes.get("imageid");

		if (imageid != null) {
			setImageid(imageid);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}
	}

	@JSON
	@Override
	public long getLoaiHinhKhuyenMaiId() {
		return _loaiHinhKhuyenMaiId;
	}

	@Override
	public void setLoaiHinhKhuyenMaiId(long loaiHinhKhuyenMaiId) {
		_loaiHinhKhuyenMaiId = loaiHinhKhuyenMaiId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public boolean getTrangThai() {
		return _trangThai;
	}

	@Override
	public boolean isTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(boolean trangThai) {
		_columnBitmask |= TRANGTHAI_COLUMN_BITMASK;

		if (!_setOriginalTrangThai) {
			_setOriginalTrangThai = true;

			_originalTrangThai = _trangThai;
		}

		_trangThai = trangThai;
	}

	public boolean getOriginalTrangThai() {
		return _originalTrangThai;
	}

	@JSON
	@Override
	public int getTileGiamGia() {
		return _tileGiamGia;
	}

	@Override
	public void setTileGiamGia(int tileGiamGia) {
		_tileGiamGia = tileGiamGia;
	}

	@JSON
	@Override
	public Date getNgayBatDau() {
		return _ngayBatDau;
	}

	@Override
	public void setNgayBatDau(Date ngayBatDau) {
		_ngayBatDau = ngayBatDau;
	}

	@JSON
	@Override
	public Date getNgayHetHan() {
		return _ngayHetHan;
	}

	@Override
	public void setNgayHetHan(Date ngayHetHan) {
		_ngayHetHan = ngayHetHan;
	}

	@JSON
	@Override
	public String getImageid() {
		if (_imageid == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageid;
		}
	}

	@Override
	public void setImageid(String imageid) {
		_imageid = imageid;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LoaiHinhKhuyenMai.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoaiHinhKhuyenMai toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoaiHinhKhuyenMai)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoaiHinhKhuyenMaiImpl loaiHinhKhuyenMaiImpl = new LoaiHinhKhuyenMaiImpl();

		loaiHinhKhuyenMaiImpl.setLoaiHinhKhuyenMaiId(getLoaiHinhKhuyenMaiId());
		loaiHinhKhuyenMaiImpl.setCompanyId(getCompanyId());
		loaiHinhKhuyenMaiImpl.setUserId(getUserId());
		loaiHinhKhuyenMaiImpl.setUserName(getUserName());
		loaiHinhKhuyenMaiImpl.setCreateDate(getCreateDate());
		loaiHinhKhuyenMaiImpl.setModifiedDate(getModifiedDate());
		loaiHinhKhuyenMaiImpl.setTen(getTen());
		loaiHinhKhuyenMaiImpl.setTrangThai(getTrangThai());
		loaiHinhKhuyenMaiImpl.setTileGiamGia(getTileGiamGia());
		loaiHinhKhuyenMaiImpl.setNgayBatDau(getNgayBatDau());
		loaiHinhKhuyenMaiImpl.setNgayHetHan(getNgayHetHan());
		loaiHinhKhuyenMaiImpl.setImageid(getImageid());
		loaiHinhKhuyenMaiImpl.setGhiChu(getGhiChu());

		loaiHinhKhuyenMaiImpl.resetOriginalValues();

		return loaiHinhKhuyenMaiImpl;
	}

	@Override
	public int compareTo(LoaiHinhKhuyenMai loaiHinhKhuyenMai) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				loaiHinhKhuyenMai.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoaiHinhKhuyenMai)) {
			return false;
		}

		LoaiHinhKhuyenMai loaiHinhKhuyenMai = (LoaiHinhKhuyenMai)obj;

		long primaryKey = loaiHinhKhuyenMai.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LoaiHinhKhuyenMaiModelImpl loaiHinhKhuyenMaiModelImpl = this;

		loaiHinhKhuyenMaiModelImpl._originalTen = loaiHinhKhuyenMaiModelImpl._ten;

		loaiHinhKhuyenMaiModelImpl._originalTrangThai = loaiHinhKhuyenMaiModelImpl._trangThai;

		loaiHinhKhuyenMaiModelImpl._setOriginalTrangThai = false;

		loaiHinhKhuyenMaiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LoaiHinhKhuyenMai> toCacheModel() {
		LoaiHinhKhuyenMaiCacheModel loaiHinhKhuyenMaiCacheModel = new LoaiHinhKhuyenMaiCacheModel();

		loaiHinhKhuyenMaiCacheModel.loaiHinhKhuyenMaiId = getLoaiHinhKhuyenMaiId();

		loaiHinhKhuyenMaiCacheModel.companyId = getCompanyId();

		loaiHinhKhuyenMaiCacheModel.userId = getUserId();

		loaiHinhKhuyenMaiCacheModel.userName = getUserName();

		String userName = loaiHinhKhuyenMaiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loaiHinhKhuyenMaiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loaiHinhKhuyenMaiCacheModel.createDate = createDate.getTime();
		}
		else {
			loaiHinhKhuyenMaiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loaiHinhKhuyenMaiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loaiHinhKhuyenMaiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		loaiHinhKhuyenMaiCacheModel.ten = getTen();

		String ten = loaiHinhKhuyenMaiCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			loaiHinhKhuyenMaiCacheModel.ten = null;
		}

		loaiHinhKhuyenMaiCacheModel.trangThai = getTrangThai();

		loaiHinhKhuyenMaiCacheModel.tileGiamGia = getTileGiamGia();

		Date ngayBatDau = getNgayBatDau();

		if (ngayBatDau != null) {
			loaiHinhKhuyenMaiCacheModel.ngayBatDau = ngayBatDau.getTime();
		}
		else {
			loaiHinhKhuyenMaiCacheModel.ngayBatDau = Long.MIN_VALUE;
		}

		Date ngayHetHan = getNgayHetHan();

		if (ngayHetHan != null) {
			loaiHinhKhuyenMaiCacheModel.ngayHetHan = ngayHetHan.getTime();
		}
		else {
			loaiHinhKhuyenMaiCacheModel.ngayHetHan = Long.MIN_VALUE;
		}

		loaiHinhKhuyenMaiCacheModel.imageid = getImageid();

		String imageid = loaiHinhKhuyenMaiCacheModel.imageid;

		if ((imageid != null) && (imageid.length() == 0)) {
			loaiHinhKhuyenMaiCacheModel.imageid = null;
		}

		loaiHinhKhuyenMaiCacheModel.ghiChu = getGhiChu();

		String ghiChu = loaiHinhKhuyenMaiCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			loaiHinhKhuyenMaiCacheModel.ghiChu = null;
		}

		return loaiHinhKhuyenMaiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{loaiHinhKhuyenMaiId=");
		sb.append(getLoaiHinhKhuyenMaiId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", tileGiamGia=");
		sb.append(getTileGiamGia());
		sb.append(", ngayBatDau=");
		sb.append(getNgayBatDau());
		sb.append(", ngayHetHan=");
		sb.append(getNgayHetHan());
		sb.append(", imageid=");
		sb.append(getImageid());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>loaiHinhKhuyenMaiId</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinhKhuyenMaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tileGiamGia</column-name><column-value><![CDATA[");
		sb.append(getTileGiamGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayBatDau</column-name><column-value><![CDATA[");
		sb.append(getNgayBatDau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHan</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageid</column-name><column-value><![CDATA[");
		sb.append(getImageid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LoaiHinhKhuyenMai.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LoaiHinhKhuyenMai.class
		};
	private long _loaiHinhKhuyenMaiId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private boolean _trangThai;
	private boolean _originalTrangThai;
	private boolean _setOriginalTrangThai;
	private int _tileGiamGia;
	private Date _ngayBatDau;
	private Date _ngayHetHan;
	private String _imageid;
	private String _ghiChu;
	private long _columnBitmask;
	private LoaiHinhKhuyenMai _escapedModel;
}