/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.cuahang.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.cuahang.model.CaLamViec;
import com.minimart.portlet.cuahang.model.CaLamViecModel;
import com.minimart.portlet.cuahang.model.CaLamViecSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CaLamViec service. Represents a row in the &quot;minimart_calamviec&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.cuahang.model.CaLamViecModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CaLamViecImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see CaLamViecImpl
 * @see com.minimart.portlet.cuahang.model.CaLamViec
 * @see com.minimart.portlet.cuahang.model.CaLamViecModel
 * @generated
 */
@JSON(strict = true)
public class CaLamViecModelImpl extends BaseModelImpl<CaLamViec>
	implements CaLamViecModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ca lam viec model instance should use the {@link com.minimart.portlet.cuahang.model.CaLamViec} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_calamviec";
	public static final Object[][] TABLE_COLUMNS = {
			{ "caLamViecId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "cuaHangId", Types.BIGINT },
			{ "gioVaoLam", Types.TIMESTAMP },
			{ "gioRaVe", Types.TIMESTAMP },
			{ "gioNghiGiuaCaTu", Types.TIMESTAMP },
			{ "gioNghiGiuaCaDen", Types.TIMESTAMP },
			{ "tiLeLuong", Types.INTEGER },
			{ "hoatDong", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_calamviec (caLamViecId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,cuaHangId LONG,gioVaoLam DATE null,gioRaVe DATE null,gioNghiGiuaCaTu DATE null,gioNghiGiuaCaDen DATE null,tiLeLuong INTEGER,hoatDong BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table minimart_calamviec";
	public static final String ORDER_BY_JPQL = " ORDER BY caLamViec.ten ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_calamviec.ten ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.cuahang.model.CaLamViec"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.cuahang.model.CaLamViec"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.cuahang.model.CaLamViec"),
			true);
	public static long HOATDONG_COLUMN_BITMASK = 1L;
	public static long TEN_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CaLamViec toModel(CaLamViecSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CaLamViec model = new CaLamViecImpl();

		model.setCaLamViecId(soapModel.getCaLamViecId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setCuaHangId(soapModel.getCuaHangId());
		model.setGioVaoLam(soapModel.getGioVaoLam());
		model.setGioRaVe(soapModel.getGioRaVe());
		model.setGioNghiGiuaCaTu(soapModel.getGioNghiGiuaCaTu());
		model.setGioNghiGiuaCaDen(soapModel.getGioNghiGiuaCaDen());
		model.setTiLeLuong(soapModel.getTiLeLuong());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CaLamViec> toModels(CaLamViecSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CaLamViec> models = new ArrayList<CaLamViec>(soapModels.length);

		for (CaLamViecSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.cuahang.model.CaLamViec"));

	public CaLamViecModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _caLamViecId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCaLamViecId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _caLamViecId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CaLamViec.class;
	}

	@Override
	public String getModelClassName() {
		return CaLamViec.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("caLamViecId", getCaLamViecId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("cuaHangId", getCuaHangId());
		attributes.put("gioVaoLam", getGioVaoLam());
		attributes.put("gioRaVe", getGioRaVe());
		attributes.put("gioNghiGiuaCaTu", getGioNghiGiuaCaTu());
		attributes.put("gioNghiGiuaCaDen", getGioNghiGiuaCaDen());
		attributes.put("tiLeLuong", getTiLeLuong());
		attributes.put("hoatDong", getHoatDong());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long caLamViecId = (Long)attributes.get("caLamViecId");

		if (caLamViecId != null) {
			setCaLamViecId(caLamViecId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		Long cuaHangId = (Long)attributes.get("cuaHangId");

		if (cuaHangId != null) {
			setCuaHangId(cuaHangId);
		}

		Date gioVaoLam = (Date)attributes.get("gioVaoLam");

		if (gioVaoLam != null) {
			setGioVaoLam(gioVaoLam);
		}

		Date gioRaVe = (Date)attributes.get("gioRaVe");

		if (gioRaVe != null) {
			setGioRaVe(gioRaVe);
		}

		Date gioNghiGiuaCaTu = (Date)attributes.get("gioNghiGiuaCaTu");

		if (gioNghiGiuaCaTu != null) {
			setGioNghiGiuaCaTu(gioNghiGiuaCaTu);
		}

		Date gioNghiGiuaCaDen = (Date)attributes.get("gioNghiGiuaCaDen");

		if (gioNghiGiuaCaDen != null) {
			setGioNghiGiuaCaDen(gioNghiGiuaCaDen);
		}

		Integer tiLeLuong = (Integer)attributes.get("tiLeLuong");

		if (tiLeLuong != null) {
			setTiLeLuong(tiLeLuong);
		}

		Boolean hoatDong = (Boolean)attributes.get("hoatDong");

		if (hoatDong != null) {
			setHoatDong(hoatDong);
		}
	}

	@JSON
	@Override
	public long getCaLamViecId() {
		return _caLamViecId;
	}

	@Override
	public void setCaLamViecId(long caLamViecId) {
		_caLamViecId = caLamViecId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public long getCuaHangId() {
		return _cuaHangId;
	}

	@Override
	public void setCuaHangId(long cuaHangId) {
		_cuaHangId = cuaHangId;
	}

	@JSON
	@Override
	public Date getGioVaoLam() {
		return _gioVaoLam;
	}

	@Override
	public void setGioVaoLam(Date gioVaoLam) {
		_gioVaoLam = gioVaoLam;
	}

	@JSON
	@Override
	public Date getGioRaVe() {
		return _gioRaVe;
	}

	@Override
	public void setGioRaVe(Date gioRaVe) {
		_gioRaVe = gioRaVe;
	}

	@JSON
	@Override
	public Date getGioNghiGiuaCaTu() {
		return _gioNghiGiuaCaTu;
	}

	@Override
	public void setGioNghiGiuaCaTu(Date gioNghiGiuaCaTu) {
		_gioNghiGiuaCaTu = gioNghiGiuaCaTu;
	}

	@JSON
	@Override
	public Date getGioNghiGiuaCaDen() {
		return _gioNghiGiuaCaDen;
	}

	@Override
	public void setGioNghiGiuaCaDen(Date gioNghiGiuaCaDen) {
		_gioNghiGiuaCaDen = gioNghiGiuaCaDen;
	}

	@JSON
	@Override
	public int getTiLeLuong() {
		return _tiLeLuong;
	}

	@Override
	public void setTiLeLuong(int tiLeLuong) {
		_tiLeLuong = tiLeLuong;
	}

	@JSON
	@Override
	public boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public boolean isHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CaLamViec.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CaLamViec toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CaLamViec)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CaLamViecImpl caLamViecImpl = new CaLamViecImpl();

		caLamViecImpl.setCaLamViecId(getCaLamViecId());
		caLamViecImpl.setCompanyId(getCompanyId());
		caLamViecImpl.setUserId(getUserId());
		caLamViecImpl.setUserName(getUserName());
		caLamViecImpl.setCreateDate(getCreateDate());
		caLamViecImpl.setModifiedDate(getModifiedDate());
		caLamViecImpl.setTen(getTen());
		caLamViecImpl.setCuaHangId(getCuaHangId());
		caLamViecImpl.setGioVaoLam(getGioVaoLam());
		caLamViecImpl.setGioRaVe(getGioRaVe());
		caLamViecImpl.setGioNghiGiuaCaTu(getGioNghiGiuaCaTu());
		caLamViecImpl.setGioNghiGiuaCaDen(getGioNghiGiuaCaDen());
		caLamViecImpl.setTiLeLuong(getTiLeLuong());
		caLamViecImpl.setHoatDong(getHoatDong());

		caLamViecImpl.resetOriginalValues();

		return caLamViecImpl;
	}

	@Override
	public int compareTo(CaLamViec caLamViec) {
		int value = 0;

		value = getTen().compareTo(caLamViec.getTen());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CaLamViec)) {
			return false;
		}

		CaLamViec caLamViec = (CaLamViec)obj;

		long primaryKey = caLamViec.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CaLamViecModelImpl caLamViecModelImpl = this;

		caLamViecModelImpl._originalTen = caLamViecModelImpl._ten;

		caLamViecModelImpl._originalHoatDong = caLamViecModelImpl._hoatDong;

		caLamViecModelImpl._setOriginalHoatDong = false;

		caLamViecModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CaLamViec> toCacheModel() {
		CaLamViecCacheModel caLamViecCacheModel = new CaLamViecCacheModel();

		caLamViecCacheModel.caLamViecId = getCaLamViecId();

		caLamViecCacheModel.companyId = getCompanyId();

		caLamViecCacheModel.userId = getUserId();

		caLamViecCacheModel.userName = getUserName();

		String userName = caLamViecCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			caLamViecCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			caLamViecCacheModel.createDate = createDate.getTime();
		}
		else {
			caLamViecCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			caLamViecCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			caLamViecCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		caLamViecCacheModel.ten = getTen();

		String ten = caLamViecCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			caLamViecCacheModel.ten = null;
		}

		caLamViecCacheModel.cuaHangId = getCuaHangId();

		Date gioVaoLam = getGioVaoLam();

		if (gioVaoLam != null) {
			caLamViecCacheModel.gioVaoLam = gioVaoLam.getTime();
		}
		else {
			caLamViecCacheModel.gioVaoLam = Long.MIN_VALUE;
		}

		Date gioRaVe = getGioRaVe();

		if (gioRaVe != null) {
			caLamViecCacheModel.gioRaVe = gioRaVe.getTime();
		}
		else {
			caLamViecCacheModel.gioRaVe = Long.MIN_VALUE;
		}

		Date gioNghiGiuaCaTu = getGioNghiGiuaCaTu();

		if (gioNghiGiuaCaTu != null) {
			caLamViecCacheModel.gioNghiGiuaCaTu = gioNghiGiuaCaTu.getTime();
		}
		else {
			caLamViecCacheModel.gioNghiGiuaCaTu = Long.MIN_VALUE;
		}

		Date gioNghiGiuaCaDen = getGioNghiGiuaCaDen();

		if (gioNghiGiuaCaDen != null) {
			caLamViecCacheModel.gioNghiGiuaCaDen = gioNghiGiuaCaDen.getTime();
		}
		else {
			caLamViecCacheModel.gioNghiGiuaCaDen = Long.MIN_VALUE;
		}

		caLamViecCacheModel.tiLeLuong = getTiLeLuong();

		caLamViecCacheModel.hoatDong = getHoatDong();

		return caLamViecCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{caLamViecId=");
		sb.append(getCaLamViecId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", cuaHangId=");
		sb.append(getCuaHangId());
		sb.append(", gioVaoLam=");
		sb.append(getGioVaoLam());
		sb.append(", gioRaVe=");
		sb.append(getGioRaVe());
		sb.append(", gioNghiGiuaCaTu=");
		sb.append(getGioNghiGiuaCaTu());
		sb.append(", gioNghiGiuaCaDen=");
		sb.append(getGioNghiGiuaCaDen());
		sb.append(", tiLeLuong=");
		sb.append(getTiLeLuong());
		sb.append(", hoatDong=");
		sb.append(getHoatDong());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.cuahang.model.CaLamViec");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>caLamViecId</column-name><column-value><![CDATA[");
		sb.append(getCaLamViecId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuaHangId</column-name><column-value><![CDATA[");
		sb.append(getCuaHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioVaoLam</column-name><column-value><![CDATA[");
		sb.append(getGioVaoLam());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioRaVe</column-name><column-value><![CDATA[");
		sb.append(getGioRaVe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioNghiGiuaCaTu</column-name><column-value><![CDATA[");
		sb.append(getGioNghiGiuaCaTu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioNghiGiuaCaDen</column-name><column-value><![CDATA[");
		sb.append(getGioNghiGiuaCaDen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiLeLuong</column-name><column-value><![CDATA[");
		sb.append(getTiLeLuong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoatDong</column-name><column-value><![CDATA[");
		sb.append(getHoatDong());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CaLamViec.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CaLamViec.class
		};
	private long _caLamViecId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private long _cuaHangId;
	private Date _gioVaoLam;
	private Date _gioRaVe;
	private Date _gioNghiGiuaCaTu;
	private Date _gioNghiGiuaCaDen;
	private int _tiLeLuong;
	private boolean _hoatDong;
	private boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private long _columnBitmask;
	private CaLamViec _escapedModel;
}