/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.cuahang.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.cuahang.model.CuaHang;
import com.minimart.portlet.cuahang.model.CuaHangModel;
import com.minimart.portlet.cuahang.model.CuaHangSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CuaHang service. Represents a row in the &quot;minimart_cuahang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.cuahang.model.CuaHangModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CuaHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see CuaHangImpl
 * @see com.minimart.portlet.cuahang.model.CuaHang
 * @see com.minimart.portlet.cuahang.model.CuaHangModel
 * @generated
 */
@JSON(strict = true)
public class CuaHangModelImpl extends BaseModelImpl<CuaHang>
	implements CuaHangModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cua hang model instance should use the {@link com.minimart.portlet.cuahang.model.CuaHang} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_cuahang";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "cuaHangId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "gioMoCua", Types.TIMESTAMP },
			{ "gioDongCua", Types.TIMESTAMP },
			{ "hoatDong", Types.BOOLEAN },
			{ "uuTien", Types.INTEGER },
			{ "diaChi", Types.VARCHAR },
			{ "dienThoai", Types.VARCHAR },
			{ "khoHangId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_cuahang (uuid_ VARCHAR(75) null,cuaHangId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,gioMoCua DATE null,gioDongCua DATE null,hoatDong BOOLEAN,uuTien INTEGER,diaChi VARCHAR(75) null,dienThoai VARCHAR(75) null,khoHangId LONG)";
	public static final String TABLE_SQL_DROP = "drop table minimart_cuahang";
	public static final String ORDER_BY_JPQL = " ORDER BY cuaHang.ten ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_cuahang.ten ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.cuahang.model.CuaHang"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.cuahang.model.CuaHang"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.cuahang.model.CuaHang"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long HOATDONG_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CuaHang toModel(CuaHangSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CuaHang model = new CuaHangImpl();

		model.setUuid(soapModel.getUuid());
		model.setCuaHangId(soapModel.getCuaHangId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setGioMoCua(soapModel.getGioMoCua());
		model.setGioDongCua(soapModel.getGioDongCua());
		model.setHoatDong(soapModel.getHoatDong());
		model.setUuTien(soapModel.getUuTien());
		model.setDiaChi(soapModel.getDiaChi());
		model.setDienThoai(soapModel.getDienThoai());
		model.setKhoHangId(soapModel.getKhoHangId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CuaHang> toModels(CuaHangSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CuaHang> models = new ArrayList<CuaHang>(soapModels.length);

		for (CuaHangSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.cuahang.model.CuaHang"));

	public CuaHangModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cuaHangId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCuaHangId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cuaHangId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CuaHang.class;
	}

	@Override
	public String getModelClassName() {
		return CuaHang.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("cuaHangId", getCuaHangId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("gioMoCua", getGioMoCua());
		attributes.put("gioDongCua", getGioDongCua());
		attributes.put("hoatDong", getHoatDong());
		attributes.put("uuTien", getUuTien());
		attributes.put("diaChi", getDiaChi());
		attributes.put("dienThoai", getDienThoai());
		attributes.put("khoHangId", getKhoHangId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long cuaHangId = (Long)attributes.get("cuaHangId");

		if (cuaHangId != null) {
			setCuaHangId(cuaHangId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		Date gioMoCua = (Date)attributes.get("gioMoCua");

		if (gioMoCua != null) {
			setGioMoCua(gioMoCua);
		}

		Date gioDongCua = (Date)attributes.get("gioDongCua");

		if (gioDongCua != null) {
			setGioDongCua(gioDongCua);
		}

		Boolean hoatDong = (Boolean)attributes.get("hoatDong");

		if (hoatDong != null) {
			setHoatDong(hoatDong);
		}

		Integer uuTien = (Integer)attributes.get("uuTien");

		if (uuTien != null) {
			setUuTien(uuTien);
		}

		String diaChi = (String)attributes.get("diaChi");

		if (diaChi != null) {
			setDiaChi(diaChi);
		}

		String dienThoai = (String)attributes.get("dienThoai");

		if (dienThoai != null) {
			setDienThoai(dienThoai);
		}

		Long khoHangId = (Long)attributes.get("khoHangId");

		if (khoHangId != null) {
			setKhoHangId(khoHangId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCuaHangId() {
		return _cuaHangId;
	}

	@Override
	public void setCuaHangId(long cuaHangId) {
		_cuaHangId = cuaHangId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public Date getGioMoCua() {
		return _gioMoCua;
	}

	@Override
	public void setGioMoCua(Date gioMoCua) {
		_gioMoCua = gioMoCua;
	}

	@JSON
	@Override
	public Date getGioDongCua() {
		return _gioDongCua;
	}

	@Override
	public void setGioDongCua(Date gioDongCua) {
		_gioDongCua = gioDongCua;
	}

	@JSON
	@Override
	public boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public boolean isHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	@JSON
	@Override
	public int getUuTien() {
		return _uuTien;
	}

	@Override
	public void setUuTien(int uuTien) {
		_uuTien = uuTien;
	}

	@JSON
	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@JSON
	@Override
	public String getDienThoai() {
		if (_dienThoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoai;
		}
	}

	@Override
	public void setDienThoai(String dienThoai) {
		_dienThoai = dienThoai;
	}

	@JSON
	@Override
	public long getKhoHangId() {
		return _khoHangId;
	}

	@Override
	public void setKhoHangId(long khoHangId) {
		_khoHangId = khoHangId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				CuaHang.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CuaHang.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CuaHang toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CuaHang)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CuaHangImpl cuaHangImpl = new CuaHangImpl();

		cuaHangImpl.setUuid(getUuid());
		cuaHangImpl.setCuaHangId(getCuaHangId());
		cuaHangImpl.setCompanyId(getCompanyId());
		cuaHangImpl.setUserId(getUserId());
		cuaHangImpl.setUserName(getUserName());
		cuaHangImpl.setCreateDate(getCreateDate());
		cuaHangImpl.setModifiedDate(getModifiedDate());
		cuaHangImpl.setTen(getTen());
		cuaHangImpl.setGioMoCua(getGioMoCua());
		cuaHangImpl.setGioDongCua(getGioDongCua());
		cuaHangImpl.setHoatDong(getHoatDong());
		cuaHangImpl.setUuTien(getUuTien());
		cuaHangImpl.setDiaChi(getDiaChi());
		cuaHangImpl.setDienThoai(getDienThoai());
		cuaHangImpl.setKhoHangId(getKhoHangId());

		cuaHangImpl.resetOriginalValues();

		return cuaHangImpl;
	}

	@Override
	public int compareTo(CuaHang cuaHang) {
		int value = 0;

		value = getTen().compareTo(cuaHang.getTen());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CuaHang)) {
			return false;
		}

		CuaHang cuaHang = (CuaHang)obj;

		long primaryKey = cuaHang.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CuaHangModelImpl cuaHangModelImpl = this;

		cuaHangModelImpl._originalUuid = cuaHangModelImpl._uuid;

		cuaHangModelImpl._originalCompanyId = cuaHangModelImpl._companyId;

		cuaHangModelImpl._setOriginalCompanyId = false;

		cuaHangModelImpl._originalTen = cuaHangModelImpl._ten;

		cuaHangModelImpl._originalHoatDong = cuaHangModelImpl._hoatDong;

		cuaHangModelImpl._setOriginalHoatDong = false;

		cuaHangModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CuaHang> toCacheModel() {
		CuaHangCacheModel cuaHangCacheModel = new CuaHangCacheModel();

		cuaHangCacheModel.uuid = getUuid();

		String uuid = cuaHangCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cuaHangCacheModel.uuid = null;
		}

		cuaHangCacheModel.cuaHangId = getCuaHangId();

		cuaHangCacheModel.companyId = getCompanyId();

		cuaHangCacheModel.userId = getUserId();

		cuaHangCacheModel.userName = getUserName();

		String userName = cuaHangCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cuaHangCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cuaHangCacheModel.createDate = createDate.getTime();
		}
		else {
			cuaHangCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cuaHangCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cuaHangCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cuaHangCacheModel.ten = getTen();

		String ten = cuaHangCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			cuaHangCacheModel.ten = null;
		}

		Date gioMoCua = getGioMoCua();

		if (gioMoCua != null) {
			cuaHangCacheModel.gioMoCua = gioMoCua.getTime();
		}
		else {
			cuaHangCacheModel.gioMoCua = Long.MIN_VALUE;
		}

		Date gioDongCua = getGioDongCua();

		if (gioDongCua != null) {
			cuaHangCacheModel.gioDongCua = gioDongCua.getTime();
		}
		else {
			cuaHangCacheModel.gioDongCua = Long.MIN_VALUE;
		}

		cuaHangCacheModel.hoatDong = getHoatDong();

		cuaHangCacheModel.uuTien = getUuTien();

		cuaHangCacheModel.diaChi = getDiaChi();

		String diaChi = cuaHangCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			cuaHangCacheModel.diaChi = null;
		}

		cuaHangCacheModel.dienThoai = getDienThoai();

		String dienThoai = cuaHangCacheModel.dienThoai;

		if ((dienThoai != null) && (dienThoai.length() == 0)) {
			cuaHangCacheModel.dienThoai = null;
		}

		cuaHangCacheModel.khoHangId = getKhoHangId();

		return cuaHangCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", cuaHangId=");
		sb.append(getCuaHangId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", gioMoCua=");
		sb.append(getGioMoCua());
		sb.append(", gioDongCua=");
		sb.append(getGioDongCua());
		sb.append(", hoatDong=");
		sb.append(getHoatDong());
		sb.append(", uuTien=");
		sb.append(getUuTien());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", dienThoai=");
		sb.append(getDienThoai());
		sb.append(", khoHangId=");
		sb.append(getKhoHangId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.cuahang.model.CuaHang");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuaHangId</column-name><column-value><![CDATA[");
		sb.append(getCuaHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioMoCua</column-name><column-value><![CDATA[");
		sb.append(getGioMoCua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioDongCua</column-name><column-value><![CDATA[");
		sb.append(getGioDongCua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoatDong</column-name><column-value><![CDATA[");
		sb.append(getHoatDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uuTien</column-name><column-value><![CDATA[");
		sb.append(getUuTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoai</column-name><column-value><![CDATA[");
		sb.append(getDienThoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>khoHangId</column-name><column-value><![CDATA[");
		sb.append(getKhoHangId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CuaHang.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CuaHang.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _cuaHangId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private Date _gioMoCua;
	private Date _gioDongCua;
	private boolean _hoatDong;
	private boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private int _uuTien;
	private String _diaChi;
	private String _dienThoai;
	private long _khoHangId;
	private long _columnBitmask;
	private CuaHang _escapedModel;
}