/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.danhmucchung.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.minimart.portlet.danhmucchung.model.TinhThanhPho;
import com.minimart.portlet.danhmucchung.model.TinhThanhPhoModel;
import com.minimart.portlet.danhmucchung.model.TinhThanhPhoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TinhThanhPho service. Represents a row in the &quot;minimart_tinhthanhpho&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.minimart.portlet.danhmucchung.model.TinhThanhPhoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TinhThanhPhoImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see TinhThanhPhoImpl
 * @see com.minimart.portlet.danhmucchung.model.TinhThanhPho
 * @see com.minimart.portlet.danhmucchung.model.TinhThanhPhoModel
 * @generated
 */
@JSON(strict = true)
public class TinhThanhPhoModelImpl extends BaseModelImpl<TinhThanhPho>
	implements TinhThanhPhoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tinh thanh pho model instance should use the {@link com.minimart.portlet.danhmucchung.model.TinhThanhPho} interface instead.
	 */
	public static final String TABLE_NAME = "minimart_tinhthanhpho";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tinhThanhPhoId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "ten", Types.VARCHAR },
			{ "ma", Types.VARCHAR },
			{ "trangThai", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table minimart_tinhthanhpho (tinhThanhPhoId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,ma VARCHAR(75) null,trangThai BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table minimart_tinhthanhpho";
	public static final String ORDER_BY_JPQL = " ORDER BY tinhThanhPho.ten ASC";
	public static final String ORDER_BY_SQL = " ORDER BY minimart_tinhthanhpho.ten ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.minimart.portlet.danhmucchung.model.TinhThanhPho"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.minimart.portlet.danhmucchung.model.TinhThanhPho"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.minimart.portlet.danhmucchung.model.TinhThanhPho"),
			true);
	public static long MA_COLUMN_BITMASK = 1L;
	public static long TEN_COLUMN_BITMASK = 2L;
	public static long TRANGTHAI_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TinhThanhPho toModel(TinhThanhPhoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TinhThanhPho model = new TinhThanhPhoImpl();

		model.setTinhThanhPhoId(soapModel.getTinhThanhPhoId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setMa(soapModel.getMa());
		model.setTrangThai(soapModel.getTrangThai());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TinhThanhPho> toModels(TinhThanhPhoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TinhThanhPho> models = new ArrayList<TinhThanhPho>(soapModels.length);

		for (TinhThanhPhoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.minimart.portlet.danhmucchung.model.TinhThanhPho"));

	public TinhThanhPhoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tinhThanhPhoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTinhThanhPhoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tinhThanhPhoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TinhThanhPho.class;
	}

	@Override
	public String getModelClassName() {
		return TinhThanhPho.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tinhThanhPhoId", getTinhThanhPhoId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("ten", getTen());
		attributes.put("ma", getMa());
		attributes.put("trangThai", getTrangThai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tinhThanhPhoId = (Long)attributes.get("tinhThanhPhoId");

		if (tinhThanhPhoId != null) {
			setTinhThanhPhoId(tinhThanhPhoId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		String ma = (String)attributes.get("ma");

		if (ma != null) {
			setMa(ma);
		}

		Boolean trangThai = (Boolean)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}
	}

	@JSON
	@Override
	public long getTinhThanhPhoId() {
		return _tinhThanhPhoId;
	}

	@Override
	public void setTinhThanhPhoId(long tinhThanhPhoId) {
		_tinhThanhPhoId = tinhThanhPhoId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public boolean getTrangThai() {
		return _trangThai;
	}

	@Override
	public boolean isTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(boolean trangThai) {
		_columnBitmask |= TRANGTHAI_COLUMN_BITMASK;

		if (!_setOriginalTrangThai) {
			_setOriginalTrangThai = true;

			_originalTrangThai = _trangThai;
		}

		_trangThai = trangThai;
	}

	public boolean getOriginalTrangThai() {
		return _originalTrangThai;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TinhThanhPho.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TinhThanhPho toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TinhThanhPho)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TinhThanhPhoImpl tinhThanhPhoImpl = new TinhThanhPhoImpl();

		tinhThanhPhoImpl.setTinhThanhPhoId(getTinhThanhPhoId());
		tinhThanhPhoImpl.setCompanyId(getCompanyId());
		tinhThanhPhoImpl.setUserId(getUserId());
		tinhThanhPhoImpl.setUserName(getUserName());
		tinhThanhPhoImpl.setCreateDate(getCreateDate());
		tinhThanhPhoImpl.setModifiedDate(getModifiedDate());
		tinhThanhPhoImpl.setTen(getTen());
		tinhThanhPhoImpl.setMa(getMa());
		tinhThanhPhoImpl.setTrangThai(getTrangThai());

		tinhThanhPhoImpl.resetOriginalValues();

		return tinhThanhPhoImpl;
	}

	@Override
	public int compareTo(TinhThanhPho tinhThanhPho) {
		int value = 0;

		value = getTen().compareTo(tinhThanhPho.getTen());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TinhThanhPho)) {
			return false;
		}

		TinhThanhPho tinhThanhPho = (TinhThanhPho)obj;

		long primaryKey = tinhThanhPho.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TinhThanhPhoModelImpl tinhThanhPhoModelImpl = this;

		tinhThanhPhoModelImpl._originalTen = tinhThanhPhoModelImpl._ten;

		tinhThanhPhoModelImpl._originalMa = tinhThanhPhoModelImpl._ma;

		tinhThanhPhoModelImpl._originalTrangThai = tinhThanhPhoModelImpl._trangThai;

		tinhThanhPhoModelImpl._setOriginalTrangThai = false;

		tinhThanhPhoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TinhThanhPho> toCacheModel() {
		TinhThanhPhoCacheModel tinhThanhPhoCacheModel = new TinhThanhPhoCacheModel();

		tinhThanhPhoCacheModel.tinhThanhPhoId = getTinhThanhPhoId();

		tinhThanhPhoCacheModel.companyId = getCompanyId();

		tinhThanhPhoCacheModel.userId = getUserId();

		tinhThanhPhoCacheModel.userName = getUserName();

		String userName = tinhThanhPhoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tinhThanhPhoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tinhThanhPhoCacheModel.createDate = createDate.getTime();
		}
		else {
			tinhThanhPhoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tinhThanhPhoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tinhThanhPhoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tinhThanhPhoCacheModel.ten = getTen();

		String ten = tinhThanhPhoCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			tinhThanhPhoCacheModel.ten = null;
		}

		tinhThanhPhoCacheModel.ma = getMa();

		String ma = tinhThanhPhoCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			tinhThanhPhoCacheModel.ma = null;
		}

		tinhThanhPhoCacheModel.trangThai = getTrangThai();

		return tinhThanhPhoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{tinhThanhPhoId=");
		sb.append(getTinhThanhPhoId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.minimart.portlet.danhmucchung.model.TinhThanhPho");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tinhThanhPhoId</column-name><column-value><![CDATA[");
		sb.append(getTinhThanhPhoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TinhThanhPho.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TinhThanhPho.class
		};
	private long _tinhThanhPhoId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _ten;
	private String _originalTen;
	private String _ma;
	private String _originalMa;
	private boolean _trangThai;
	private boolean _originalTrangThai;
	private boolean _setOriginalTrangThai;
	private long _columnBitmask;
	private TinhThanhPho _escapedModel;
}