/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khuyenmai.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DotKhuyenMai service. Represents a row in the &quot;minimart_dotkhuyenmai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.khuyenmai.model.impl.DotKhuyenMaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.khuyenmai.model.impl.DotKhuyenMaiImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see DotKhuyenMai
 * @see com.minimart.portlet.khuyenmai.model.impl.DotKhuyenMaiImpl
 * @see com.minimart.portlet.khuyenmai.model.impl.DotKhuyenMaiModelImpl
 * @generated
 */
public interface DotKhuyenMaiModel extends AuditedModel, BaseModel<DotKhuyenMai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dot khuyen mai model instance should use the {@link DotKhuyenMai} interface instead.
	 */

	/**
	 * Returns the primary key of this dot khuyen mai.
	 *
	 * @return the primary key of this dot khuyen mai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dot khuyen mai.
	 *
	 * @param primaryKey the primary key of this dot khuyen mai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dot khuyen mai ID of this dot khuyen mai.
	 *
	 * @return the dot khuyen mai ID of this dot khuyen mai
	 */
	public long getDotKhuyenMaiId();

	/**
	 * Sets the dot khuyen mai ID of this dot khuyen mai.
	 *
	 * @param dotKhuyenMaiId the dot khuyen mai ID of this dot khuyen mai
	 */
	public void setDotKhuyenMaiId(long dotKhuyenMaiId);

	/**
	 * Returns the company ID of this dot khuyen mai.
	 *
	 * @return the company ID of this dot khuyen mai
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dot khuyen mai.
	 *
	 * @param companyId the company ID of this dot khuyen mai
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dot khuyen mai.
	 *
	 * @return the user ID of this dot khuyen mai
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dot khuyen mai.
	 *
	 * @param userId the user ID of this dot khuyen mai
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dot khuyen mai.
	 *
	 * @return the user uuid of this dot khuyen mai
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dot khuyen mai.
	 *
	 * @param userUuid the user uuid of this dot khuyen mai
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dot khuyen mai.
	 *
	 * @return the user name of this dot khuyen mai
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dot khuyen mai.
	 *
	 * @param userName the user name of this dot khuyen mai
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dot khuyen mai.
	 *
	 * @return the create date of this dot khuyen mai
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dot khuyen mai.
	 *
	 * @param createDate the create date of this dot khuyen mai
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dot khuyen mai.
	 *
	 * @return the modified date of this dot khuyen mai
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dot khuyen mai.
	 *
	 * @param modifiedDate the modified date of this dot khuyen mai
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this dot khuyen mai.
	 *
	 * @return the ten of this dot khuyen mai
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this dot khuyen mai.
	 *
	 * @param ten the ten of this dot khuyen mai
	 */
	public void setTen(String ten);

	/**
	 * Returns the trang thai of this dot khuyen mai.
	 *
	 * @return the trang thai of this dot khuyen mai
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this dot khuyen mai is trang thai.
	 *
	 * @return <code>true</code> if this dot khuyen mai is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this dot khuyen mai is trang thai.
	 *
	 * @param trangThai the trang thai of this dot khuyen mai
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the user modifield ID of this dot khuyen mai.
	 *
	 * @return the user modifield ID of this dot khuyen mai
	 */
	public long getUserModifieldId();

	/**
	 * Sets the user modifield ID of this dot khuyen mai.
	 *
	 * @param userModifieldId the user modifield ID of this dot khuyen mai
	 */
	public void setUserModifieldId(long userModifieldId);

	/**
	 * Returns the ngay bat dau of this dot khuyen mai.
	 *
	 * @return the ngay bat dau of this dot khuyen mai
	 */
	public Date getNgayBatDau();

	/**
	 * Sets the ngay bat dau of this dot khuyen mai.
	 *
	 * @param ngayBatDau the ngay bat dau of this dot khuyen mai
	 */
	public void setNgayBatDau(Date ngayBatDau);

	/**
	 * Returns the ngay het han of this dot khuyen mai.
	 *
	 * @return the ngay het han of this dot khuyen mai
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this dot khuyen mai.
	 *
	 * @param ngayHetHan the ngay het han of this dot khuyen mai
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the ngung ap dung of this dot khuyen mai.
	 *
	 * @return the ngung ap dung of this dot khuyen mai
	 */
	public boolean getNgungApDung();

	/**
	 * Returns <code>true</code> if this dot khuyen mai is ngung ap dung.
	 *
	 * @return <code>true</code> if this dot khuyen mai is ngung ap dung; <code>false</code> otherwise
	 */
	public boolean isNgungApDung();

	/**
	 * Sets whether this dot khuyen mai is ngung ap dung.
	 *
	 * @param ngungApDung the ngung ap dung of this dot khuyen mai
	 */
	public void setNgungApDung(boolean ngungApDung);

	/**
	 * Returns the ti le gia gia of this dot khuyen mai.
	 *
	 * @return the ti le gia gia of this dot khuyen mai
	 */
	public int getTiLeGiaGia();

	/**
	 * Sets the ti le gia gia of this dot khuyen mai.
	 *
	 * @param tiLeGiaGia the ti le gia gia of this dot khuyen mai
	 */
	public void setTiLeGiaGia(int tiLeGiaGia);

	/**
	 * Returns the ghi chu of this dot khuyen mai.
	 *
	 * @return the ghi chu of this dot khuyen mai
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this dot khuyen mai.
	 *
	 * @param ghiChu the ghi chu of this dot khuyen mai
	 */
	public void setGhiChu(String ghiChu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.khuyenmai.model.DotKhuyenMai dotKhuyenMai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.khuyenmai.model.DotKhuyenMai> toCacheModel();

	@Override
	public com.minimart.portlet.khuyenmai.model.DotKhuyenMai toEscapedModel();

	@Override
	public com.minimart.portlet.khuyenmai.model.DotKhuyenMai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}