/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.khuyenmai.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LoaiHinhKhuyenMai service. Represents a row in the &quot;minimart_loaihinhkhuyenmai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.khuyenmai.model.impl.LoaiHinhKhuyenMaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.khuyenmai.model.impl.LoaiHinhKhuyenMaiImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see LoaiHinhKhuyenMai
 * @see com.minimart.portlet.khuyenmai.model.impl.LoaiHinhKhuyenMaiImpl
 * @see com.minimart.portlet.khuyenmai.model.impl.LoaiHinhKhuyenMaiModelImpl
 * @generated
 */
public interface LoaiHinhKhuyenMaiModel extends AuditedModel,
	BaseModel<LoaiHinhKhuyenMai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loai hinh khuyen mai model instance should use the {@link LoaiHinhKhuyenMai} interface instead.
	 */

	/**
	 * Returns the primary key of this loai hinh khuyen mai.
	 *
	 * @return the primary key of this loai hinh khuyen mai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loai hinh khuyen mai.
	 *
	 * @param primaryKey the primary key of this loai hinh khuyen mai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loai hinh khuyen mai ID of this loai hinh khuyen mai.
	 *
	 * @return the loai hinh khuyen mai ID of this loai hinh khuyen mai
	 */
	public long getLoaiHinhKhuyenMaiId();

	/**
	 * Sets the loai hinh khuyen mai ID of this loai hinh khuyen mai.
	 *
	 * @param loaiHinhKhuyenMaiId the loai hinh khuyen mai ID of this loai hinh khuyen mai
	 */
	public void setLoaiHinhKhuyenMaiId(long loaiHinhKhuyenMaiId);

	/**
	 * Returns the company ID of this loai hinh khuyen mai.
	 *
	 * @return the company ID of this loai hinh khuyen mai
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loai hinh khuyen mai.
	 *
	 * @param companyId the company ID of this loai hinh khuyen mai
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loai hinh khuyen mai.
	 *
	 * @return the user ID of this loai hinh khuyen mai
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loai hinh khuyen mai.
	 *
	 * @param userId the user ID of this loai hinh khuyen mai
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loai hinh khuyen mai.
	 *
	 * @return the user uuid of this loai hinh khuyen mai
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this loai hinh khuyen mai.
	 *
	 * @param userUuid the user uuid of this loai hinh khuyen mai
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loai hinh khuyen mai.
	 *
	 * @return the user name of this loai hinh khuyen mai
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loai hinh khuyen mai.
	 *
	 * @param userName the user name of this loai hinh khuyen mai
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loai hinh khuyen mai.
	 *
	 * @return the create date of this loai hinh khuyen mai
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loai hinh khuyen mai.
	 *
	 * @param createDate the create date of this loai hinh khuyen mai
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loai hinh khuyen mai.
	 *
	 * @return the modified date of this loai hinh khuyen mai
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loai hinh khuyen mai.
	 *
	 * @param modifiedDate the modified date of this loai hinh khuyen mai
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this loai hinh khuyen mai.
	 *
	 * @return the ten of this loai hinh khuyen mai
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this loai hinh khuyen mai.
	 *
	 * @param ten the ten of this loai hinh khuyen mai
	 */
	public void setTen(String ten);

	/**
	 * Returns the trang thai of this loai hinh khuyen mai.
	 *
	 * @return the trang thai of this loai hinh khuyen mai
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this loai hinh khuyen mai is trang thai.
	 *
	 * @return <code>true</code> if this loai hinh khuyen mai is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this loai hinh khuyen mai is trang thai.
	 *
	 * @param trangThai the trang thai of this loai hinh khuyen mai
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the tile giam gia of this loai hinh khuyen mai.
	 *
	 * @return the tile giam gia of this loai hinh khuyen mai
	 */
	public int getTileGiamGia();

	/**
	 * Sets the tile giam gia of this loai hinh khuyen mai.
	 *
	 * @param tileGiamGia the tile giam gia of this loai hinh khuyen mai
	 */
	public void setTileGiamGia(int tileGiamGia);

	/**
	 * Returns the ngay bat dau of this loai hinh khuyen mai.
	 *
	 * @return the ngay bat dau of this loai hinh khuyen mai
	 */
	public Date getNgayBatDau();

	/**
	 * Sets the ngay bat dau of this loai hinh khuyen mai.
	 *
	 * @param ngayBatDau the ngay bat dau of this loai hinh khuyen mai
	 */
	public void setNgayBatDau(Date ngayBatDau);

	/**
	 * Returns the ngay het han of this loai hinh khuyen mai.
	 *
	 * @return the ngay het han of this loai hinh khuyen mai
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this loai hinh khuyen mai.
	 *
	 * @param ngayHetHan the ngay het han of this loai hinh khuyen mai
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the imageid of this loai hinh khuyen mai.
	 *
	 * @return the imageid of this loai hinh khuyen mai
	 */
	@AutoEscape
	public String getImageid();

	/**
	 * Sets the imageid of this loai hinh khuyen mai.
	 *
	 * @param imageid the imageid of this loai hinh khuyen mai
	 */
	public void setImageid(String imageid);

	/**
	 * Returns the ghi chu of this loai hinh khuyen mai.
	 *
	 * @return the ghi chu of this loai hinh khuyen mai
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this loai hinh khuyen mai.
	 *
	 * @param ghiChu the ghi chu of this loai hinh khuyen mai
	 */
	public void setGhiChu(String ghiChu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai loaiHinhKhuyenMai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai> toCacheModel();

	@Override
	public com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai toEscapedModel();

	@Override
	public com.minimart.portlet.khuyenmai.model.LoaiHinhKhuyenMai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}