/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.cuahang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CaLamViec service. Represents a row in the &quot;minimart_calamviec&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.cuahang.model.impl.CaLamViecModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.cuahang.model.impl.CaLamViecImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see CaLamViec
 * @see com.minimart.portlet.cuahang.model.impl.CaLamViecImpl
 * @see com.minimart.portlet.cuahang.model.impl.CaLamViecModelImpl
 * @generated
 */
public interface CaLamViecModel extends AuditedModel, BaseModel<CaLamViec> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ca lam viec model instance should use the {@link CaLamViec} interface instead.
	 */

	/**
	 * Returns the primary key of this ca lam viec.
	 *
	 * @return the primary key of this ca lam viec
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ca lam viec.
	 *
	 * @param primaryKey the primary key of this ca lam viec
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ca lam viec ID of this ca lam viec.
	 *
	 * @return the ca lam viec ID of this ca lam viec
	 */
	public long getCaLamViecId();

	/**
	 * Sets the ca lam viec ID of this ca lam viec.
	 *
	 * @param caLamViecId the ca lam viec ID of this ca lam viec
	 */
	public void setCaLamViecId(long caLamViecId);

	/**
	 * Returns the company ID of this ca lam viec.
	 *
	 * @return the company ID of this ca lam viec
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ca lam viec.
	 *
	 * @param companyId the company ID of this ca lam viec
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ca lam viec.
	 *
	 * @return the user ID of this ca lam viec
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ca lam viec.
	 *
	 * @param userId the user ID of this ca lam viec
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ca lam viec.
	 *
	 * @return the user uuid of this ca lam viec
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ca lam viec.
	 *
	 * @param userUuid the user uuid of this ca lam viec
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ca lam viec.
	 *
	 * @return the user name of this ca lam viec
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ca lam viec.
	 *
	 * @param userName the user name of this ca lam viec
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ca lam viec.
	 *
	 * @return the create date of this ca lam viec
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ca lam viec.
	 *
	 * @param createDate the create date of this ca lam viec
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ca lam viec.
	 *
	 * @return the modified date of this ca lam viec
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ca lam viec.
	 *
	 * @param modifiedDate the modified date of this ca lam viec
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this ca lam viec.
	 *
	 * @return the ten of this ca lam viec
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this ca lam viec.
	 *
	 * @param ten the ten of this ca lam viec
	 */
	public void setTen(String ten);

	/**
	 * Returns the cua hang ID of this ca lam viec.
	 *
	 * @return the cua hang ID of this ca lam viec
	 */
	public long getCuaHangId();

	/**
	 * Sets the cua hang ID of this ca lam viec.
	 *
	 * @param cuaHangId the cua hang ID of this ca lam viec
	 */
	public void setCuaHangId(long cuaHangId);

	/**
	 * Returns the gio vao lam of this ca lam viec.
	 *
	 * @return the gio vao lam of this ca lam viec
	 */
	public Date getGioVaoLam();

	/**
	 * Sets the gio vao lam of this ca lam viec.
	 *
	 * @param gioVaoLam the gio vao lam of this ca lam viec
	 */
	public void setGioVaoLam(Date gioVaoLam);

	/**
	 * Returns the gio ra ve of this ca lam viec.
	 *
	 * @return the gio ra ve of this ca lam viec
	 */
	public Date getGioRaVe();

	/**
	 * Sets the gio ra ve of this ca lam viec.
	 *
	 * @param gioRaVe the gio ra ve of this ca lam viec
	 */
	public void setGioRaVe(Date gioRaVe);

	/**
	 * Returns the gio nghi giua ca tu of this ca lam viec.
	 *
	 * @return the gio nghi giua ca tu of this ca lam viec
	 */
	public Date getGioNghiGiuaCaTu();

	/**
	 * Sets the gio nghi giua ca tu of this ca lam viec.
	 *
	 * @param gioNghiGiuaCaTu the gio nghi giua ca tu of this ca lam viec
	 */
	public void setGioNghiGiuaCaTu(Date gioNghiGiuaCaTu);

	/**
	 * Returns the gio nghi giua ca den of this ca lam viec.
	 *
	 * @return the gio nghi giua ca den of this ca lam viec
	 */
	public Date getGioNghiGiuaCaDen();

	/**
	 * Sets the gio nghi giua ca den of this ca lam viec.
	 *
	 * @param gioNghiGiuaCaDen the gio nghi giua ca den of this ca lam viec
	 */
	public void setGioNghiGiuaCaDen(Date gioNghiGiuaCaDen);

	/**
	 * Returns the ti le luong of this ca lam viec.
	 *
	 * @return the ti le luong of this ca lam viec
	 */
	public int getTiLeLuong();

	/**
	 * Sets the ti le luong of this ca lam viec.
	 *
	 * @param tiLeLuong the ti le luong of this ca lam viec
	 */
	public void setTiLeLuong(int tiLeLuong);

	/**
	 * Returns the hoat dong of this ca lam viec.
	 *
	 * @return the hoat dong of this ca lam viec
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this ca lam viec is hoat dong.
	 *
	 * @return <code>true</code> if this ca lam viec is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this ca lam viec is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this ca lam viec
	 */
	public void setHoatDong(boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.cuahang.model.CaLamViec caLamViec);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.cuahang.model.CaLamViec> toCacheModel();

	@Override
	public com.minimart.portlet.cuahang.model.CaLamViec toEscapedModel();

	@Override
	public com.minimart.portlet.cuahang.model.CaLamViec toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}