/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.cuahang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedAuditedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CuaHang service. Represents a row in the &quot;minimart_cuahang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.cuahang.model.impl.CuaHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.cuahang.model.impl.CuaHangImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see CuaHang
 * @see com.minimart.portlet.cuahang.model.impl.CuaHangImpl
 * @see com.minimart.portlet.cuahang.model.impl.CuaHangModelImpl
 * @generated
 */
public interface CuaHangModel extends BaseModel<CuaHang>, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cua hang model instance should use the {@link CuaHang} interface instead.
	 */

	/**
	 * Returns the primary key of this cua hang.
	 *
	 * @return the primary key of this cua hang
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cua hang.
	 *
	 * @param primaryKey the primary key of this cua hang
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cua hang.
	 *
	 * @return the uuid of this cua hang
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cua hang.
	 *
	 * @param uuid the uuid of this cua hang
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cua hang ID of this cua hang.
	 *
	 * @return the cua hang ID of this cua hang
	 */
	public long getCuaHangId();

	/**
	 * Sets the cua hang ID of this cua hang.
	 *
	 * @param cuaHangId the cua hang ID of this cua hang
	 */
	public void setCuaHangId(long cuaHangId);

	/**
	 * Returns the company ID of this cua hang.
	 *
	 * @return the company ID of this cua hang
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cua hang.
	 *
	 * @param companyId the company ID of this cua hang
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cua hang.
	 *
	 * @return the user ID of this cua hang
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cua hang.
	 *
	 * @param userId the user ID of this cua hang
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cua hang.
	 *
	 * @return the user uuid of this cua hang
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this cua hang.
	 *
	 * @param userUuid the user uuid of this cua hang
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cua hang.
	 *
	 * @return the user name of this cua hang
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cua hang.
	 *
	 * @param userName the user name of this cua hang
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cua hang.
	 *
	 * @return the create date of this cua hang
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cua hang.
	 *
	 * @param createDate the create date of this cua hang
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cua hang.
	 *
	 * @return the modified date of this cua hang
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cua hang.
	 *
	 * @param modifiedDate the modified date of this cua hang
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this cua hang.
	 *
	 * @return the ten of this cua hang
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this cua hang.
	 *
	 * @param ten the ten of this cua hang
	 */
	public void setTen(String ten);

	/**
	 * Returns the gio mo cua of this cua hang.
	 *
	 * @return the gio mo cua of this cua hang
	 */
	public Date getGioMoCua();

	/**
	 * Sets the gio mo cua of this cua hang.
	 *
	 * @param gioMoCua the gio mo cua of this cua hang
	 */
	public void setGioMoCua(Date gioMoCua);

	/**
	 * Returns the gio dong cua of this cua hang.
	 *
	 * @return the gio dong cua of this cua hang
	 */
	public Date getGioDongCua();

	/**
	 * Sets the gio dong cua of this cua hang.
	 *
	 * @param gioDongCua the gio dong cua of this cua hang
	 */
	public void setGioDongCua(Date gioDongCua);

	/**
	 * Returns the hoat dong of this cua hang.
	 *
	 * @return the hoat dong of this cua hang
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this cua hang is hoat dong.
	 *
	 * @return <code>true</code> if this cua hang is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this cua hang is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this cua hang
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the uu tien of this cua hang.
	 *
	 * @return the uu tien of this cua hang
	 */
	public int getUuTien();

	/**
	 * Sets the uu tien of this cua hang.
	 *
	 * @param uuTien the uu tien of this cua hang
	 */
	public void setUuTien(int uuTien);

	/**
	 * Returns the dia chi of this cua hang.
	 *
	 * @return the dia chi of this cua hang
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this cua hang.
	 *
	 * @param diaChi the dia chi of this cua hang
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the dien thoai of this cua hang.
	 *
	 * @return the dien thoai of this cua hang
	 */
	@AutoEscape
	public String getDienThoai();

	/**
	 * Sets the dien thoai of this cua hang.
	 *
	 * @param dienThoai the dien thoai of this cua hang
	 */
	public void setDienThoai(String dienThoai);

	/**
	 * Returns the kho hang ID of this cua hang.
	 *
	 * @return the kho hang ID of this cua hang
	 */
	public long getKhoHangId();

	/**
	 * Sets the kho hang ID of this cua hang.
	 *
	 * @param khoHangId the kho hang ID of this cua hang
	 */
	public void setKhoHangId(long khoHangId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.cuahang.model.CuaHang cuaHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.cuahang.model.CuaHang> toCacheModel();

	@Override
	public com.minimart.portlet.cuahang.model.CuaHang toEscapedModel();

	@Override
	public com.minimart.portlet.cuahang.model.CuaHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}