/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.minimart.portlet.cuahang.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TangCa service. Represents a row in the &quot;minimart_tangca&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.minimart.portlet.cuahang.model.impl.TangCaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.minimart.portlet.cuahang.model.impl.TangCaImpl}.
 * </p>
 *
 * @author Mai Thành Duy An
 * @see TangCa
 * @see com.minimart.portlet.cuahang.model.impl.TangCaImpl
 * @see com.minimart.portlet.cuahang.model.impl.TangCaModelImpl
 * @generated
 */
public interface TangCaModel extends AuditedModel, BaseModel<TangCa> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tang ca model instance should use the {@link TangCa} interface instead.
	 */

	/**
	 * Returns the primary key of this tang ca.
	 *
	 * @return the primary key of this tang ca
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tang ca.
	 *
	 * @param primaryKey the primary key of this tang ca
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tang ca ID of this tang ca.
	 *
	 * @return the tang ca ID of this tang ca
	 */
	public long getTangCaId();

	/**
	 * Sets the tang ca ID of this tang ca.
	 *
	 * @param tangCaId the tang ca ID of this tang ca
	 */
	public void setTangCaId(long tangCaId);

	/**
	 * Returns the company ID of this tang ca.
	 *
	 * @return the company ID of this tang ca
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tang ca.
	 *
	 * @param companyId the company ID of this tang ca
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tang ca.
	 *
	 * @return the user ID of this tang ca
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tang ca.
	 *
	 * @param userId the user ID of this tang ca
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tang ca.
	 *
	 * @return the user uuid of this tang ca
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tang ca.
	 *
	 * @param userUuid the user uuid of this tang ca
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tang ca.
	 *
	 * @return the user name of this tang ca
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tang ca.
	 *
	 * @param userName the user name of this tang ca
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tang ca.
	 *
	 * @return the create date of this tang ca
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tang ca.
	 *
	 * @param createDate the create date of this tang ca
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tang ca.
	 *
	 * @return the modified date of this tang ca
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tang ca.
	 *
	 * @param modifiedDate the modified date of this tang ca
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this tang ca.
	 *
	 * @return the ten of this tang ca
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this tang ca.
	 *
	 * @param ten the ten of this tang ca
	 */
	public void setTen(String ten);

	/**
	 * Returns the cua hang ID of this tang ca.
	 *
	 * @return the cua hang ID of this tang ca
	 */
	public long getCuaHangId();

	/**
	 * Sets the cua hang ID of this tang ca.
	 *
	 * @param cuaHangId the cua hang ID of this tang ca
	 */
	public void setCuaHangId(long cuaHangId);

	/**
	 * Returns the ca lam viec ID of this tang ca.
	 *
	 * @return the ca lam viec ID of this tang ca
	 */
	public long getCaLamViecId();

	/**
	 * Sets the ca lam viec ID of this tang ca.
	 *
	 * @param caLamViecId the ca lam viec ID of this tang ca
	 */
	public void setCaLamViecId(long caLamViecId);

	/**
	 * Returns the nhan vien ID of this tang ca.
	 *
	 * @return the nhan vien ID of this tang ca
	 */
	public long getNhanVienId();

	/**
	 * Sets the nhan vien ID of this tang ca.
	 *
	 * @param nhanVienId the nhan vien ID of this tang ca
	 */
	public void setNhanVienId(long nhanVienId);

	/**
	 * Returns the tang ca tu of this tang ca.
	 *
	 * @return the tang ca tu of this tang ca
	 */
	public Date getTangCaTu();

	/**
	 * Sets the tang ca tu of this tang ca.
	 *
	 * @param tangCaTu the tang ca tu of this tang ca
	 */
	public void setTangCaTu(Date tangCaTu);

	/**
	 * Returns the tang ca den of this tang ca.
	 *
	 * @return the tang ca den of this tang ca
	 */
	public Date getTangCaDen();

	/**
	 * Sets the tang ca den of this tang ca.
	 *
	 * @param tangCaDen the tang ca den of this tang ca
	 */
	public void setTangCaDen(Date tangCaDen);

	/**
	 * Returns the hoat dong of this tang ca.
	 *
	 * @return the hoat dong of this tang ca
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this tang ca is hoat dong.
	 *
	 * @return <code>true</code> if this tang ca is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this tang ca is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this tang ca
	 */
	public void setHoatDong(boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.minimart.portlet.cuahang.model.TangCa tangCa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.minimart.portlet.cuahang.model.TangCa> toCacheModel();

	@Override
	public com.minimart.portlet.cuahang.model.TangCa toEscapedModel();

	@Override
	public com.minimart.portlet.cuahang.model.TangCa toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}